- docs/netcdf.m4
- ncdump/nccopy.1
- ncdump/ncdump.1
- ncgen/ncgen.1
- ncgen3/ncgen3.1
Fixes `-` signs on manpages.
See <https://lintian.debian.org/tags/hyphen-used-as-minus-sign.html>.
> hyphens used as minus signs

- ncdump/nccopy.1
Most of these issues were fixed in #101, but the patch included in the Debian package and forwarded in the PR was updated afterward to include this remaining issue.
> Fix another hyphen-used-as-minus-sign issue in nccopy.1 man page.

- libsrc5/nc5dispatch.c
There is a case that handles a memtype of NC_INT64, so the code
should not error out if that memtype is passed in.  This type is also handled in the other file types, so not sure why it should
cause invalid values error in parallel-netcdf mode.
> Remove error check for NC_INT64 type

- oc2/ocinternal.c
that code path is common to all win32 platforms: msvc & mingw/cygwin
> fix mingw build

- Makefile.am
this is the standard, the .def along with the export lib .dll in /bin, and the import lib or static lib in /lib
> install .def to /bin

- oc2/oc.h
- oc2/ochttp.c
- oc2/ocrc.c
As reported in [Debian Bug #749511](https://bugs.debian.org/749511), inconsistent return types can cause the build to fail (when using tools from the [cbmc](https://tracker.debian.org/pkg/cbmc) package).
This PR forwards the three patches by Michael Tautschnig, who also reported the issue in Debian.
> Fix inconsistent return type.

- libdispatch/dvar.c
Replace static array dimensioned to NC_MAX_DIMS with dynamic memory allocation of correctly sized array.
> Remove hard-wired use of NC_MAX_DIMS

- CMakeLists.txt
- libsrc4/nc4var.c
Add local include paths first
If a netcdf.h include file exists in any of the include paths
specified for HDF5 or other libraries, it was being included
instead of the local netcdf.h file in the source directory
since the local include paths were added at the end of the
compile line instead of at the beginning.
This commit puts the local include paths at the beginning
of the compile line
> Cmake -- Add local include paths at beginning of compile line

- cf
- ncdump/cdl/Makefile.am
- ncdump/cdl/ref_keyword.cdl
- ncdump/expected/Makefile.am
- ncdump/expected/ref_keyword.dmp
- ncdump/ncdump.c
- ncdump/tst_ncgen_shared.sh
NetCDF-c Github issue #178 / esupport BNL-694121
The ncgen man pages says:
> Note also that the words variable',dimension', data',group', and
> `types' are legal CDL names, but be careful that there is a space be-
> tween them and any following colon character when used as a variable
> name. This is mostly an issue with attribute declarations.
Ncdump does not obey this rule.
The fix is to modify ncdump/ncdump.c to check if a variable name is
a keyword.
Also added test case.
> NetCDF-c Github issue #178

- .travis.yml
- CONTRIBUTING.html
- cf
- cf.cmake
- configure.ac
- libsrc/dim.c
- ncdump/CMakeLists.txt
- ncdump/Make0
- ncdump/Makefile.am
- ncdump/chunkspec.c
- ncdump/ncdump.c
- ncdump/ncdump.h
- ncdump/tst_dimsizes.c
- ncdump/tst_dimsizes.sh
- ncgen/genbin.c
- ncgen/genlib.h
- ncgen/getfill.c
- ncgen/main.c
- ncgen/ncgen.y
- ncgen/offsets.h
- ncgen/semantics.c
NetCDF-c Github issue #185
The code in libsrc/dim.c has not been upgraded to support
CDF-5 format.
Rule we are implementing sets the max dimension sizes as follows:
Classic:	CDF-1	NC_MAX_INT - 3    = 2147483647 - 3
64 bit Offset:	CDF-2	NC_MAX_UINT - 3	  =  4294967295 - 3
64 bit Data:	CDF-5	NC_MAX_UINT64 - 3 = 18446744073709551615 - 3
The -3 is to handle rounding.
> The max dimension sizes do not take CDF-5 format into account.

- ncgen/ncgen.1
The lintian QA tool reported this typo during the Debian package build process.
> Fix 'atttributes' typo, replace with 'attributes'.

- nc_test4/bm_file.c
The constant NC_MAX_DIMS is used to dimension the `dimids` arrays which are use to retrieve the dimension ids corresponding to the variables dimensions.  By definition, the maximum number of dimension ids is `NC_MAX_VAR_DIMS` as is documented in the `nc_inq_var` documentation:
http://www.unidata.ucar.edu/software/netcdf/netcdf-4/newdocs/netcdf-c/nc_005finq_005fvar.html
dimids   Returned vector of *ndimsp dimension IDs corresponding to the variable dimensions. The caller must allocate enough space for a vector of at least *ndimsp integers to be returned. The maximum possible number of dimensions for a variable is given by the predefined constant NC_MAX_VAR_DIMS. 
Although the default or standard values of NC_MAX_DIMS and NC_MAX_VAR_DIMS are the same, the correct value to be used here is …
> Replace NC_MAX_DIMS with correct NC_MAX_VAR_DIMS

- nc_test4/tst_files3.c
The count and start arrays are dimensioned to NC_MAX_DIMS even though the maximum size should be NDIMS which is set to 3; possibly, the maximum size could be 2 since only indices 0 and 1 are used to access both start and count.  I left it at NDIMS since that matches the number of items in the initialization and is consistent with other uses in the file.
> Fix incorrect array size specification

- include/nc4internal.h
- libsrc4/nc4file.c
- libsrc4/nc4internal.c
Clean up the handling of hdf5 initialization by
creating an nc4_hdf5_initialize(void) function
plus nc4_hdf5_initialized flag.
Also fix potential null exception in nc4internal.c
> Clean up the handling of hdf5 initialization

- nc-config.cmake.in
A couple of the `has_XX` variables seem to have values of OFF or ON instead of `empty` or ON which causes incorrect output from the nc-config script since it is using `-z` to test whether the variable is non-empty.  This causes nc-config to incorrectly report that the library supports HDF5 or has the version 2 api.
I think these are the only tests that need the extra testing against OFF and I think that the value will always be ON or OFF and not some other variant (FALSE, NO, ...).
> Generate correct results from cmake-generated nc-config

- include/netcdf_meta.h.in
If pnetcdf support is enabled, then  NC_HAS_PARALLEL is defined to 1 even if HDF5 is not enabled.  Fix comment to make this clearer.
> Update comment in netcdf_meta.h.in

- libsrc4/nc4file.c
- libsrc4/nc4hdf.c
- libsrc4/nc4var.c
The var struct has a 'dim' field which was not being used
Instead, the dimids field would always search for the dim
with the matching dimid.  For db with large numbers of dims,
this could be a significant time sync.
Modified code to always set var-dim[i] when var->dimids[i] was
set (if the dim existed at that point).  Then use the var->dim
field instead of var->dimids and search whenever requested.
All var->dim accesses are protected by asserts that verify
non-null and that the var->dim[]->dimid == var->dimids[].
> Use dim field of var instead of finding dim from var->dimids.

- include/nc3internal.h
- include/nc_hashmap.h
- libsrc/dim.c
- libsrc/nc_hashmap.c
- libsrc/v1hpg.c
- libsrc/var.c
The addition of the nc_hashmap to facilitate quick
retrieval of var and dim by name did not take into
account key collisions -- two or more var or dim names hashed
to the same value.  If the keys matched, it assumed
that the names matched also.
This change fixes this incorrect assumption and
checks the key (which is the hash of the name)
and if the keys match, it also checks that the names
match.
While there have been no instances of duplicate keys,
they are certain to occur and cause difficult to
debug issues. This fix eliminates that defect.
> Nc3 hashmap fix

- libsrc4/nc4file.c
If in parallel mode and the H5Fcreate fails, then the h5->comm field may/will point to MPI_COMM_NULL instead of to a valid communicator.  If that is passed to MPI_Comm_free, then the code will core dump down in the MPI_Comm_free function and not return a valid return status to the caller routine. If communicator is checked, then execution proceeds back up the call tree and caller can report a better error message about the failed file create.
> Check for valid MPI_Comm before freeing

- cf
- libdap2/ncd2dispatch.c
- libsrc4/nc4attr.c
- libsrc4/nc4file.c
- libsrc4/nc4info.c
- libsrc4/nc4internal.c
- nc_test4/Make0
- nc_test4/tst_empty_vlen_unlim.c
- nc_test4/tst_misc.sh
- ncdump/ncdump.c
re: github netcdf-c issue #271
This occurs for several reasons, including:
1. using H5Aopen_name instead of H5Aexists to test if attribute exists.
2. using H5Eset_auto instead of H5Eset_auto2.
There are probably others that will have to be extinguished as encountered.
p.s Hope I did not overdo this and kill too much.
> HDF5 generates unnecessary error messages when netcdf4 logging enabled

- cf
- configure.ac
- libsrc4/nc4file.c
- nc_test4/CMakeLists.txt
- nc_test4/Makefile.am
- nc_test4/tst_hdf4_read_var.sh
- ncdump/Make0
Fix in nc4file.c.
Not sure how this ever worked for any variable.
What is also weird is that the dim hash is
apparently being computed.
> The name hash for hdf4 variables was not being computed.

- cf
- libdap2/Makefile.am
- libdap2/constraints.c
- libdap2/dceparse.c
- libdap2/dceparselex.h
- libdap2/dcetab.c
- libdap2/dcetab.h
- libdap2/ncd2dispatch.c
A netcdfgroup email
(Re: [netcdfgroup] nccopy fails with corrupted double link list)
shows that ncdump/nccopy was returning EPERM instead of
NC_EDAPCONSTRAINT as an error when we have a malformed constraint.
Also clean up a potential bug that might occur if the user invokes
nc_set_default_format before calling nc_open on a dap url.
> Make ncdump/nccopy return a better error when given a bad constraint in a dap url

- include/netcdf.h
The single commented out line was the only use of a c-99 or c++ style comment in the entire file.  Either remove line completely or change to c-89 style comment to permit use with projects that still require c89 compatible code.
> Eliminate c++ or c99-style comment

- libdap2/dceparselex.h
A couple of people have reported that the multiple definitions of
typedef struct DCEparsestate
near lines 10 and 42 causes compiler
problems with some versions of gcc.
remove the second typedef.
> mutiple typedefs causing compile problems

- libsrc/dim.c
- libsrc/var.c
Pull request to fix issue #282 
Patch included in discussion of that issue, but easier to apply if supplied as pull request. 
The problem is that the name was being updated prior to the old
variable being removed from the hashmap. It checks whether the key and
the name of the variable being removed match, but since the name had
already been updated, the names did not match so the variable was not
removed. This patch removes the variable from the hashmap first,
then updates the name, and then adds the variable with the new name to
the hashmap.
Similar change for renaming dimensions.
> Fix variable and dimension renaming for nc3 with hashmap

- libsrc4/nc4hdf.c
There was a mismatch between the allocated size of att_name and the size that H5Aget_name was told the size was.
> Fix att_name size

- libsrc4/nc4hdf.c
If H5Aopen_idx on line 1964 fails, then attid will be < 0.  The BAIL will goto exit at line 1989 and then the test of "if (attid ...)" at line 1995 will pass (attd != 0) and then call H5Aclose(attid) with a negative attid.    Similar issue for spaceid.  
Result of function if probably the same since there is a failure somewhere, but more difficult to track down if looks like failure is happening in the wrong place.
> Fix incorrect test

- nc-config.cmake.in
- nc-config.in
PR #235 fixed a couple of hard-coded paths in `nc-config.cmake.in`. This PR fixes them in `nc-config.in`, used by autotools. It also adds some flags which I think should be included: `--libdir`, by analogy with `--includedir`; `--has-fortran`, rather than the specific `--has-{f90,f03}`, which are only available if `nf-config` is found; and the flags/libs needed for the C++ API, which can be checked with `ncxx{,4}-config`, assuming it's been found (by analogy to the Fortran flags/libs).
> Some small fixes for nc-config

- nc-config.cmake.in
- nc-config.in
Another trivial patch, I'm afraid. `usage` needs to be called with an exit value. Incorrect options won't set the exit value, so are trickier to detect, i.e. you currently can't do something like
if [[ nc-config --wrong-option ]]; then
to detect wrong options.
> Usage function called wrong in nc-config

- ncdump/vardata.c
If an empty line is passed to this routine, then there is an invalid memory access at the cp[nn-1] line.  This becomes cp[-1] which is invalid.
> Fix invalid array access

- docs/netcdf.m4
- docs/old/netcdf-f90.texi
- ncgen/ncgen.1
The lintian QA tool reported a couple of spelling errors for the most recent Debian package build:
* characers -> characters
* varaible  -> variable
> Fix spelling errors.

- include/nc4internal.h
- libsrc4/nc4attr.c
- libsrc4/nc4file.c
- libsrc4/nc4grp.c
- libsrc4/nc4hdf.c
- libsrc4/nc4info.c
- libsrc4/nc4internal.c
- libsrc4/nc4var.c
The use of the linked list for var storage on nc4-format files can cause slowdowns for files with several variables.  We have seen read/write times of 10s of minutes for some complex files.  Reading/writing the same files with these changes applied has reduced the read/write times to a few seconds.
Basically, the change replaces the linked_list with an array.  Currently only done for vars, but a similar change could be done for dims.
All tests pass and the changes have been in production use for a few months at out site.
This is discussed in #234
> Replace linked list with array for var storage in netcdf-4 format

- h5_test/tst_h_par.c
This fixes the following compile error when building parallel tests:
```
mpicc -DHAVE_CONFIG_H -I. -I../../h5_test -I..  -I../../include -I../../oc2  -I/usr/include/hdf  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -c -o tst_h_par.o ../../h5_test/tst_h_par.c
../../h5_test/tst_h_par.c: In function 'main':
../../h5_test/tst_h_par.c:89:55: error: 'ERR' undeclared (first use in this function)
if ((fapl_id = H5Pcreate(H5P_FILE_ACCESS)) < 0) ERR;
^~~
../../h5_test/tst_h_par.c:89:55: note: each undeclared identifier is reported only once for each function it appears in …
```
> Add missing #include "err_macros.h" to tst_h_par.c

- libsrc4/nc4hdf.c
The only way to need to extend a variable is if it has at least one unlimited dimension. Since metadata for variables is the same across processors, can check whether a variable has at least one unlimited dimension and it not, then there is no need to call the MPI_Allreduce to check whether the variable needs to be extended.  Simple addition eliminates MPI_Allreduce call for many variables.
> Eliminate an MPI_Allreduce in many cases

- ncdump/ncdump.c
re: e-support (XKJ-645277) and github issue #351.
A set of typecasts in the function
print_enum_type in ncdump/ncdump.c cause some
compilers to complain about type punning:
"warning: dereferencing type-punned pointer will
break strict-aliasing rules"
Fix is to cast to void* before casting to final
value.  There may be other occurrences in some
of the older netcdf-c code.
> Fix aliasing/type-pun problem in ncdump

- CMakeLists.txt
- config.h.cmake.in
- configure.ac
- libsrc4/nc4file.c
In HDF5-1.10 and later, the group implemented collective metadata operations. The rationale and discussion is at https://support.hdfgroup.org/HDF5/docNewFeatures/NewFeaturesCollectiveMetadataIoDocs.html
Another discussion showing some CGNS timings is at https://hdfgroup.org/wp/2015/08/parallel-and-large-scale-simulation-enhancements-to-cgns/
We have also noticed the slow file open and close times with exodus when running on processor counts exceeding 1024. As an example, with a run on 32,768 processors, the time to open the files was 827.7 seconds.  With the changes in this pull request implemented, the time dropped to 15 seconds.  The time seems to increase as num_proc^2 at large num_proc without these changes.
The changes to CMakeLists.txt include the changes from hdf5 to …
> Use HDF5 collective metadata operations if available.

- ncgen/ncgen.l
- ncgen/ncgen.y
- ncgen/ncgenl.c
- ncgen/ncgeny.c
- ncgen/ncgeny.h
It appears that the token OPAQUE in ncgen.y is somehow in interference
with something  in the HDF4 code. So, I changedthe OPAQUE -> OPAQUE_
and that appears to fix the problem with bison when HDF4  is enabled.
(See also https://github.com/Unidata/netcdf-c/pull/366).
I am surprised that other tokens did not also cause this problem, but
apparently not.
I should also note that Visual Studio error message leave something to be desired.
when Visual Studio complained about token 'constant' it turn out that it mean token type,
not the actual token named 'constant'. Instead the actual token that was causing the
problem was 'OPAQUE'.
> HDF4-visual studio interference

- libsrc4/nc4file.c
Changed from discovering attributes and then looping through them to using H5Aiterate2 instead. This was needed to port netcdf-c to work with a Fast-Forward version of HDF5.
> Use H5Aiterate2 in read_var.

- RELEASE_NOTES.md
- libdap2/env
- libdap2/ncd2dispatch.c
- ncdap_test/expectremote3/test.01.1.dmp
- ncdap_test/expectremote3/test.07.1.dmp
- ncdap_test/expectremote3/test.07.3.dmp
- ncdap_test/expectremote3/test.07.4.dmp
- ncdap_test/tst_remote.sh
- oc2/ocnode.c
- oc2/ocnode.h
Re: github issue https://github.com/Unidata/netcdf-c/issues/373
Github issue https://github.com/Unidata/netcdf-c/issues/152
requested that "orphaned" DAS attributes be included in the netcdf
metadata as global variables. The term orphaned here meant that
they were not connected to any variable in the DDS.
This was done in pull request https://github.com/Unidata/netcdf-c/pull/164
However, some servers (e.g. Thredds) include attributes for variables not
specified in a constraint expression, but which exist in the full DDS.
So I was adding these to the set of global attributes, but in retrospect
this should not have been done: they should have been elided.
Solution: modify oc2 code to be more discriminatory about
which orphaned attributes to include. Specifically elide orphan
attributes that …
> Suppress selected orphan opendap attributes

- cf
- ncgen/CMakeLists.txt
- ncgen/Makefile.am
- ncgen/run_nc4_tests.sh
- ncgen/run_tests.sh
- ncgen/semantics.c
- ncgen/tst_gattenum.cdl
Apparently we have no .cdl test cases that have a global attribute whose type is an enum.
Turns out this case fails because of an oversight in ncgen.
This pr fixes that problem (in semantics.c).
Also added test case .cdl file: tst_gattenum.cdl
> Fix bug in ncgen handling of global, enum valued, attribute.

- docs/file_format_specifications.md
- libsrc4/nc4hdf.c
- nc_test4/tst_strings2.c
Fixes #298
The new test, a minor modification of `tst_strings2.c` to use `NC_CHAR` and some non-ASCII characters, passes on Travis-CI. Let me know if you need anything else.
You'll notice that I didn't modify the reading code at all -- older versions of netCDF4 already read fixed width ASCII as NC_CHAR. Thus this should present no backwards compatibility concerns.
> Switch NC_CHAR on netCDF4 to use ASCII

- libsrc/Makefile.am
- libsrc4/nc4file.c
- nc_test4/tst_fill_attr_vanish.c
- nc_test4/tst_vars2.c
This patch is for issue #384, NC_ELATEFILL error code is not properly returned.
In NC4_enddef() before nc_enddef() returns, the patch marks all variables "written".
I hope this is the right fix. It passed all tests.
> patch for issue 384 - NC_ELATEFILL error for NetCDF-4 files

- libdispatch/dattput.c
NC_EINVAL is returned when trying to set attribute _FillValue for global variables.
This patch is for issue #388
> patch for #388 - setting global _FillValue

- h5_test/tst_h_enums.c
The documentation for `H5Tget_member_name` states that the memory returned should be freed by `H5free_memory` instead of `free`.  I was getting test failure until I changed this to call H5free_memory on a Mac OS Sierra system with hdf5-1.9.236
> Use H5free_memory instead of free

- libsrc4/nc4info.c
Current code only frees char* text in error cases. It should
also free it in success case.
Otherwise Valgrind reports a leak:
==28536== 64 bytes in 1 blocks are definitely lost in loss record 4 of 13
==28536==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==28536==    by 0xE673496: NC4_buildpropinfo (nc4info.c:239)
==28536==    by 0xE67313B: NC4_put_propattr (nc4info.c:162)
==28536==    by 0xE65BF35: nc4_create_file (nc4file.c:468)
==28536==    by 0xE65C0AC: NC4_create (nc4file.c:564)
==28536==    by 0xE608A08: NC_create (dfile.c:1773)
==28536==    by 0xE607E6A: nc__create (dfile.c:511)
==28536==    by 0xE607E23: nc_create (dfile.c:440)
Credit to OSS Fuzz
> Fix memory leak in NC4_put_propattr()

- libsrc/ncx.m4
Running a build on the .nc file corresponding to the below ncdump output
with -fsanitize=undefined raises
libsrc/ncx.c:4722:26: runtime error: left shift of 255 by 24 places cannot be represented in type 'int'
This is due to *cp being promoted to int before doing the left shift, instead
of the intended unsigned. So do the cast to unsigned internally rather than
externally
ncdump file to reproduce:
netcdf temp {
dimensions:
y = UNLIMITED ; // (0 currently)
x = 109067 ;
variables:
byte t(y, x, x) ;
data:
}
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2265
Credit to OSS Fuzz
> Fix undefined left shift in ncx_get_size_t()

- configure.ac
- dap4_test/test_meta.sh
- libdap2/nccommon.h
- libdap2/ncd2dispatch.c
- libdap4/d4file.c
- libdap4/d4read.c
- libdap4/ncd4types.h
- libdispatch/dfile.c
- libsrc4/nc4file.c
If DAP (2 or 4) is enabled, but diskless is disabled, then the
dap code will create a real temporary file in which to store the
converted metadata for the DAP .dds or .dmr.
It was assumed that the nc_close code would reclaim the
temporary file. For DAP2, reclamation occurs in the ncio
code. For DAP4, it was assumed that the libsrc4 code would do
the reclamation, but for whatever reason, this is not happening.
Thus, in this situation, a temporary file is left in the file
system. Aside from being irritating to users, this screws up
'make distcheck'.
So the DAP4 code is fixed to ensure that the temporary file is
properly reclaimed independent of the libsrc4 code.
> Reclaim DAP temporary files

- nc_test/tst_formatx_pnetcdf.c
Call nc_close, which calls MPI_File_close, to avoid MPI wraning messages on MPI objects are still allocated.
> close files in tst_formatx_pnetcdf.c

- CMakeLists.txt
- configure.ac
- libsrc/ncx.m4
- libsrc/putget.m4
This pull request is to silence the NC_EBADTYPE error that NCO ncpdq encountered when built with netcdf 4.5.0-rc2. 
Please note this PR does not resolve the fundamental issue of whether or not the data type of a variable's _FillValue attribute should match with the variable's.
See discussion in #458
> avoid calling NC3_inq_var_fill when ERANGE_FILL is enabled

- docs/guide.dox
Part of #460.
Some documentation fixes. No code changes.
> Fix a bunch of references, and some formatting, in the doxygen C guide

- nc-config.cmake.in
The `has_dap4` define was missing trailing @.  I also added tests similar to other code to result in lowercase yes no for `--has_dap4`.
I'm not as sure about the `--has-dap` changes.  One place was outputting `$has_dap` which is never defined.  I think that the intent is that `--has-dap` returns the same as `--has-dap2` so made changes that did that.  If that isn't the intent, then let me know and I will back out those changes and only leave the dap4-related change.
> Fix (I think) the --has-dap and --has-dap4 output

- nc-config.cmake.in
I was getting "yes" output from some of the options which were not enabled.  This was due to two reasons:
* If CMake set the variable to "OFF", then the `-z $var test` would fail and `$var` would be set to "yes" even though it should be "no"
* If CMake set the variable to empty string (`has_var=""`), then the `-z $has_var` test would also fail and set it to yes instead of no.
With these changes, it looks like I am getting the correct output from nc-config consistent with my configuration options.
> Fix bad output from nc-config

- libdap4/d4rc.c
- oc2/ocinternal.c
It is imperative that this fix goes into
v4.5-release-candidate branch and master branch ASAP.
The bug occurs in d4rc.c where strcmp is being applied to NULL.
Also, the code in which it occurs is debugging code, so it needs
to be #ifdef'd.  This fix may cause minor conflicts with other
outstanding pull requests that fix the same bug. But the
conflicts should be minor and easy to resolve.
> Important fix to d4rc.c

- docs/CMakeLists.txt
- docs/Doxyfile.in
- docs/Makefile.am
- docs/internal.dox
- docs/mainpage.dox
- libdispatch/dfile.c
re: issues https://github.com/Unidata/netcdf-c/issues/493 and https://github.com/Unidata/netcdf-c/issues/474
Update docs/internal.dox to
provide a more accurate description
of how to add a new dispatch table.
Also remove dispatch.dox as superfluous.
> Update dispatch table documentation

- libdap4/d4meta.c
- nc_test/util.c
The nc_test/util.c error is a typo. The libdap4/d4meta.c error only is shown
when using a 64 bit machine because then |size_t| == 64 bits
and |int| = 32bits.
> Fix dap4 related warnings in https://github.com/Unidata/netcdf-c/issues/501.

- h5_test/tst_h_dimscales.c
Fixes #505.
Fixes #363.
Fixes #244.
Simple fix - passed parameter was size int, but was being cast to int64. As a result, there was a memory overflow which may blow away the loop counter variable.
Hilarious confusion then ensued.
> fixed memory problem in tst_h_dimscales

- nc_test4/tst_vars.c
Fixes #508.
Very simple fix. Target array was too small in an off-by-one error in one of the dimensions.
Kind of looks like my code so probably I was the programmer who introduced this bug. ;-)
> fix for tst_vars.c memory overflow

- nc_test4/tst_empty_vlen_unlim.c
Part of #520.
Fixes #510.
This test had some simple memory leaks, easily fixed.
> fixed memory leaks and warnings in nc_test4/tst_empty_vlen_unlim.c

- libsrc4/nc4hdf.c
Fixes #526.
Simple for some compile warnings in libsrc4/nc4hdf.c.
> fixed warnings in libsrc4/nc4hdf.c

- libsrc4/nc4info.c
- libsrc4/nc4var.c
Fixes #528.
Fixes #529.
Easy fixes for some compile warnings. The function with warnings in nc4var.c was not used anywhere so I removed it.
> fixed compile warnings in nc4info.c/nc4var.c

- libsrc4/nc4file.c
Fixes #507.
There is a memory error in the code when reading a file that contains attributes of type REFERENCE. In this case, the code tries to set a field in a struct that has already been freed.
This fix checks that the struct memory is still available before attempting to set the field.
> fixed memory error in handling of (ignored) reference atts in HDF5 file

- libdispatch/dfile.c
Fix for the leaks in nc_create().
I thought I had got these in the last batch of memory fixes, but I missed it.
Fixes #506 (and this time I really mean it).
> fix for leaks in nc_create as seen in nc_test4/tst_files

- configure.ac
- libsrc/ncx.h
I believe it is safe to type define "schar" to "signed char" no matter char is signed or unsigned. This patch silence the following compile warnings.
```
netcdf-c/libsrc/nc3internal.c:1778:80: warning: passing 'signed char *' to parameter of
type 'schar *' (aka 'char *') converts between pointers to integer types with different sign
[-Wpointer-sign]
case NC_BYTE:   return ncx_getn_schar_schar        (&xp, 1,        (signed char*)fill_value);
^~~~~~~~~~~~~~~~~~~~~~~~
netcdf-c/libsrc/ncx.h:332:64: note: passing argument to parameter 'ip' here
ncx_getn_schar_schar (const void **xpp, size_t nelems, schar  *ip);
^
1 warning generated.
```
> typedef schar to signed char

- oc2/daplex.c
Fixes https://github.com/Unidata/netcdf-c/issues/569
Serious bad on my part. For some reason, I changed the set of
characters allowed n a DAP name. In particular, characters that
are legal according to the DAP spec were removed. So when one of
this removed characters was encountered, it produced a parse
error.
In this case, the offending character was a single quote character in the name:
Blackadar's_mixing_length_scale_hybrid
The reason it worked for java is because the escape character set
is correct and different than the one in the netcdf-c dap code.
> Fix dap legal name character handling

- include/nc_tests.h
- nc_test/tst_inq_type.c
- nc_test4/tst_converts.c
- nc_test4/tst_files.c
Only test code changes in this PR - no library code.
Some tests were using NC_CDF5 without checking ENABLE_CDF5. Fixed in this PR, as well as a similar case with NC_NETCDF4.
Fixes #590. This passes my CI testing, which currently tests 15 different configurations (except the --disable-utilities built until a pending PR is merged).
> Fix some tests use of ENABLE_CDF5

- nc_test4/tst_interops5.c
Fixes #593 
One of these was an actual problem BTW, the use of a hid_t * where an int * is expected. (And they are different sizes).
> fixed warnings in tst_interops5.c

- h5_test/tst_h_dimscales1.c
Fixes #598.
Test file name was same as another test, causing tst_h_dimscales1.c to fail when used with make -j.
> fixed file name in test which was breaking make -j check in h5_test

- libdispatch/dfilter.c
- libsrc4/nc4internal.c
- nc_test4/tst_filterparser.c
Fixes 3 memory leaks, in tst_filterparser.c, nc4internal.c, and dfilter.c.
Fixes #648.
Fixes #645.
@WardF it would be helpful if you could merge this PR next, then my CI address sanitizer build will work again, and I can continue to spot any memory errors introduced by merges. Otherwise they will accumulate and be harder to fix.
> BUGFIX: Fixes 3 memory leaks, in tst_filterparser.c, nc4internal.c, and dfilter.c

- include/netcdf_par.h
- libdispatch/dparallel.c
Part of #253.
Added missing doxygen documentation for some parallel functions, including nc_create_par(), an important function that needs to be documented.
No code changes in this PR - documentation only.
> DOCUMENTATION: add docs for nc_create_par() and other functions

- libdispatch/dvar.c
At suggestion of @wkliao, I have improved the documentation of nc_inq_var_fill() to warn users about providing enough memory for the returned fill value.
Fixes #327.
> DOCUMENTATION: note of memory issues in nc_inq_var_fill()

- libdispatch/dattget.c
Added return code documentation, also example of nc_get_att(). This cleared up doxygen warnings for this file.
Fixes #639.
> DOCUMENTATION: fixed doxygen warnings nc_get_att() and related functions in dattget.c

- configure.ac
Fixes #638.
Set an automake variable that was being set in CMake build, but not autotools build.
Clears up a doxygen warning.
> set DOXYGEN_SERVER_BASED_SEARCH in configure.ac

- libdispatch/dattinq.c
Part of #644.
Fixed documentation warnings by adding documentation of return codes to public att inq functions. Also added examples so each public function now has an example.
Documentation changes only in this PR. No code changes.
> DOCUMENTATION: fixed doxygen warnings in dattinq.c

- nc_test4/tst_atts1.c
- nc_test4/tst_files5.c
- nc_test4/tst_grps2.c
- nc_test4/tst_h_files3.c
- nc_test4/tst_h_vl2.c
- nc_test4/tst_interops3.c
- nc_test4/tst_large3.c
Fixes #617.
Fix all the data file names in nc_test4 tests.
This allows make -j check to succeed in nc_test4.
> fixed names of output files to enable parallel make check in nc_test4

- libsrcp/ncpdispatch.c
Fixes #647.
Several fixes needed to get pnetcdf build working. @DennisHeimbigner please glance at the code and tell me if you think it is correct WRT the options_maskp argument. (I surmise that you took that out of the parameters and now pass it in with params in the HDF4 code?)
Also had to add the new nc_def_var_filter() function to the dispatch table for pnetcdf.
@WardF please make this PR a priority since my pnetcdf CI build will be broken until this is merged. I believe there is no other pnetcdf CI build at the moment.
> BUGFIX: fixed pnetcdf issues

- include/rnd.h
- libsrc4/nc4file.c
- libsrc4/nc4var.c
- nc_test4/Makefile.am
- nc_test4/tst_chunk_hdf4.c
- nc_test4/tst_interops2.c
- ncdap_test/t_dap3a.c
- ncdump/indent.h
- ncdump/isnan.h
- ncdump/ncdump.c
- ncdump/nctime0.h
- ncdump/utils.h
- ncdump/vardata.h
- ncgen/nc_iter.h
This PR contains more changes from PR #755, which was not merged. I am breaking it into smaller pieces.
In this PR I add guards to all the header files that need them, and remove some unneeded HDF4 checking code in nc4_dev_var() and nc4_def_var_extar(). (Recall that HDF4 is read-only, so these functions can't be called for HDF4 anyway.)
Also added necessary parameter checks for nc4_def_var_extra() and nc4_rename().
Also added some test code in support of checking HDF4 changes. I have much more test code on branch ejh_fill_values but I think I need to see all the existing PRs merged, then I can do a compare with master and see what is left on ejh_fill_values. There are certainly some important string fill value fixes there, so I hope this can happen soon.
Fixes #759.
Fixes #757.
Fixes …
> Fixes of warnings, check return values, added guards for headers that needed them, remove unneeded HDF4 checks

- libsrc4/nc4var.c
- nc_test4/tst_chunks.c
Fix #299
The conditions to make this error are the following:
* Two variables with different chunk sizes
* Both variables write on the same unlimited dimension
* The first variable has already written data when the second variable is created
> Allow multiple vars with different chunks on the same unlimited dim

- libdispatch/dutil.c
I realize strncat is being eliminated, but in case the elimination isn't done prior to release, this patch should be applied.
> Eliminate potential buffer overflow

- libdispatch/ncuri.c
Eliminate this warning from clang:
```
TPL/netcdf/netcdf-c/libdispatch/ncuri.c:914:31: warning: for loop has empty body [-Wempty-body]
for(p=sp,q=sp+1;(*p++=*q++););
^
TPL/netcdf/netcdf-c/libdispatch/ncuri.c:914:31: note: put the semicolon on a separate line to silence this warning
1 warning generated.
```
> Eliminate warning from clang compilers.

- include/netcdf.h
Make it clear that NC_MAX_DIMS, NC_MAX_VARS, and NC_MAX_ATTRS limits are not enforced after netcdf-4.5.0 to avoid confusion
> Make it clear that limits are not enforced

- include/nc4internal.h
- include/nc_tests.h
- include/netcdf.h
- libdispatch/dtype.c
- libdispatch/dutil.c
- libdispatch/ncuri.c
- libsrc/Makefile.am
- libsrc4/nc4dim.c
- libsrc4/nc4grp.c
- libsrc4/nc4internal.c
- libsrc4/nc4type.c
- libsrc4/nc4var.c
- nc_test4/CMakeLists.txt
- nc_test4/Makefile.am
- nc_test4/run_par_test.sh
- nc_test4/tst_chunks.c
- nc_test4/tst_grps.c
- nc_test4/tst_rename.c
- nc_test4/tst_simplerw_coll_r.c
- nc_test4/tst_types.c
OK, my last attempt was too ambitious. Hubris!!
This PR does not include Denis' PRs.
This includes:
@wkliao PR #466
@gdsjaar #764, #765, #766 
@Lnaden PR #760.
And from me, #763, #769, #780, #786.
After this has passed through testing @WardF will merge it and close the PRs listed above. 
After this merge we will take another pass through the remaining PRs to see what can be merged.
From PR #760
Fix #299
From PR #786 
Fixes #785.
Fixes #784.
Fixes #783.
Fixes #782
From PR #780:
Part of #701.
Fixes #779.
Fixes #777.
Fixes #776.
Fixes #775.
Fixes #774.
From PR #769 
Part of #441.
From PR #763 
Part of #597.
Fixes #741.
Fixes #746.
Fixes #749.
Thanks to all for your contributions to netCDF.
> Combination of 9 outstanding non-controversial PRs

- CMakeLists.txt
- configure.ac
- libnetcdf.settings.in
- nc_test4/tst_converts.c
When erange-fill is enabled, nc_test4/tst_converts.c fails with the following error message.
This is also reported in #424
```
*** Testing conversion in netCDF CDF5 files... Sorry! Unexpected result,
netcdf-c/nc_test4/tst_converts.c, line: 152
1 failures
1 errors detected! Sorry!
```
No such error would occur when erange-fill is disabled (NetCDF default mode).
This PR also add an item in libnetcdf.settings.in to report whether erange-fill is enabled or not.
> fix tst_converts.c when enable-erange-fill is set

- libsrc4/nc4var.c
Recent refactorings removed the use of these variable, but they were still defined.  Removing to eliminate unused variable warnings.
> Recent refactoring removed uses of variables

- cf
- libdispatch/dfilter.c
re: GH Issue https://github.com/Unidata/netcdf-c/issues/806
Change byteswap8 -> NC_byteswap8.
> Incorrect reference to byteswap8 in libdispatch/dfilter.c

- ncgen/genbin.c
* level is unsigned, so can never be < 0
* If level is 0, then don't enable deflate filter.
> Fix compression level settings

- include/nc_tests.h
- libsrc4/nc4hdf.c
- libsrc4/nc4var.c
- nc_test4/tst_chunks.c
- nc_test4/tst_rename.c
- nc_test4/tst_strings.c
- nc_test4/tst_vars.c
- nc_test4/tst_vars2.c
This contains extra tests, and fixes for the fill values of strings.
Also contains the rename tests, including a couple of commented out lines which show where some rename problems remain.
Fixes #727.
Fixes #732.
> extra tests, plus fill value fixes for string type

- libsrc4/nc4var.c
- nc_test4/tst_rename.c
Renames have been a problem for a long time - since the beginning, in fact. The way that dims, vars, and dimscales interact is complex, and renaming can make vars into dimscales, than turn them back to non-dimscales, then back to dimscales again. Each time, dimscales have to be correctly detached and reattached between each dim, and each var that uses that dim.
Renames can be devilishly tricky little blighters!
I did a rename fix that got into 4.6.0, but there were still known rename errors. I was prepared for a major effort to fix the remaining rename issues. I was ready to refactor the whole shebang.
But that turned out not to be necessary. I added one line of code and now all my rename tests work.
I don't promise this is the end of rename bugs. ;-)
Part of #597.
> another rename fix

- CMakeLists.txt
- RELEASE_NOTES.md
This is PR #853 submitted by @pedro-vicente plus an update to the RELEASE_NOTES file.
> HDF5 ZLIB detection and CRT configuration

- CMakeLists.txt
these are the changes explained in
#848 
https://github.com/Unidata/netcdf-c/issues/848
> changes to detect HDF5 HL, build with CRT and detect ZLIB in HDF5

- nc_test/tst_names.c
Got the followings from nc_test/tst_names.log. This PR fixes the error reporting if expected error codes are not NC_EBADNAME and is considered fatal.
```
::::::::::::::
nc_test/tst_names.log
::::::::::::::
*** testing names with file tst_names.nc...
*** switching to netCDF classic format...Error at line 282 (loop=131): No error
Error at line 282 (loop=132): No error
ok.
*** switching to netCDF 64-bit offset format...Error at line 282 (loop=131): No error
Error at line 282 (loop=132): No error
ok.
*** switching to netCDF 64-bit data format...Error at line 282 (loop=131): No error
Error at line 282 (loop=132): No error
ok.
*** Tests successful!
PASS tst_names (exit status: 0)
```
> fix error reporting

- include/onstack.h
If it isn't available, it isn't defined at all.
> onstack: check whether HAVE_ALLOCA_H is defined or not

- configure.ac
Fixes #911.
Fixes some missing spaces that are needed for --disable-shared to work.
> fixed spaces

- acinclude.m4
- configure.ac
- hdf4_test/Makefile.am
- nc_test/Makefile.am
- nc_test4/Makefile.am
- nctest/Makefile.am
Fixes #873.
This PR introduces a new way to do valgrind.
A macro has been added to acinclude.m4 from the autoconf community, which looks for valgrind on build machines. If present, extra valgrind targets are added. So unlike the old method, this does not change what make check does.
Make check will do the same as it does without valgrind. To use valgrind, make some of the new targets. For example:
`make check-valgrind-memcheck 
`
Will run the memory checking in each directory where testing is enabled.
I have enabled valgrind testing for nctest, nc_test, nc_test4, and hdf4_test.
In order to add the valgrind test targets to a directory, simply add the following to the Makefile.am:
```
@VALGRIND_CHECK_RULES@
```
> new method of using valgrind

- libsrc/nc3internal.c
- nc_test/CMakeLists.txt
- nc_test/Makefile.am
- nc_test/tst_err_enddef.c
When encountering an error in NC_begins, ncp->begin_var may have already been set.
This PR suggests to reset it to 0 before returning the error code.
A test program is added, tst_err_enddef.c.
Line 40 expects error code NC_EVARSIZE.
40    err = nc__enddef(ncid, 2147483648LL, 1, 1, 1);
The following call to nc_close() in line 46 will again return the same error code.
This because the failure in line 40 leaves the dataset in define mode and nc_enddef will be called inside nc_clode()
46    err = nc_close(ncid); CHECK_ERR
> reset ncp->begin_var if errors occur when calling NC_begins()

- libsrc4/nc4file.c
In hdf5-1.10.2, THG added a new enumeration for use in the `H5Pset_libver_bounds` function which makes it easier to maintain compatibility with hdf5-1.8.X clients.   
An explanation is provided at https://www.hdfgroup.org/2018/04/why-should-i-care-about-the-hdf5-1-10-2-release/ 
In particular, the section "What does this change mean to an HDF5 application?" discusses its use with NetCDF
> Use hdf5-1.8 compatible output format if possible

- nc_test4/tst_utf8.c
The ERR macro was  missing from a couple tests.
> Add missing ERR Macro

- docs/static-pages/software.html
- include/ncdimscale.h
- libsrc/nc3internal.c
- libsrc/ncx.m4
- libsrc4/nc4file.c
- libsrc4/nc4hdf.c
Getting caught up on PR's, consolidating several into a single PR to avoid cascading CI checks.
* https://github.com/Unidata/netcdf-c/pull/954
* https://github.com/Unidata/netcdf-c/pull/953
* https://github.com/Unidata/netcdf-c/pull/850
* https://github.com/Unidata/netcdf-c/pull/957
> Consolidating Several PR's

- libsrc4/nc4hdf.c
Fix unused variable warning for `printid`.   Looks like it was not substituted in all places where it should have been and was only used inside an ifdef so was unused if `LOGGING` was false.  Add use in `fprintf` line following the ifdef block.
Minor change, but compilation output is so clean that a little wart sticks out...
> Fix unused variable compiler warning

- include/nc4internal.h
- libhdf4/hdf4var.c
- libhdf5/hdf5attr.c
- libhdf5/nc4hdf.c
- libsrc4/nc4attr.c
- libsrc4/nc4var.c
- nc_test4/tst_vars2.c
Fixes #997.
Fixes #577.
The new way of handling long vs. int is much simpler. There was a lot of code associated with the old way of handling long vs. int which this PR removes.
Also:
Change test to stop printing errors, and to correctly allow late setting of fill for classic/64-bit offset files.
> removed dead code associated with old handling of NC_LONG, fixed test checking NC_ELATEFILL

- .travis.yml
- CMakeLists.txt
- configure.ac
Reverts Unidata/netcdf-c#1033 due to failures observed after the merge.  We can fix these and re-apply this merge.
Failure details can be seen here:
* http://cdash.unidata.ucar.edu/viewTest.php?onlyfailed&buildid=3790
> Revert "fix cdf5 configure option"

- docs/all-error-codes.md
- include/netcdf.h
- libdispatch/derror.c
- libsrcp/ncpdispatch.c
- nc_test/util.c
In addition to introducing `NC_EPNETCDF`, this PR also updates comments in `libsrcp/ncpdispatch.c` to match PnetCDF implementation. It also changes some APIs to return `NC_EPNETCDF` when certain features are not available from the (earlier versions of) PnetCDF library used underneath.
> introduce error code NC_EPNETCDF for errors at PnetCDF level

- ncdump/nccopy.c
The `error` macro used to output the usage information already outputs `progname`, so the `progname` argument is not needed and results in double printing of the `progname` as shown below:
```
ceerws2703a:build(master)> ../bin/nccopy
../bin/nccopy: ../bin/nccopy [-k kind] [-[3|4|6|7]] [-d n] [-s] [-c chunkspec] [-u] [-w] [-[v|V] varlist] [-[g|G] grplist] [-m n] [-h n] [-e n] [-r] infile outfile
[-k kind] specify kind of netCDF format for output file, default same as input
kind strings: 'classic', '64-bit offset', 'cdf5',
'netCDF-4', 'netCDF-4 classic model'
```
> Eliminate double printing of nccopy program name in usage output

- ncdump/nccopy.1
Restore the lost documentation in nccopy.1 of
the new per-variable chunking specifications.
> Restore lost chunking documentation

- nc_test/CMakeLists.txt
- nc_test/Makefile.am
- nc_test/run_diskless2.sh
- nc_test/tst_diskless4.c
ret: https://github.com/Unidata/netcdf-c/issues/1162
The test nc_test/run_diskless2.sh fails
when LARGE_FILE_TESTS is enabled.
Since the goal of the test was to test out
diskless+persist on a reasonably large file,
I fixed by just limiting the file size to
1000000000L bytes.
> Fix test run_diskless2.sh with LARGE_FILE_TESTS

- RELEASE_NOTES.md
- configure.ac
- docs/install.md
- include/hdf5internal.h
- include/nc4internal.h
- libdispatch/drc.c
- libdispatch/nchashmap.c
- libhdf5/hdf5attr.c
- libhdf5/hdf5create.c
- libhdf5/hdf5dim.c
- libhdf5/hdf5file.c
- libhdf5/hdf5grp.c
- libhdf5/hdf5internal.c
- libhdf5/hdf5open.c
- libhdf5/hdf5var.c
- libhdf5/nc4hdf.c
- libhdf5/nc4info.c
- libsrc4/nc4internal.c
- ncdump/chunkspec.c
- ncdump/nccopy.1
- ncdump/tst_nccopy5.sh
Migrate changes back upstream into `master`.
> V4.6.2 release branch.wif

- include/hdf5internal.h
- include/nc4internal.h
- libhdf5/hdf5attr.c
- libhdf5/hdf5file.c
- libhdf5/hdf5internal.c
- libhdf5/hdf5open.c
- libsrc4/nc4internal.c
Part of #856.
Starting to move hid_t elements from nc4internal.h to hdf5internal.h. In this PR I do the attributes.
No effect on library operation, just moving these pointers to libhdf5 so that they are not in libsrc4.
> Next step in HDF5 separation - moving att HDF5 info to libhdf5

- include/hdf5internal.h
- include/nc4internal.h
- libhdf5/hdf5attr.c
- libhdf5/hdf5dim.c
- libhdf5/hdf5file.c
- libhdf5/hdf5internal.c
- libhdf5/hdf5open.c
- libhdf5/hdf5var.c
- libhdf5/nc4hdf.c
- libsrc4/nc4internal.c
Part of #856.
Next step in this separation. Moving some HDF5 types from nc4internal.h to hdf5internal.h.
This is in the queue behind #1182.
> Next step in libhdf5/libsrc4 separation - moving hdf5-specific dim info to libhdf5

- configure.ac
Fixes #1152,
Now if curl is not present, configure script errors out instead of turning off dap.
> fixed curl configure issue

- ncdump/chunkspec.c
- ncdump/nccopy.1
- ncdump/tst_nccopy5.sh
re: https://github.com/Unidata/netcdf-c/issues/1183
* Fixes #1183 
Changes:
1. fix typo in nccopy.1 man page
2. fix chunkspec parsing for -c so that "-c var:"
(with no chunkspec arguments) disables chunking
on the specified variable
3. Add test case to ncdump/tst_nccopy5.sh
> Fix failure in the nccopy -c option

- nc_test4/tst_files6.c
- nc_test4/tst_rename.c
Fixes #1181.
Fixed up some test output.
> Fixing text output in nc_test4/tst_files6.c and tst_rename.c

- CMakeLists.txt
If not building shared libraries, then the RPATH handling should not be specified.  Although ignored on some compilers, the CRAY / Intel compiler will error out when installing the NetCDF executables if the RPATH settings are enabled.
Not sure if this is the best fix, but it does work on our internal CRAY systems.
> RPATH handling is not needed for archive library

- nc_test4/tst_udf.c
Removes extra argument to match function prototype in `NC_Dispatch` as described in #1196
> Remove extra argument

- libhdf5/nc4info.c
- ncdump/dumplib.c
- ncdump/ncdump.c
- ncgen/data.c
Fixed a few compiler warnings.  One of these is actually a code error where the statement following the `if` is always executed due to the semicolon at the end of the if statement:
``` 
if(prov->propattr.properties != NULL);
nclistfreeall(prov->propattr.properties);
```
> Eliminate compiler warnings (and code error)

- ncdump/Makefile.am
- ncdump/tst_netcdf4_4.sh
> change rm in test script to use specific file names so parallel builds continue to work

- libsrc/memio.c
- nc_test/tst_inmemory.c
- plugins/H5Zbzip2.c
re: pull request https://github.com/Unidata/netcdf-c/pull/1219
This pr should go in after or at the same time as 1219.
It updates nc_test/tst_inmemory to add a test to cover
the case fixed in 1219. It also disables a couple of tests
that no longer are relevant.
> Update nc_test/tst_inmemory to cover more cases

- include/ncdispatch.h
- ncgen/genbin.c
We need to do this periodically because they sneek in.
> Remove // style comments from source code.

- include/hdf5internal.h
- include/nc4internal.h
- libhdf5/nc4info.c
- liblib/nc_initialize.c
* Fixes #1207 
re: issue https://github.com/Unidata/netcdf-c/issues/1207
The NC4_get_provenance is generating a spurious error message.
This properly suppresses it.
> Fix error report coming out of nc4info.c

- debug/README.txt
- debug/cf.cmake
- include/nc_provenance.h
- nc_test/run_inmemory.sh
- nc_test/tst_inmemory.c
- nc_test/tst_open_mem.c
- ncgen/bindata.c
- ncgen/ncgenl.c
* Fixes #1233 
re: issue https://github.com/Unidata/netcdf-c/issues/1233
Changes:
1. remove exit that was there for testing.
2. the program tst_open_mem must be netcdf-4 only.
3. fix some diff problems
- Change dataset name for tst_inmemory4_create to tst_inmemory4
- Modify tst_inmemory.c to reorder the variables (somewhat major rewrite)
Minor Unrelated Fixes:
1. fix comment problem in nc_provenance.h
2. Fix memory leak in tst_open_mem.c
3. fix ncdump/bindata.c to properly compile if netcdf4 is disabled.
4. minor changes to ncgen.l
> Fix failings of nc_test/run_inmemory.sh

- hdf4_test/tst_interops3.c
- libdap2/ncd2dispatch.h
- libdap4/d4meta.c
- libdap4/ncd4dispatch.c
- libdispatch/utf8proc.c
- libdispatch/utf8proc.h
- libsrc/attr.m4
- nc_test/tst_formats.c
- nc_test/tst_inq_type.c
- nc_test/util.c
- nc_test4/tst_empty_vlen_unlim.c
- ncdump/nccopy.c
- ncdump/ncdump.c
- ncgen/main.c
re: pull request https://github.com/Unidata/netcdf-c/pull/1242
This pr should be applied before pr https://github.com/Unidata/netcdf-c/pull/1242.
It fixes only the -ansi '//' comment problems. There may be some
slight conflicts with that other pr when it is applied, since in some
cases I converted #if 0...#endif to /* ... */
> Separate out the -ansi comment fixes.

- libhdf5/hdf5type.c
If `equalp` is NULL, then the function returns early, so all subsequent tests on `equalp` are not needed.
> Tests on equalp are always true

- CMakeLists.txt
Since 209c31d3 (Bringing config.h as generagted by cmake in line with config.h as generated by autotools., 2017-01-27)
we check that we can find the hdf5.h main include file.
But this file may reside in non-standard location so we have to search
in HDF5_INCLUDE_DIR as well.
> CMakeLists.txt: Fix compilation with default settings on debian stretch

- docs/filters.md
- include/Makefile.am
- include/netcdf_filter.h
- libdap4/d4data.c
- libdap4/d4debug.h
- libdap4/d4swap.c
- libdispatch/dfilter.c
- nc_test4/test_filter_misc.c
- nc_test4/tst_filterparser.c
- ncdump/nccopy.c
- ncdump/ncdump.c
- ncgen/ncgen.y
- ncgen/ncgenl.c
- ncgen/ncgeny.c
- oc2/occompile.c
- oc2/ocinternal.c
- plugins/H5Zmisc.c
- plugins/H5Zutil.c
- plugins/Makefile.am
* Fixes https://github.com/Unidata/netcdf-c/issues/1278
* Fixes https://github.com/Unidata/netcdf-c/issues/876
* Fixes https://github.com/Unidata/netcdf-c/issues/806
* Major change to the handling of 8-byte parameters for nc_def_var_filter.
The old code was not well thought out.
* The new algorithm is documented in docs/filters.md.
* Added new utility file plugins/H5Zutil.c to support
* Modified plugins/H5Zmisc.c to use new algorithm
the new algorithm.
* Renamed include/ncfilter.h to include/netcdf_filter.h
and made it an installed header so clients can access the
new algorithm utility.
* Fixed nc_test4/tst_filterparser.c and nc_test4/test_filter_misc.c
to use the new algorithm
* libdap4/ fixes:
* d4swap.c has an error in the endian pre-processing such
that record counts were not being …
> Fix errors when building on big-endian machine

- libdap2/ncd2dispatch.c
- oc2/ochttp.c
re: issue https://github.com/Unidata/netcdf-c/issues/1316
The DAP2 data model does not have a signed byte type,
but netcdf-3 does have (only) a signed byte type.
So, when converting a netcdf-3 signed byte typed variable to
a DAP2 unsigned byte, the following actions are taken by thredds:
1. The variable type is marked as DAP2 (unsigned) byte.
2. A special attribute, "_Unsigned=false" is set for the variable
3. The corresponding "_FillValue" attribute, if any, is up-converted
to the DAP2 Int16 type in order to hold, with sign, any signed byte
fill value.
On the netcdf-c side, this looks like a fillvalue type mismatch and causes
an error. Instead, the netcdf-c dap2 conversion code needs to recognize
this hack and undo it locally.
So this change looks for the above case, and if found, then …
> Add hack to deal with DAP2 signed byte conversion.

- libdispatch/dauth.c
re: esupport (DVK-211460)
Turns out it was a typo in libdispatch/dauth.c
Fix is to Change:
HTTP.USERNAME -> HTTP.CREDENTIALS.USERNAME
and
HTTP.PASSWORD-> HTTP.CREDENTIALS.PASSWORD
> URL with username+pwd in url is not working.

- CMakeLists.txt
- config.h.cmake.in
- configure.ac
- libdap2/daputil.c
- libdap4/d4varx.c
re: https://github.com/Unidata/thredds/issues/1224
[note that this is an issue in thredds, but the fix is in netcdf-c]
A thredds server can encode a netcdf-4 file into DAP2
by flattening names to include the containing group path,
where the group names are separated by '/'.
But the '/' is prohibited in netcdf names even if escaped
(a decision before my time).
So, if the netcdf-c/libdap2 code encounters a DAP2 name with '/'
characters, the '/' characters are converted to the string
%2f. Unfortunately, there is a glitch, namely that converting
the leading '/' produces a name that is still illegal. This PR
modifies the code to just drop the leading '/' character.
> Fix handling of '/' characters in names in DAP2.

- h5_test/CMakeLists.txt
- h5_test/Makefile.am
- h5_test/tst_h_rename.c
- libhdf5/hdf5dim.c
- libhdf5/hdf5grp.c
- libhdf5/hdf5var.c
- libhdf5/nc4hdf.c
- nc_test4/CMakeLists.txt
- nc_test4/Makefile.am
- nc_test4/tst_rename2.c
- nc_test4/tst_rename3.c
Part of #597.
Fixes #1307.
In this PR I fix the problem of vars changing order after a rename. After a var is renamed, it should have the same varid the next time the file is opened.
This includes all my outstanding PRs.
Part of #597.
Fixes #1305.
Fixes #1304.
This PR is ready to merge and should be merged soon so that rename work can continue.
> Fix bug which changed varids after var rename

- nc_test4/ref_filteredvv.cdl
- nc_test4/tst_filter.sh
- nc_test4/tst_filterparser.c
- plugins/H5Zutil.c
re: issue https://github.com/Unidata/netcdf-c/issues/1338
Changes:
1. nc_test4/tst_filter.sh + nc_test4/ref_filteredvv.cdl --
properly suppress _Endianness attribute
2. fix some warnings
> Fix nc_test4/tst_filter.sh for big endian

- ncdump/CMakeLists.txt
- ncdump/Makefile.am
- ncdump/ref_tst_radix.cdl
- ncdump/test_radix.sh
- ncdump/tst_radix.cdl
- ncgen/ncgen.l
- ncgen/ncgenl.c
* fixes #1330 
re: https://github.com/Unidata/netcdf-c/issues/1330
The ncgen utility is documented to accept octal integer constants
if the leading digit is zero. This was not implemented. Fix ncgen.l
to properly handle such constants. Also add a test to c0.cdl.
> Fix ncgen handling of octal constants (with leading 0).

- nc_test4/tst_filterparser.c
re: https://github.com/Unidata/netcdf-c/pull/1337
tst_filterparser was creating but not using the baseline
array. Instead, it did the same thing inline. Fixed code
to use baseline array.
> Modify tst_filterparser to use baseline array

- ncdump/utils.h
Part of #1323.
Provide NDEBUG version of macro NC_CHECK which does not use code file name.
> provide NDEBUG version of macro NC_CHECK which does not use code file name

- docs/inmemory.md
- ncdump/CMakeLists.txt
- ncdump/Makefile.am
- ncdump/nccopy.c
- ncdump/ref_nccopy_w.cdl
- ncdump/tst_nccopy_w3.sh
- ncdump/tst_nccopy_w4.sh
* Fixes https://github.com/Unidata/netcdf-c/issues/1365
At some point (4.6.1) we changed the diskless handling of flags
and added a new NC_PERSIST flag. Looks like we did not fix all
occurrences of the old flag set, specifically for 'nccopy -w' command.
Also added some tests (tst_nccopy_w{3,4}.sh) for this situation.
> Fix nccopy to use NC_PERSIST so that -w actually persists the output.

- include/netcdf.h
- libdispatch/dfile.c
- libdispatch/dparallel.c
As NC_MPIIO has deprecated, move checking for flag conflict of parallel and diskless|inmemory|mmap to nc_create_par.
> move checking for flag conflict to nc_create_par

- examples/C/run_filter.sh
- nc_test4/tst_filter.sh
- ncdump/Makefile.am
- plugins/CMakeLists.txt
- plugins/Makefile.am
re: https://github.com/Unidata/netcdf-c/issues/1347
It turns out that the plugin libraries (bzip2 and misc) were
being installed as part of 'make install'. This was not intended
behavior. But after some discussion in the above issue, it was decided
to install the bzip2 plugin. However, in order to avoid naming conflicts,
the plugin is installed under the name 'libh5bzip2.so'.
Note that this is automake behavior only; the install does not
(yet) occur using cmake.
Misc. unrelated changes
-----------------------
1. turn off some debug output in ncdump/Makefile.am
> Support installation of the bzip2 plugin under name libh5bzip2.so

- nc-config.cmake.in
- nc-config.in
> Bring behavior of nc-config in line with pkgconfig --libs --static netcdf

- libdap2/ncd2dispatch.c
- libdap4/ncd4dispatch.c
- libdispatch/ddispatch.c
- libhdf5/hdf5dispatch.c
- libsrc/mmapio.c
- oc2/ocinternal.c
re: https://github.com/Unidata/netcdf-c/issues/1388
1. Centralize calls to curl_global_init and curl_global_cleanup
to libdispatch/ddispatch.c
2. Make the above calls if options require curl: currently
any of DAP2, DAP4, or byterange.
3. Side issue: Fix obscure bug in mmapio.c involving non-persistent mmap.
> Centralize calls to curl_global_init and curl_global_cleanup

- configure.ac
- libsrc/mmapio.c
* Fixes https://github.com/Unidata/netcdf-c/issues/1390
Change configure.ac to properly test for
combination of no-curl and disable-byterange.
> Option --disable-byterange fails if libcurl is not found

- configure.ac
Observed an issue on systems using `libsz` as provided by the `libaec` package instead of being built from scratch.  Discovered after a CI bug report by @edhartnett, and was able to recreate.  The libaec-provided libsz does not contain the symbol `SZ_Compress`, and so the netcdf-c `configure` script returned a false negative.  
Fix was to modify `libsz` detection to mirror how `libhdf5` is detecting it.
> Modified how libsz is being detected in automake-based builds.

- configure.ac
- debug/cf.cmake
- include/ncconfigure.h
- libdispatch/nctime.c
re: https://github.com/Unidata/netcdf-c/issues/1408
1. Add some function tests to configure.ac; these are functions
not defined with -ansi.
2. When using -ansi, fix include/ncconfigure.h to check for
the possibilty that certain functions are being defined
by macros. Apparently Debian does this for some reason.
No idea why.
Unrelated: modify the debug/cf.cmake debug shell script.
> Fix ncconfigure.h to solve a -ansi problem with strdup()

- include/nc.h
- libdispatch/dfile.c
- libdispatch/nclistmgr.c
Fixes #1427.
As discussed with Dennis, I've removed this unused macro, which is an artifact of programming efforts of the past.
>  remove unused macro USE_REFCOUNT

- include/Makefile.am
- include/ncdispatch.h
- include/netcdf_dispatch.h
- libdispatch/dfile.c
- nc_test4/tst_udf.c
Part of #1426 
Fixes #1434 
I have put the minimum (just the dispatch table itself) into netcdf_dispatch.h.
I may have to move more as I continue with the PIO work and see what is needed.
This PR will have no effect on any user code. It begins the separation of public dispatch declarations and macros from internal declarations and macros.
> create header netcdf_dispatch.h

- libdispatch/ncuri.c
- oc2/ocinternal.c
* Fixes #1425
The 'ncdump -v' command causes a constraint to be sent
to the opendap code (in libdap2). This is a separate path
from specifying the constraint via a URL.
This separate path encoded its constraint using code independent
of and duplicative of that provided by ncuri.c and this duplicate
code did not properly encode the constraint, which might include
square brackets.
Solution chosen here was to get rid of the duplicate code and
ensure that all URL escaping is performed in the ncuribuild function
in the ncuri.c file.
Also removed the use of the NEWESCAPE conditional in ncuri.c
because it is no longer needed.
> Fix encoding of a DAP2 constraint specified outside the URL.

- RELEASE_NOTES.md
- ncdump/nccopy.1
- ncdump/nccopy.c
* Fixes https://github.com/Unidata/netcdf-c/issues/1436
It used to be that when no -c parameters were specified
(and the input was some variant of netcdf-3) that nccopy
let the netcdf-c library decide on any default chunking.
Now, it attempts to do it itself and is not doing it
correctly when unlimited dimensions are involved.
So fix is to revert to previous behavior.
Note: The chunking rules are getting too complicated; consider revising.
> nccopy must use defaulting when there are no -c parameters

- include/nc4internal.h
- libhdf4/hdf4file.c
- libhdf5/hdf5file.c
- libsrc4/nc4internal.c
Fixes #1433 
Part of #1426 
The current code to close a file needs a little cleanup for PIO use of the UDF feature.
In this PR I add function nc4_nc4f_list_del() to go with nc4_nc4f_list_add(). This new function cleans up the memory that was allocated by libsrc4 code. This allows some duplicate code to be removed from hdf4file.c and hdf5file.c, as well as making it easier for layers like PIO to use the libsrc4 metadata handling code.
This change is required for the netCDF/PIO integration. See https://github.com/NCAR/ParallelIO/pull/1566.
> clean up freeing of libsrc4 metadata memory in HDF5 and HDF4

- include/netcdf_dispatch.h
- libdap2/ncd2dispatch.c
- libdap2/ncd2dispatch.h
- libdap4/ncd4dispatch.c
- libdispatch/CMakeLists.txt
- libdispatch/Makefile.am
- libdispatch/dcopy.c
- libdispatch/dfile.c
- libdispatch/dvar.c
- libdispatch/dvarget.c
- libdispatch/dvarput.c
- libhdf5/hdf5dispatch.c
- libsrc/nc3dispatch.c
- libsrcp/ncpdispatch.c
- ncdump/nctrunc.c
- ncdump/ncvalidator.c
Partially address: https://github.com/Unidata/netcdf-c/issues/1056
Currently, some of the entries in the dispatch table
are conditional'd on USE_NETCDF4.
As a step in upgrading the dispatch table for use
with user-defined tables, we remove that conditional.
This means that all dispatch tables must implement the
netcdf-4 specific functions even if only to make them
return NC_ENOTNC4. To simplify this, a set of default
functions are defined in libdispatch/dnotnc4.c to provide this
behavior. The file libdispatch/dnotnc3.c is also relevant to
this.
The primary fix is to modify the various dispatch tables to
remove the conditional and use the functions in
libdispatch/dnotnc4.c as appropriate. In practice, all of the
existing tables are prepared to handle this, so the only
real change is to …
> Remove netcdf-4 conditional on the dispatch table.

- libhdf5/hdf5var.c
- nc_test4/CMakeLists.txt
- nc_test4/Makefile.am
- nc_test4/tst_bug1442.c
This fixes an issue hit by GDAL, and that is found in netcdf 4.6.3
and 4.7.0
git bisect pointed the problem to have started with
```
77ab979c5fd7151f8583c7698498bb8cb0dafb63 is the first bad commit
commit 77ab979c5fd7151f8583c7698498bb8cb0dafb63
Author: Ed Hartnett <edwardjameshartnett@gmail.com>
Date:   Sat Jun 16 09:58:48 2018 -0600
using get_vars but not put_vars
:040000 040000 8611e77aaea4f130ca769a852e2c3b26373a78fa fc9ffd1d13d8f5db5ab888044e0cec4def26eba1 M	libsrc4
```
where nc_get_vara_double() started using nc4_get_vars() underneath.
It turns out that nc4_get_vars() was buggy in the situation exercised by GDAL.
This can be reproduced with the following simple test case:
```
int main()
{
int status;
int cdfid = -1;
int first_dim;
int varid;
int other_var;
size_t …
```
> NC4_get_vars(): fix out-of-bounds write with unlimited dimension

- ncdump/nccopy.c
`option_min_chunk_bytes` is `size_t` which is unsigned so value can never be less than zero.
> Eliminate compiler warning

- ncdump/ncdump.c
- ncdump/ocprint.c
With MinGW, _WIN32 is defined and HAVE_GETOPT_H is also defined.
To avoid double inclusion of the function getopt(), the _WIN32 is replace with _MSC_VER, and it is unified the principe fir all XGetopt.h inclusion.
> Fix XGetopt.h inclusion for Windows/MinGW

- libhdf5/hdf5create.c
- libhdf5/hdf5open.c
Part of #1426 
In this PR I remove the setting of int_ncid by libhdf5 code. This turns out to be unnecessary.
This is useful both to reduce code clutter and confusion, and also because this was the only use of the NC structure in the HDF5 code.
> removed unneeded setting of int_ncid by libhdf5 layer

- libsrc4/nc4var.c
Fixes #1412 
This only fixes it for the NetCDF4 API. A similar fix is needed for the v3 API, but I couldn't see how to regenerate `ncx.c` from `ncx.m4` (and I'm not 100% sure of the needed change there).
The other conversion cases could also use these non-signalling macros, but then the conversion itself will signal. I don't know what the expected behaviour is from the library when writing a NaN to an integral type, so I didn't change the other comparisons -- it's a simple regex though, so I can do so if wished.
As an aside, this function generates a _lot_ of conversion warnings. Explicit casts would silence them -- would you like those adding (perhaps in a separate PR)?
> Use quiet comparison when converting from double to float

- docs/install.md
`./configure --with-zlib=${ZDIR} --prefix=${H5DIR} --eanble-hl` on line 135
command errors, but runs if changed to `enable-hl`
> An example argument typo

- CMakeLists.txt
Fixes #1372
Remove mention of run_par_tests2.sh from CMakeList.txt. It is no longer used.
This is just PR #1454 again, with up-to-date master, trying to pass the DAP tests in Travis.
> removed commented lines refering to run_par_test2.sh, which does not exist

- Makefile.am
- RELEASE_NOTES.md
- configure.ac
- docs/netcdf.m4
- include/nc3internal.h
- include/netcdf.h
- libdispatch/nc.c
- libdispatch/nclistmgr.c
- libsrc/nc3internal.c
- libsrc/putget.m4
- ncgen/main.c
- ncgen3/main.c
- unit_test/Makefile.am
- unit_test/tst_nclist.c
Fixes #1459.
The obsolete macros _CRAYMPP and LOCKNUMREC were in use on an ancient version of a Cray. They would no longer work on modern Crays, which use MPI and the nc_open_par/nc_create_par functions for parallel I/O.
This will have no effect on existing users, since no could build with these macros - they are not supported in the configure.ac file.
This PR contains PR #1463, and should be inspected after that one is merged.
> Remove obsolete _CRAYMPP and LOCKNUMREC macros

- CMakeLists.txt
- RELEASE_NOTES.md
- include/nc4internal.h
- libdispatch/nc.c
- libsrc4/nc4internal.c
- nc_test4/CMakeLists.txt
- unit_test/CMakeLists.txt
- unit_test/Makefile.am
- unit_test/tst_nc4internal.c
- unit_test/tst_nclist.c
https://github.com/Unidata/netcdf-c/pull/1472 but with cmake support (except for Visual Studio)
> Unit tests plus cmake infrastructure

- Makefile.am
- RELEASE_NOTES.md
- configure.ac
- docs/netcdf.m4
- include/nc3internal.h
- include/nc4internal.h
- include/netcdf.h
- libdispatch/nc.c
- libdispatch/nclistmgr.c
- libsrc/nc3internal.c
- libsrc/putget.m4
- libsrc4/nc4internal.c
- ncgen/main.c
- ncgen3/main.c
- unit_test/Makefile.am
- unit_test/tst_nc4internal.c
- unit_test/tst_nclist.c
Part of #1458.
Part of #1457 
Adding more unit tests, this time for the code in nc4internal.c. (These unit tests run for netcdf-4 builds.)
More coming. 
This includes PR #1463 and #1464.
> more unit tests

- CMakeLists.txt
- include/netcdf_par.h
This PR enables building netCDF with parallel I/O support under MSVC. This only requires minor changes as HDF5-1.10.5 supports Microsoft MPI by default with `HDF5_ENABLE_PARALLEL`. All tests are passing on my end except **tst_parallel5** - I'll look into it.
The change to `FIND_PACKAGE(HDF5)` is minor to correct a typo, `NO_MODULES` should be `NO_MODULE|CONFIG` (synonyms). While this fixes HDF5 linkage on my system (I'm using the [CMake Package](https://www.hdfgroup.org/downloads/hdf5/source-code/) from HDF Group), I think more extensive changes may be needed to make this more generic. You might consider integrating the changes in vcpkg, see for example microsoft/vcpkg#6771.
This should also fix the incomplete library exports discussed in #554 and …
> Support parallel functions in MSVC

- libdispatch/drc.c
The comment states that prefix must end in '/', but the '/' is added in the function itself, so the prefix should *not* end in '/' and the comment is incorrect.
> Remove incorrect comment

- libdispatch/drc.c
- libdispatch/ncuri.c
- libsrc4/nc4internal.c
- ncdump/ncvalidator.c
- ncgen/genbin.c
Cleaning up assorted issues identified via static analysis.
> Assorted Static Analysis cleanup

- include/nc4internal.h
- include/nc_tests.h
- include/netcdf_par.h
- libdap2/dapdump.c
> Added EXTERNL definition in netcdf_par.h

- nc_test4/tst_interops6.c
Fixes #1524 
There were duplicate tests, both commented out. I've eliminated one of them, and fixed and uncommented the other.
The problems were all in the test code, it's a bit tricky to handle strings, and we must get the pointers correct. Now they are fixed, and the test runs fine.
> cleaned up test handling of strings

- RELEASE_NOTES.md
- docs/tutorial.dox
- libdispatch/dinfermodel.c
- libhdf5/hdf5open.c
- nc_test4/CMakeLists.txt
- nc_test4/Makefile.am
- nc_test4/tst_interops_dims.c
- nc_test4/tst_udf.c
Fixes #1484 
When reading a HDF5 file (i.e. not a netCDF-4/HDF5 file), the library has to make assumptions about dimensions.
Until now, each dataspace length got it's own phony dimension, unless it was the same length as a previously assigned anon dimension.
That meant a HDF5 file with a 2-D dataspace of 100x100 would look like this:
```
netcdf dset {
dimensions:
phony_dim_0 = 100 ;
variables:
int dset(phony_dim_0, phony_dim_0) ;
}
```
This is probably not what the data writer intended. The two dimensions of the dataset should be two different dimensions, even though they are (coincidentally) the same size.
Now, if an anon dimension of the same size is found, it is also checked to see if it was already used in this dataset. If so, we now assume that it is a new dimension.
So now a HDF5 …
> If HDF5 dataset has multiple anonymous dimensions of the same size, assume they are different dimensions

- libhdf5/nc4hdf.c
- nc_test4/tst_atts.c
1) We have to use `H5Tequal()` to compare HDF5 type IDs.
2) When checking if we can re-use an `NC_CHAR` attribute it is enough to compare data types (`H5Tequal()` takes care of the size comparison).
3) This PR adds missing code (`reuse_att` was set but not used).
Now an attribute in a NetCDF-4 file can be modified as many times as necessary, as long its type and length remain the same.
Modifications changing either type or length of an attribute require deleting and re-creating an attribute which increments the attribute order creation index. Once this index reaches 65535 all attribute modifications (for a particular group or variable) will fail.
> Improve the fix for #350 included in #1119

- libhdf5/hdf5var.c
- libhdf5/nc4hdf.c
- nc_test4/tst_dims3.c
Fixes #1496 
When looking up the coordinate var associated with a dimension, we were looking it up by name. Well, if there is a var of the same name, which is not a coordinate var, hilarious confusion ensues.
Now, instead of checking by name, we use the dim->coord_var pointer, which already correctly points to a coord var, or is NULL if there is no coord var.
I have added code derived from @jswhit to test.
> Fix for subtle error involving var and unlimited dim of the same name, but unrelated, in netCDF-4

- libhdf5/hdf5var.c
- nc_test4/tst_vars3.c
- nc_test4/tst_vars4.c
Fixes #1479
As is clearly stated in the documentation for nc_def_var_endian():
`Warning: this function is only defined if the type of the variable is an atomic integer or float type.`
But this was not actually being checked in the code. Setting the endianness for other types is not safe. If there is an interest in controlling endianess for user-defined types, we can pursue that as a separate and new feature. (But no one wants it anyway.)
In this PR I add checking to ensure that endianness is only set on atomic integer or float types. Tests are added to confirm.
> now testing that endianness can only be set on atomic ints and floats

- CMakeLists.txt
- configure.ac
- include/netcdf_meta.h.in
- libnetcdf.settings.in
Fixes #1469 
Adding a version number for the dispatch table, in case we decide to change it at some point.
> Add a dispatch version number to netcdf_meta.h and libnetcdf.settings, in case we decide to change dispatch table in future

- docs/Doxyfile.in
- libdispatch/datt.c
- libdispatch/dattget.c
- libdispatch/dattinq.c
- libdispatch/dattput.c
Fixes #1512 
Previously we had been trying to get by with one documentation block for all the different types of nc_get_att_<type>, and another for nc_put_att_<type>. But this was an imperfect solution.
Some problems:
* many functions do not get correct links throughout the documentation (though some of them are working).
* documentation had to be confusingly general.
* nearly-duplicate documentation blocks were needed to handle typeless and string type functions.
So, after this PR, each att fucntion gets its own doxygen documentation, which makes doxygen happy. I have edited the documentation to take repeated parts out and put them in the member group for "Reading Attributes" and "Writing Attributes" and have added achors to them so they can be referred to from each function definion, …
> update for attribute documentation

- libdispatch/dinfermodel.c
- nc_test4/tst_udf.c
Fixes #1522 
Also modified tst_udf.c to detect this problem. Also added comments to dinfermodel.c and tst_udf.c to describe what is going on.
@DennisHeimbigner this PR will be of interest to you.
@WardF we absolutely want this in before the next release.
> User-defined formats must come first in NC_infermodel, plus test

- docs/FAQ.md
The CMakeLists.txt actually uses `HDF5_C_LIBRARY` and `HDF5_HL_LIBRARY` to find non-standard HDF5 installation.  This just updates the FAQ with the correct usage.
This addresses issue #1533.
> Update FAQ based on actual usage of HDF5 variables

- CMakeLists.txt
CMake provides the means to track the transient dependencies of a library, like its include directories, by setting the appropriate property on the target(s).  This pull request does two things.  The first add the include directories to the `netcdf` library so that downstream usage only requires adding the link library. Specifically
add_executable(myprog ...)
target_link_libraries(myprog netcdf ...)
target_include_directories(myprog ${netCDF_INCLUDE_DIRS} ...)
becomes
add_executable(myprog ...)
target_link_libraries(myprog netcdf ...)
This helps CMake to correctly track the implicit dependencies and get linking orders correct.
The second change (second commit) is adding a namespace for the netCDF targets.  Namespaces are advised by most tutorials (I'm thinking [this one in …
> Provide Transient Properties on netCDF Library

- nc_perf/Makefile.am
Fixes #1534 
Some test scripts were not being included in EXTRA_DIST.
> fixed nc_perf Makefile.am to include benchmark scripts in EXTRA_DIST

- RELEASE_NOTES.md
> updated RELEASE_NOTES with recent PRs that have been merged

- libhdf5/hdf5open.c
- nc_test4/tst_interops5.c
Fixes #1558 
Fixes a memory problem that can occur on failed HDF5 file opens. The test fails address sanitizer with current master, but passes with fix.
Fix is just to move initialization of udata.grp to top of function, before any BAIL macros are called.
Thanks @brentd42 for finding this one.
> fix memory issue that may occur for some HDF5 file opens

- include/nc4internal.h
- include/netcdf.h
- libdispatch/dvar.c
- libhdf5/hdf5open.c
- libhdf5/hdf5var.c
- libhdf5/nc4hdf.c
- libsrc4/nc4var.c
- nc_test4/tst_vars4.c
Fixes #1568 
@gsjaardema thanks very much for the suggestion and prototype implementation.
This PR includes a test and a method of setting (and inquiring about) compact storage, with the existing API.
This PR is instead of #1535
> enable compact storage for netcdf-4 vars

- CMakeLists.txt
- unit_test/CMakeLists.txt
Fixes #1458 
Turning on rest of unit tests in CMake build, seeing if they work on Windows...
they do not. And to make them work we would need to EXTERNL every internal function we are testing in the unit_test directory. This is not something we want to do, so I suspect unit_test directory will never run on Windows, which I think is OK.
> Adding rest of unit_tests to CMake build, but not running them on Windows

- CMakeLists.txt
- RELEASE_NOTES.md
- configure.ac
- docs/Doxyfile.in
- docs/guide.dox
- libdispatch/dvar.c
- libhdf5/hdf5cache.c
- nc_perf/Makefile.am
- nc_perf/tst_bm_rando.c
Fixes #1541
Fixes #1559 
Fixes #1553 
This fix contains an increase in the chunk cache and number of slots settings, plus better documentation of cache settings and a new benchmarking program to help examine the effect of different cache settings.
> increase default cache size for netCDF-4/HDF5 files, also improve cache docs and add benchmarking program

- configure.ac
- libdap4/d4chunk.c
- libdap4/d4util.c
- libdap4/ncd4.h
- libdispatch/derror.c
- libdispatch/dhttp.c
- libhdf5/nc4info.c
- nc_test/tst_byterange.c
Some versions of some servers are returning malformed responses.
Make the library either handle them or gracefully fail.
The three server errors "fixed" here are as follows.
1. The attribute _NCProperties sometimes has a trailing nul character
in its value. Soln is to elide the nul(s).
2. Sometimes a DAP response has no data part, only a DMR.
Soln is to detect and return an error code instead of crashing.
3. Sometimes a server returns a redirection, but our current
openmagic() function was not following the redirect. Soln
is to follow redirects.
Also because of #2, I am temporarily making --disable-dap-remote-tests
be the default.
> Make the dap4 code resistant to various server errors.

- docs/DAP2.dox
- docs/DAP4.dox
- include/ncauth.h
- include/nctestserver.h
- libdap4/d4curlfunctions.c
- libdispatch/dauth.c
- oc2/occurlflags.c
- oc2/occurlfunctions.c
- oc2/ochttp.c
I see that there is no way to set CURLOPT_CONNECTTIMEOUT,
but there is support for CURLOPT_TIMEOUT.
So, accept the line 'HTTP.CONNECTTIMEOUT'
in .rc file to allow user to set CURLOPT_CONNECTTIMEOUT.
> Add support for CURLOPT_CONNECTTIMEOUT

- docs/guide.dox
Fixes #1596 
Minor documentation change to prevent inadvertent bullet-point in the docs.
> fixed doc formatting issue

- CMakeLists.txt
- configure.ac
Fixes #1557 
We require that HDF5 be built with zlib, but we never checked that. This results in some problems when HDF5 was built without zlib (like #1562 for example).
In this PR I add checks to ensure that HDF5 was built with zlib. If not, then both the autotools and cmake build will error out, and tell the user that they need to rebuild HDF5 with zlib.
> detect if HDF5 was built without zlib, and error out of configure/cmake

- RELEASE_NOTES.md
- include/hdf4dispatch.h
- include/netcdf.h
> raised NC_MAX_HDF4_NAME length to NC_MAX_NAME

- h5_test/tst_h_vars.c
- libhdf5/hdf5filter.c
- libhdf5/hdf5var.c
- libsrc4/nc4var.c
- nc_test4/tst_vars2.c
- ncdump/cdl/ref_tst_special_atts3.cdl
- ncdump/chunkspec.c
- ncdump/chunkspec.h
- ncdump/nccopy.1
- ncdump/nccopy.c
- ncdump/ncdump.1
- ncdump/ncdump.c
- ncdump/ref_ctest_special_atts_4.c
- ncdump/ref_tst_special_atts.cdl
- ncdump/tst_nccopy5.sh
- ncdump/tst_special_atts.c
- ncgen/genbin.c
- ncgen/genc.c
- ncgen/ncgen.1
- ncgen/ncgen.y
- ncgen/ncgeny.c
* fixes https://github.com/Unidata/netcdf-c/issues/1642
Modify ncdump, nccopy, and ncgen to support the NC_COMPACT storage option.
Added test cases and added description to the man pages for the utilities.
1. ncdump: For compact storage variable, print special attribute __Storage_ as
````
<var>: _Storage = "compact";
````
2. ncgen: parse and implement
````
<var>: _Storage = "compact";
````
in a .cdl file
3. nccopy: Extend the chunk specification (-c flag) to support
compact using the forms
````
nccopy ... -c <var>:compact
and
nccopy ... -c <var>:contiguous
````
Misc. other changes
1. cleanup the copy_chunking function in ncdump/nccopy.c
> Make utilities support NC_COMPACT

- nc_test4/tst_parallel5.c
A few of the tests were missing a call to the ERR macro.
> Add missing ERR macro on tests

- include/nc4internal.h
- nc_test4/tst_mode.c
Fixes #1658 
Also added some missing documentation to nc4internal.h NC_VAR_INFO_T. I'm about to make some edits on this code for #1648.
> Fix parallel build error in tst_mode.c caused by returning errors for attempts to set filters on scalar vars

- RELEASE_NOTES.md
- libdispatch/dfilter.c
- libdispatch/dvar.c
- libhdf5/hdf5var.c
- nc_test4/tst_vars2.c
Fixes #1644 
Also updated documentation to note that nc_def_var_deflate, nc_def_var_filter cannot be used on scalar vars.
> Return error on attempt to set chunking on scalar var

- h5_test/tst_h_vars2.c
- include/nc4internal.h
- libhdf4/hdf4file.c
- libhdf5/hdf5filter.c
- libhdf5/hdf5open.c
- libhdf5/hdf5var.c
- libhdf5/nc4hdf.c
- libsrc4/nc4internal.c
- libsrc4/nc4var.c
Fixes #1649 
This PR changes from using two fields (contiguous and compact) to hold storage info in NC_VAR_INFO_T, and instead uses one new field (storage) to hold the storage info.
> refactor storage in NC_VAR_INFO_T

- libdispatch/dfile.c
* Fixes https://github.com/Unidata/netcdf-c/issues/1666
The code in NC_open and NC_create (in dfile.c)
was using improper testing for leading whitespace chars.
It was treating UTF-8 as whitespace.
Fix is to do tests using unsigned char.
> Fix open/create of UTF8 names

- libdap4/d4parser.c
- oc2/ocinternal.c
* Fixes https://github.com/Unidata/netcdf-c/issues/1667
Make DAP (2 and 4) forcibly report an error message
when an error response is received from the DAP servlet.
> Force error report when DAP gets error response.

- debug/cf
- include/hdf5internal.h
- include/nc4internal.h
- libhdf4/hdf4file.c
- libhdf5/hdf5attr.c
- libhdf5/hdf5debug.c
- libhdf5/hdf5file.c
- libhdf5/hdf5internal.c
- libhdf5/hdf5open.c
- libhdf5/hdf5var.c
- libhdf5/nc4hdf.c
- libsrc4/nc4internal.c
nc4internal.c contains code to free the format_XXX_info
fields. Since these are format specific, this code
was moved to the dispatch code (libhdf5 and libhdf4
in the current case).
Additionally, there are some fields in nc4internal.h (e.g.
dimscale fields) that are specific to HDF5 and have been moved
to the corresponding HDF5 data structures and code.
Misc. other changes:
1. NC_VAR_INFO_T->hdf5_name renamed to alt_name to avoid
implying it is necessarily HDF5 specific.
2. prefix NC_FILE_INFO_T with an instance of NC_OBJ for consistency.
this also requires wrapping move_in_NCList() to keep
hdr.id consistent.
> Fix reclamation of the ->format_XXX_info fields

- RELEASE_NOTES.md
- libdispatch/dfilter.c
- nc_test4/tst_filterparser.c
- plugins/H5Zutil.c
* Fixes issue https://github.com/Unidata/netcdf-c/issues/1687
static functions are being used before decl and it causes
errors. Only occurs when BIG_ENDIAN is defined.
Solution is to add the forward declarations.
> Fix missing forward declarations

- RELEASE_NOTES.md
- libdispatch/dvar.c
- libdispatch/dvarinq.c
- nc_test/tst_formats.c
> now testing that nc_inq_var_deflate()/nc_inq_var_szip() work for all formats and returns settings consistent with no compression in use

- CMakeLists.txt
- NUG/DAP2.dox
- NUG/DAP4.dox
- RELEASE_NOTES.md
- config.h.cmake.in
- configure.ac
- libdap4/d4curlfunctions.c
- libdispatch/dauth.c
- oc2/occurlfunctions.c
* Fixes https://github.com/Unidata/netcdf-c/issues/1684
re: e-support VZL-904142
Two issues:
1. As of libcurl 7.66, the semantics of CURLOPT_SSL_VERIFYHOST
changed so that the non-zero values affects certificate processing.
2. The current library was forcing the values of VERIFYPEER
and VERIFYHOST to zero instead of leaving them to the default values.
Solution was first to leave the defaults in place for VERIFYPEER and VERIFYHOST
as long as they are not set in .ocrc/.dodsrc file.
Second, the value of HTTP.SSL.VERIFYPEER or HTTP.SSL.VERIFYHOST
as set in .ocrc/.dodrc is used to set the corresponding CURLOPT flags.
So for example, adding
> HTTP.SSL.VERIFYHOST=2
will set the value of CURLOPT_SSL_VERIFYHOST to 2, the default.
Using
> HTTP.SSL.VERIFYHOST=0
will set the value of …
> Use proper CURLOPT values for VERIFYHOST and VERIFYPEER

- libhdf5/hdf5var.c
Fixing typo (release `4.7.4`) with CMake Debug builds, introduced in e7b9b1b58717f983ca183980d4c8353199e6bc53.
> Fix build bug in debug mode

- RELEASE_NOTES.md
- ncdump/vardata.c
> Correcting a formatting error for scalars when dumping with ncdump -f

- libhdf5/hdf5dim.c
The current library seems to have some behavior which is N^2 in the number of vars in a file.
The `NC4_inq_dim` routine calls down to `nc4_find_dim_len` which iterates through each `var` in the file/group and calls `find_var_dim_max_length` on each var and finds the largest length of the dim on each of those vars. This is done only for unlimited vars.
I have a file with 129 dim and 1630 vars.  The unlimited dimension is of length 41.  In my test program, I am reading data from 4 files which have the same dim and var count and reading every 4th time step (unlimited dimension).  If I run a profile, I see that 98.2% of the program time is in the `nc_get_vara_float` call tree and most of that is in `find_var_dim_max_length` (94.8%).
There are 66,142 calls to `nc_get_vara_float` resulting in …
> Proof-of-Concept:  Avoid N^2 behavior in NC4_inq_dim

- nc_test4/tst_vars.c
This commented-out line of code in tst_vars.c causes an error in 4.7.4 but works in preceding versions of netCDF.
> added demonstration of nc_def_var_deflate() issue

- RELEASE_NOTES.md
- include/hdf5internal.h
- libhdf5/hdf5cache.c
- libhdf5/hdf5create.c
- libhdf5/hdf5internal.c
- libhdf5/hdf5open.c
- nc_test4/tst_parallel5.c
Fixes #1715 
Also fixed some documentation about cache stuff.
> now properly setting HDF5 file cache for files created/opened sequentially on parallel I/O builds

- libsrc4/CMakeLists.txt
The `error4.c` file is already listed in `libsrc4_SOURCES`, so does not need to be added again later.  The file's contents are only compiled if `LOGGING` is defined, so is ok to always compile.
> Remove duplicate references to error4.c

- config.h.cmake.in
- configure.ac
- libdispatch/nctime.c
- ncdump/nctime0.c
- ncdump/ref_times.cdl
- ncdump/tst_calendars.cdl
This PR changes the `strcmp` and `strncmp` calls to `strcasecmp` and `strncasecmp` calls in `nctime.c`, `nctime0.c` to account for the case-insensitive nature of UDUNITS unit names, and adds a test by piggybacking on the calendar focused test in `ncdump/`.
> Improve ncdump handling of time units

- CMakeLists.txt
Fedora renames the installed `H5pubconf.h` to allow for multi-arch installations. `H5public.h` will always be correct and include the correct version of `H5pubconf`.
> Fix wrong header include in testing HDF5 for zlib

- ncdump/ncvalidator.c
re: Issue https://github.com/Unidata/netcdf-c/issues/1737
Fix one last case of wrapping XGetOpt.h in WIN32 when it should be _MSC_VER.
> Condition XGetOpt on MSC_VER not WIN32

- libdap4/d4meta.c
- libdap4/d4parser.c
Discovered that there were some remaining memory leaks
in the dap4 code as a result of PR https://github.com/Unidata/netcdf-c/pull/1743.
Found and fixed.
> Fix some memory leaks in libdap4

- h5_test/tst_h_vars.c
- include/netcdf_dispatch.h
- libdispatch/Makefile.am
- plugins/Makefile.am
Fixes #1746 
Fixes #1745 
Fixed #1749
> fixed LDFLAFS in plugins Makefile.am, also fixed warning in tst_h_vars.c, restore NC_NOTNC3_get|put_varm() functions

- libhdf5/hdf5var.c
It is possible for the values stored to `file_value_size` to overrun the storage capacity of a 32-bit integer.  The value does need to store negative values potentially, so can be `size_t` or `hsize_t`, so use the `hssize_t` which is a signed 64-bit value.  Could also use `ssize_t`, but that is not used in this routine...
> Avoid potential integer overrun

- README.md
Reference: Issue #1711
-The proper link was provided for the Language Independent User's Guide.
-The proper link was provided for the NetCDF-Java/Common Data Model Library
> Updated README.md Links

- RELEASE_NOTES.md
- ncdump/nccopy.c
re: https://github.com/Unidata/netcdf-c/issues/1763
The nccopy program incorrectly set default chunking parameters
to use full dimension lengths. Instead, it should use the
values computed by the default chunking values as defined
in nc4_default_chunksizes2 in the netcdf library.
Solution: Revert to the old behavior.
> Fix nccopy chunking to use default chunking

- RELEASE_NOTES.md
- h5_test/CMakeLists.txt
- h5_test/Makefile.am
- h5_test/run_par_tests.sh.in
- h5_test/tst_h_par_compress.c
- nc_test4/tst_parallel5.c
In this PR I add a parallel I/O test for HDF5 that does parallel I/O just like the code in nc4hdf.c.
I have found an issue with szip that I am exploring with the HDF5 team. But meanwhile, the zlib test works, so let's get that in. ;-)
Part of #1610
Part of #1580
Part of #1545
> Add a HDF5 only test of writing and reading a file with parallel I/O and the zlib filter

- RELEASE_NOTES.md
- libhdf5/hdf5file.c
- nc_test4/tst_files.c
For classic files (or netCDF/HDF5 files with classic model), calling nc_redef() twice should and does result in NC_EINDEFINE error.
But, in accordance with the automatic handling of enddef/redef for netCDF/HDF5 files, extra calls to redef should just be ignored for netCDF/HDF5 files.
THis PR fixes this issue and makes the code work in accordance with the documentation.
Fixes #1779
> Fix nc_redef() - when called twice on netcdf-4 file, it should return no error

- ncgen/ncdumpchunks.c
The`H5Dread_chunk` function is only available if `HDF5_SUPPORTS_PAR_FILTERS` is defined (See CMakeLists.txt, line 745)  The function was added in HDF5-1.10.3
> Protect use of `H5Dread_chunk` function

- include/hdf5internal.h
- libhdf5/hdf5create.c
- libhdf5/hdf5internal.c
- libhdf5/hdf5open.c
Fixes #1786.
Made `nc_create` and `nc_open` to work the same as before regardless of the HDF5 version.
If on Windows and HDF5>=1.10.6, convert the filename encoding from ANSI to UTF-8 before calling the HDF5 function.
> Convert filename from ANSI to UTF-8 before calling HDF5.

- libdap2/constraints.c
- libdap2/dce.y
- libdap2/dcetab.c
projection functions seemed to get lost in the initial parsing (before sending DAS/DDS/DODS requests). Attempting to implement/use projection functions per `6.1.1.3` below to subset (_run for side effect only_ in this case).
see [Data Access Protocol (DAP), version 2. ESE-RFC-004.1.2](https://www.opendap.org/index.php/support/design-documentation)
```
Functions MAY be called as part of either the projection or selection
clauses. In the case of a selection, the function MUST return a value which can be used when evaluating the
clause. In the case of a projection, the function MUST return a DAP variable which will then be the return
value of the request or it MUST return nothing in which case it is run for side effect only
```
_note: IP below not persistent, but should be able to verify …
> parse projection functions

- RELEASE_NOTES.md
- libdispatch/dhttp.c
Found on conda-forge (which is now running 7.71.1), that byte-range requests would stall. It turns out this is due to
`CURLOPT_NOBODY`--apparently setting this to 0 disables the HEAD request, but does not restore downloading the body. The way to fix this is to reset to `CURLOPT_HTTPGET` when done with a HEAD request.
This was an esoteric thing to track down, the best link I could find regarding the issues with `CURLOPT_NOBODY` is:
https://curl.haxx.se/mail/curlphp-2008-03/0073.html
I can confirm this fixes ncdump doing a byte-range request on this URL on 4.7.4:
https://remotetest.unidata.ucar.edu/thredds/fileServer/testdata/2004050412_eta_211.nc#bytes
Unfortunately, I was not able to build master using cmake to test.
> Fix for cURL >7.69

- ncdump/dumplib.c
Fixed `ncdump -p10` to work properly.
It could not be specified to be longer than the current format string.
> Fix format buffer size

- ncdump/dumplib.c
Fixed to pass remaining buffer size to `strlcat`.
> Correct destination buffer size to strlcat

- plugins/Makefile.am
Convert plugins/Makefile.am to remove H5Znoop1.c
using distclean instead of clean.
> Make plugin noop1 be distcleaned

- h5_test/tst_h_par_compress.c
Fixes #1808 
This PR fixes an incorrect C99 usage in the test.
> fixed tst_h_par_compress.c

- nc_test/tst_atts3.c
Part of #1807 
In this PR I add a test that demonstrates that attempting to write an NC_INT64 attribute in a classic format file results in an NC_EBADTYPE error.
> Add test for using attributes like GFDL FMS does

- libnczarr/zcvt.c
I'm not certain what happened to the relatively minor change that was included in 1814 re: the call to `isnan()` so that it remains C99 compliant.
> Reapply fix supposedly introduced in 1814

- NUG/DAP2.dox
- libdap2/dapdebug.h
- libdispatch/ncuri.c
- ncdump/test_unicode_directory.sh
re: Github issue https://github.com/Unidata/netcdf-c/issues/1832
and Github issue https://github.com/Unidata/netcdf4-python/issues/1041
Handling of URL escape sequences for some servers
(e.g. http://iridl.ldeo.columbia.edu) appears to be somewhat
non-standard.
In particular, certain characters need escaping that other servers
do not. Fortunately, the changes should also work existing other servers.
> Fix URL encoding in DAP2 URL processing

- libhdf5/hdf5open.c
- libhdf5/nc4info.c
Older deprecated APIs will not be compatible with VOLs (for example the DAOS VOL).
> Replaced deprecated (in 1.8.0) H5Aopen_name with H5Aopen_by_name

- nc-config.cmake.in
The `USE_SZLIB` symbol only appeared one time in this file in the entire project.  I think that `USE_SZIP` is the intended symbol.
> Fix setting of use_szlib

- RELEASE_NOTES.md
- libdispatch/nctime.c
* Fixes #1864
* Fixes #1417
A simple PR, thank you very much @Dave-Allured.  This PR is his PR, #1866, plus an entry in the release notes.
> Add release notes to #1866

- libdispatch/nctime.c
Fixes time zone bug reported in #1417.  Does not resolve the request to add time zones in `ncdump -t` printed output.
Also fixes #1864 (duplicate).
> Fix time zone parser bug, github #1417

- libdap4/d4util.c
- libdap4/ncd4.h
* Fixes #1854 
re: https://github.com/Unidata/netcdf-c/issues/1854
Apparently some older Arm processors will fail if asked to
read a 64 bit value from memory if not on an 8 byte boundary.
The primary problem is in reading counter values in the dap4 stream.
So if the Arm processor is detected, then memcpy the value
to an aligned 64 bit value before using it.
> Support aligned access for selected Arm processors.

- CMakeLists.txt
- RELEASE_NOTES.md
- config.h.cmake.in
- configure.ac
- libhdf5/hdf5internal.c
- nc-config.cmake.in
- nc-config.in
- nc_test4/findplugin.in
- test_common.in
There were some irregularities in the flags for handling NCZarr S3 support.
The primary change is to regularize the flags controlling this to the following.
1. Automake: --enable-nczarr-s3 and CMake: ENABLE_NCZARR_S3
2. Automake: --enable-nczarr-s3-tests and CMake: ENABLE_NCZARR_S3_TESTS
Flag 1 indicates that NCZarr should be built with S3 support enabled.
Flag 2 indicates that the NCZarr S3 tests should be run
These two flags are separate because running the NCZarr S3 tests
requires access to protected S3 resources. Currently, running
these tests is restricted to Unidata personnel. However, users
may want to enable S3 support even if they cannot run the tests.
It is, of course, an error to specify 2 without specifying 1.
Additionally, if the AWS S3 SDK library is not found, then the …
> Improve the building of NCZARR S3 support in CMake and Autoconf

- libhdf5/nc4info.c
- libnczarr/zprov.c
If NCPROPERTIES_EXTRA (see configure.ac) is defined
but is null or empty, then an extra comma is being generated
at the end of _NCProperties global attribute.
Soln: check for null/empty NCPROPERTIES_EXTRA value.
> Remove trailing comma from _NCProperties attribute value.

- libhdf5/hdf5file.c
The `http` field of the hdf5 info struct is not defined unless `ENABLE_HDF5_ROS3` or `ENABLE_BYTERANGE` or `ENABLE_S3_SDK` is defined.  Based on a quick look at the code, I think that the `ENABLE_HDF5_ROS3` define is the relavant one here.  Maybe a better fix is to check if any of them are defined...
Fixes #1889 and #1888
> Fix undefined struct member access

- ncdump/CMakeLists.txt
- ncdump/Makefile.am
- ncdump/nccopy.c
- ncdump/ref_keyword1.cdl
- ncdump/ref_keyword2.cdl
- ncdump/test_keywords.sh
- ncgen/ncgen.l
- ncgen/ncgen.y
- ncgen/ncgenl.c
- ncgen/ncgeny.c
- ncgen/ncgeny.h
#1753 + Resolves file conflicts.
> #1753 + Conflict Resolution

- RELEASE_NOTES.md
- ncdump/CMakeLists.txt
- ncdump/Makefile.am
- ncdump/nccopy.c
- ncdump/ref_keyword1.cdl
- ncdump/ref_keyword2.cdl
- ncdump/test_keywords.sh
- ncgen/ncgen.l
- ncgen/ncgen.y
- ncgen/ncgenl.c
- ncgen/ncgeny.c
re: https://github.com/Unidata/netcdf-c/issues/1750
Built-in type-name keywords are currently flagged when used as
identifiers in formats that do not support that type.  So if a
user declares a dimension named "string" in a classic .cdl file,
it causes an error.
This PR modifies ncgen to allow those format-specific type keywords
to be used as identifiers when compiling to formats that do not
support that type. Also added a test for this.
Also a couple of misc. changes to conditional-ize some debug output.
> Allow use of type keywords as identifiers in some formats

- CMakeLists.txt
- libsrc/CMakeLists.txt
> m4 check in cmake provide a clear error when required but not available.

- CMakeLists.txt
The `NC_HAS_MULTIFILTERS` line in `netcdf_meta.h` was not of the correct form  -- showed as
```
#define NC_HAS_MULTIFILTERS
```
Instead of the better form:
```
#define NC_HAS_MULTIFILTERS 0  (or 1 if enabled)
```
> Fix CMake build so netcdf_meta.h has correct form

- libnczarr/zwalk.c
I noticed a piece of duplicate code in libnczarr that could, in rare circumstances, cause bad data to be read/written.
> Remove some potentially harmful duplicate code

- config.h.cmake.in
The library fails to build on Windows with llvm toolset because `_fstat64` is defined twice.
> Fix build on Windows with clang-cl

- libnczarr/zvar.c
There is a small typo in libnczarr/zvar.c.
Should read `maximum` rather than `maximim`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, maximim -> maximum

- libdispatch/dinfermodel.c
If the user is opening a existing file for appending (NC_WRITE) in parallel and the file is in CDF5 format, the `NC_interpret_magic_number()` routine clears the `model->impl` setting of `NC_FORMATX_PNETCDF` which was set in `NC_omodeinfer` (See lines following the `done:` label in that routine which specifically set the `impl` if `useparallel` is true.)
This setting then gets overwritten when `NC_interpret_magic_number` is called which sets the `model->impl` back to `NC_FORMATX_NC3`.  This can (did) cause problems with parallel output as the `NC3` format does not correctly handle parallel writing but the `PNETCDF` does.
Not sure if this is the best place for the test, but it did fix the parallel write issues I was seeing...
If you need more details on what is happening, let me know.  But …
> Fix so setting of NC_FORMATX_NC3 in parallel is kept

- libdispatch/nctime.c
Ncdump reports times like "2015-03-12 12:19:60.000000" #1928
Imposes a microsecond accuracy on dumped time representation
> Fix for :60 seconds in ncdump

- README.md
- docs/FAQ.md
- docs/static-pages/software.html
- docs/testserver.dox
- docs/tutorial.dox
This pull request contains updates to various links (and some text) related to netCDF-Java and the THREDDS Data Server. I also updated some links related to the issue trackers for netCDF-C, netCDF-Fortran, and netCDF-CXX4 since we no longer use Jira.
> Update links related to netCDF-Java and the TDS

- CMakeLists.txt
The name of the variable `HDF5_C_LIBRARY_hdf5` is misspelled as `HDF5_C_LIBRARY_HDF5` in one of the `if` statements in `CMakeLists.txt`. This patch fixes the spelling.
> Fix name of the HDF5_C_LIBRARY_hdf5 CMake variable

- config.h.cmake.in
Without this define parallel netCDF-Fortran did not work
correctly with Open MPI, for example
examples/F90/simple_xy_par_wr.f90
reported
*** An error occurred in MPI_Info_dup
*** reported by process [2543714305,2]
*** on communicator MPI_COMM_WORLD
*** MPI_ERR_INFO: invalid info object
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
Fixes Unidata/netcdf-fortran#109
> Add HAVE_MPI_INFO_F2C to cmake config.h input file

- libnczarr/zwalk.c
Even though the `fflush()` is on the same line as the `fprintf(stderr, ...` statement, it is not part of the `if` and is therefore, executed even if the `wdebug` is not active.  This results in `fflush()` being called more than it should.  
Added parenthesis to property protect the fflush call.
> Fix if statement to apply to fflush

- CMakeLists.txt
The `ISCMAKE` was defined after its first use in a `configure_file` call.  Moved to before its first use.
> Fix use of ininitialized CMake variable

- plugins/Makefile.am
- plugins/blocksort.c
- plugins/bzlib.c
- plugins/bzlib.h
- plugins/bzlib_private.h
- plugins/compress.c
- plugins/crctable.c
- plugins/decompress.c
- plugins/huffman.c
- plugins/randtable.c
* Fixes #1969
re: Issue https://github.com/Unidata/netcdf-c/issues/1969
> Update the bzip library in plugins to version 1.0.8

- lib_flags.am
- add $(top_builddir)/include to include directory search
Since we create some includes during the build
> Fix out of tree builds with configure

- .github/workflows/run_tests.yml
- RELEASE_NOTES.md
- ncdump/Makefile.am
- ncdump/ref_keyword3.cdl
- ncdump/ref_keyword4.cdl
- ncdump/test_keywords.sh
- ncgen/generate.c
- ncgen/genlib.h
- ncgen/ncgen.l
- ncgen/ncgen.y
- ncgen/ncgenl.c
- ncgen/ncgeny.c
- ncgen/ncgeny.h
re: https://github.com/Unidata/netcdf-c/issues/1977
PR https://github.com/Unidata/netcdf-c/pull/1753 changed ncgen to allows certain type names to be used as identifiers in selected situations.
An unwanted side effect was that existing type aliases no longer were accepted by ncgen. Specifically, using the "long" type caused an error.
I was able to figure out a better solution to the original problem (https://github.com/Unidata/netcdf-c/issues/1750) that also fixes this problem as well.
This PR fixes that problem and adds tests to ncdump/test_keywords.sh
> Fix the handling of certain alias types in CDL files.

- RELEASE_NOTES.md
- include/ncpathmgr.h
- libdispatch/dutil.c
- ncdump/nccopy.c
- ncdump/ncdump.c
- ncgen/main.c
- nczarr_test/ncdumpchunks.c
- nczarr_test/s3util.c
- nczarr_test/tst_utils.c
- nczarr_test/zmapio.c
- unit_test/test_pathcvt.c
re: https://github.com/Unidata/netcdf-c/issues/1988
There was an issue with certain shell programs (bash notably).
For certain platforms and when given a url that had an escaped
'#' character (e.g. \\#) bash would not remove the backslash. So I
had to add a hack for this. Unfortunately I overdid it and it
removed all '\\' characters. This is ok for non-windows platforms,
but obviously fails for windows.
The fix is this.
1. In a utility program (ncgen, ncdump, nccopy, etc) there is probably a call (or calls) to NC_backslashUnescape(xxx) where xxx is a path argument from the command line.
2. Replace each such call with NC_shellUnescape(xxx).
The NC_shellUnescape function was added and searched only for occurrences of "\#" and replaces them with "#".
A test case was added to …
> Fix shell handling of escapes

- RELEASE_NOTES.md
- ncdump/dumplib.c
* Fixes #2002 
re: issue https://github.com/Unidata/netcdf-c/issues/2002
It turns out that ncdump has an error where it assumes that the set of all dimension ids has no holes. That is that (maxid+1) = ndims. This is incorrect for a variety of reasons for netcdf-4.
So instead of counting total number of dimensions in a dataset, it is necessary to look for the maximum dimension id and use that when allocating a table of all dimensions.
> Fix counting of dimensions in ncdump

- .github/workflows/run_tests.yml
- RELEASE_NOTES.md
- nczarr_test/Makefile.am
A stray directory was causing makedist to fail.  This PR fixes this, and adds 'make distcheck' to the github actions CI.
> Makedist is failing in nczarr_test

- RELEASE_NOTES.md
- include/hdf5internal.h
- libdispatch/derror.c
- libhdf5/hdf5filter.c
- libhdf5/hdf5open.c
- libhdf5/hdf5var.c
- libnczarr/zinternal.h
- nc_test4/tst_filter.sh
* Fixes #1996 
re: https://github.com/Unidata/netcdf-c/issues/1996
Improve the error message and location that is reported when reading a filter with a variable that uses a filter that is not available on the reading platform.
This requires checking the availability of the filter, recording it, and failing when any attempt is made to read or write that variable. A test case was added for this in tst_filter.sh. Also, LOG level 0 message is generated giving the variable and the filter id.
Note that by design if there is no attempt to read or write the variable, then no error is reported; this means that, for example, ncdump -h will list the filter even though it is not actually available. This is important for allowing a user to see the filter details.
> Improve error message when non-existent filter is encountered.

- CMakeLists.txt
Some of the tests for HDF5 symbols are failing due to not finding the include file which skews the test results.  Added the `CMAKE_REQUIRED_INCLUDES` command to set the path.  In one place this was already set, but used `HAVE_HDF5_H` which is not an include path and isn't even set at the location where it was used.  We may not need these set more than once, but I added them before each `CHECK_C_SOURCE_COMPILES` in case those blocks get moved around and the value gets unset when it should be set.
Also changed the `H5Literate_vers` check to check  that it is defined instead of checking the value.  As best I can see, as long as it is defined, then the `H5Literate` symbol will be defined which is what is needed.  Checked with 1.10.7 and 1.12.0
> Fix some HDF5-related tests

- .github/workflows/run_tests.yml
- RELEASE_NOTES.md
- dap4_test/dump.c
- ncdump/nccopy.c
- ncdump/ncdump.c
- ncdump/ncvalidator.c
- ncdump/ocprint.c
- ncgen/main.c
- ncgen3/main.c
- nczarr_test/bm_utils.c
- nczarr_test/ncdumpchunks.c
- nczarr_test/s3util.c
- nczarr_test/test_nczarr_utils.h
- nczarr_test/tst_utils.c
- nczarr_test/ut_test.c
- nczarr_test/zmapio.c
- nczarr_test/zs3parse.c
* Fixes #2003 
* 
re: https://github.com/Unidata/netcdf-c/pull/2003#issuecomment-847637871
Turns out that mingw defines both _WIN32 and also defines getopt.
This means that this test:
````
#ifdef _WIN32
#include "XGetopt.h"
#endif
````
fails on this error:
````
../include/XGetopt.h:38:24: error: conflicting types for 'getopt'
````
Fix is to replace
````
#ifdef _WIN32
with
#if defined(_WIN32) && !defined(__MINGW32__)
````
> Fix Mingw versus XGetopt (again)

- CMakeLists.txt
* Set `CMAKE_REQUIRED_INCLUDES` to include the path found for `curl.h`.  The `CHECK_C_SOURCE_COMPILES` function uses this and not the `INCLUDE_DIRECTORIES`
* Make the test for version 7.66 or later match the same test in `configure.ac`
* If the version is 7.66 or later, then we can skip the tests for the curl symbols which were all added in versions prior to 7.66.
* If the version is earlier than 7.66, then continue to perform the tests.
> Clean up curl symbol tests

- CMakeLists.txt
- fuzz/CMakeLists.txt
- fuzz/fuzz_open.c
@WardF would you agree to merge this fuzz target upstream ?
cf https://github.com/google/oss-fuzz/pull/5389#discussion_r604596718
> Adds fuzz target for oss-fuzz integration

- CMakeLists.txt
We use the CMake `VERSION_LESS` test other places, might as well use it here and  eliminate another compile-based test.
> Simply version check logic

- .github/workflows/run_tests.yml
- RELEASE_NOTES.md
- libnczarr/zutil.c
The construction of the chunk key is malformed
when using dimension_separator rather than always
using '/'.
This is a priority bug.
> Fix chunk key when using dimension_separator - high priority

- libhdf5/H5FDhttp.c
In HDF5 1.12.1, this was changed from optional to required per the changelog:
>H5Epush_ret() is a function-like macro that has been changed to
>contain a `do {} while(0)` loop. Consequently, a trailing semicolon
>is now required to end the `while` statement. Previously, a trailing
>semi would work, but was not mandatory.
This should be backward compatible with older version of HDF5.
Also fixes https://github.com/Unidata/netcdf-c/issues/2033.
> libhdf5/H5FDhttp: add missing semicolons to H5Epush_ret

- ncdap_test/Makefile.am
This avoids the test case to fail if it isn't.
Signed-off-by: Egbert Eich <eich@suse.com>
> check: Include testpathcvt.sh only if test is built

- nczarr_test/Makefile.am
- nczarr_test/bm_timer.h
- nczarr_test/bm_utils.c
- nczarr_test/bm_utils.h
* Fixes https://github.com/Unidata/netcdf-c/issues/2055
The nczarr_test benchmarks were missing some files and one was
out of date vis-a-vis compilation.
> Add missing files so --enable-benchmarks works again.

- libdispatch/dinfermodel.c
In VTK, there are some files which require the NC3 implementation, but
no longer open under 4.8.0 (it worked under 4.7.4). The code checks to
make sure that certain formats were *not* requested when it is entirely
reasonable that support may be required for other files.
This partially reverts changes made in
59e04ae0712a59688e5ae80dfbe7fc4c295d2826 which is a massive commit which
adds Zarr support but doesn't mention why this specific change was made.
---
Cc: @DennisHeimbigner
> dinfermodel: don't fail if NC_NETCDF4 is allowed, but NC3 is found

- nc_perf/Makefile.am
- nc_perf/tst_gfs_data_1.c
Fixes #2067 
Make nc_perf directory not run test programs in parallel.
Also turn off nc_perf/tst_gfs_data_1.c for HDF5 versions prior to 1.10.2, which parallel writes with compression was introduced.
@WardF it would be great if this could make it in before the release...
> made nc_perf not build and run benchmarks in parallel, turn off benchmark tst_gfs_data_1.c for HDF5 versions less than 1.10.2

- ncdump/tst_compress.c
Make the data in the variable `var1` easier to compress so that the compression tests will be more robust.  The zlib_ng library, for example, at level 1 does not compress a sequence of integers very well which resulted in the NetCDF-4 compressed file being larger than the uncompressed NetCDF-3 file.  With the change above, the variable contains `0,0,0,1,1,1,2,2,2,...,` which compresses at level 1 and the compression test is more robust.
> Make variable easier to compress

- configure.ac
Fixes #2045 
Fix comment and text of configure option --disable-dap-remote-tests.
> Fix comment and text of configure option --disable-dap-remote-tests.

- nc_perf/Makefile.am
Fixes #1812 
turned off running of run_knmi_bm.sh benchmark with make check (for --enable-benchmark builds). THis benchmarking script gets some files from Unitdata's ftp site, which presents problems and is slow. So this benchmark will no longer be run by make check.
@WardF it would be great if this could make it into the release...
> turned off running of run_knmi_bm.sh benchmark with make check (for --enable-benchmark builds)

- CMakeLists.txt
- ncdap_test/CMakeLists.txt
Revamping HDF5_VERSION logic flow in CMakeLists.txt.  Originally, this information was only used to determine if we had met the minimum supported version threshold.  It has grown since then.  We now check for versions as a cmake-infrastructure provided environmental variable; if that is not available, we attempt to determine the version programmatically using code contributed (I believe) by @edwardhartnett.  If we ultimately cannot determine the HDF5_VERSION through any method, cmake will exit with an error.
> Revamping the HDF5_VERSION logic.

- libdispatch/dvar.c
- libhdf5/hdf5var.c
- libsrc4/nc4cache.c
* Fixes #2096 
re: Issue https://github.com/Unidata/netcdf-c/issues/2096
The methods nc_set_var_chunk_cache_ints and nc_def_var_chunking_ints
are Fortran entry points for accessing the cache. They are not defined
if netcdf-c is built with --disable-hdf5.
Fix is to create dummy versions that do nothing and return NC_NOERR
when invoked. These dummy versions are defined when USE_HDF5 is false.
> Make the fortran cache API always be defined.

- CMakeLists.txt
On some versions of the HDF5 find_package call, it sets `HDF5_C_LIBRARIES` and `HDF5_HL_LIBRARIES`, but does not set the `HDF5_C_LIBRARY` or `HDF5_HL_LIBRARY` to anything.  Control then falls out of the if block with these unset and it falls into the default setting at line 792.  This does not include the path, so then when the later `CHECK_LIBRARY_EXISTS` calls are run, they do not have the full path to the library and will not link correctly.  Since the link fails, the code defaults to thinking that none of the symbols are defined.
I don't think this change will have any affect since it only sets the symbols if they are unset.
I moved the comment about MSVC environment variables into the MSVC portion of the if to avoid possible confusion.
> Make sure HDF5_C_LIBRARY and HDF5_HL_LIBRARY set

- libhdf5/hdf5internal.c
Fixes an issue with strlen() reading outside the stack allocated buffer
by NC4_HDF5_inq_att, when reading a name whose length is NC_MAX_NAME.
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=39189 found
on GDAL
==1895951== Conditional jump or move depends on uninitialised value(s)
==1895951==    at 0x483EF58: strlen (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==1895951==    by 0x48EF73E: ncindexlookup (ncindex.c:60)
==1895951==    by 0x48E81DF: nc4_find_grp_att (nc4internal.c:587)
==1895951==    by 0x48E5B39: nc4_get_att_ptrs (nc4attr.c:72)
==1895951==    by 0x48F98A0: NC4_HDF5_inq_att (hdf5attr.c:818)
==1895951==    by 0x48847F7: nc_inq_att (dattinq.c:91)
==1895951==    by 0x10D693: pr_att (ncdump.c:767)
==1895951==    by 0x110ADB: do_ncdump_rec …
> Fix a stack-read-overflow in ncindexlookup()

- RELEASE_NOTES.md
- configure.ac
- include/ncconfigure.h
- include/ncrc.h
- libdispatch/dpathmgr.c
- libdispatch/drc.c
- libdispatch/dutil.c
- libsrc/memio.c
- ncdump/CMakeLists.txt
- ncdump/Makefile.am
- ncdump/ref_rcmerge1.txt
- ncdump/ref_rcmerge2.txt
- ncdump/ref_rcmerge3.txt
- ncdump/test_rcmerge.sh
- ncgen/ncgen.l
- test_common.in
- unit_test/tst_xcache.c
1. Issue https://github.com/Unidata/netcdf-c/issues/2043
* FreeBSD build fails because of conflicts in defining the fileno() function. So removed all extern declarations of fileno.
2. Issue https://github.com/Unidata/netcdf-c/issues/2124
* There were a couple of problems here.
* I was conflating msys with mingw and they need separate handling of paths. So treat mingw like windows.
* memio.c was not always writing the full content of the memory to file. Untested fix by properly accounting for zero size writes.
* Fix bug when skipping white space in tst_xcache.c
3. Issue https://github.com/Unidata/netcdf-c/pull/2105
* On MINGW, bash and other POSIX utilities use a mounted root directory,
but executables compiled for Windows do not recognise the mount point.
Ensure that Windows paths are …
> Fix a number of OS specific bugs

- CMakeLists.txt
HDF5 can depend on the Z library (in fact required for netCDF).  Moved the detection of whether hdf5 was built with zlib up before any other tests that may require linking of the hdf5 library to determine presence/absence of symbols.  These tests require that the link line include "-lz" if the hdf5 library was built with libz support.  
This is typically handled somewhat automatically if shared libraries are being used, but in the static library case, the explicit dependency needs to be specified.  For internal CMake checks, it uses the `CMAKE_REQUIRED_LIBRARIES` list to specify the libraries that should be used in a `CHECK_C_SOURCE_COMPILE` or a `CHECK_LIBRARY_EXISTS` call.   In the current CMakeLists.txt ordering, the zlib detection is done _after_ the `CHECK_LIBRARY_EXISTS` calls which …
> Refactor Z library detection

- configure.ac
The remotetest server is down for a while
because of the log4j security flaw.
So we default to disabling dap-remote-tests.
> Temporarily disable dap remote tests

- CMakeLists.txt
The remotetest server is down for a while
because of the log4j security flaw.
So we default to disabling dap-remote-tests.
This PR adds disable to CMake
> Disable by default dap-remote-tests for CMake

- CMakeLists.txt
- configure.ac
- ncdap_test/tst_urls.sh
The remote test server is up again. So re-enable.
Also do some test cleanup.
> Restore default enable for enable-dap-remote-testsc

- .github/workflows/run_tests.yml
- RELEASE_NOTES.md
- dap4_test/test_hyrax.sh
- ncdap_test/findtestserver.c.in
- ncdap_test/tst_urls.sh
- ncdump/CMakeLists.txt
- ncdump/tst_netcdf4_4.sh
The ncdump test set has a number of inter-test dependencies
that are not properly established in ncdump/CMakeLists.txt.
So this PR attempts to:
1. reorder the tests
2. change tests in CMakeLists.txt from build_bin_test_no_prefix to add_bin_test_no_prefix so they get executed
Plus a couple of minor bug fixes.
1. Change ENABLE_NC4 => ENABLE_HDF5 in github action.
2. fix a memory error in findtestserver.c.in
3. fix bug in ncdap_tests/tst_urls.sh
4. fix netcdf file name bug in tst_netcdf4_4.sh
> Cleanup the CMake inter-test dependencies

- nc_test4/tst_misc.sh
Fix recent bug in tst_misc.sh that causes hang in make check.
Affects netcdf-c 4.8.1 on Mac.
> tst_misc.sh: Fix hang in make check

- include/netcdf.h
- include/netcdf_meta.h.in
- libdispatch/dvar.c
- libdispatch/dvarinq.c
- libhdf5/hdf5open.c
- libhdf5/hdf5var.c
- libhdf5/nc4hdf.c
- libsrc4/nc4var.c
- nc_test4/tst_quantize.c
Granular BitGroom (GBG) combines features of BitGroom, BitRound by Kouznetsov (2020), and DigitRound by Delaunay et al. (2019). GBG improves compression ratios by ~20% relative to BitGroom for NSD=3 on our benchmark 1 GB climate model output dataset. Its invocation is identical to BitGroom, so this patchset mainly utilizes a new enumerated value of the quantize_mode flag to invoke the new algorithm. No tests (yet) in this patchset. For correctness, GBG can be compared to current implementations in NCO and CCR.
> Granular BitGroom feature for netcdf-c

- nc_test4/test_filter_misc.c
- nczarr_test/testfilter_misc.c
I was just checking to see if the build warnings were meaningful. I feel like some of them are.
This was was "straightforward" to cleanup, but I never saw symptoms of of its "wrongness".
> Fix a few memory leaks and erroneous logic in nczarr_test/testfilter_misc

- .github/workflows/run_tests_osx.yml
- include/hdf5internal.h
- libhdf5/CMakeLists.txt
- libhdf5/Makefile.am
- libhdf5/hdf5create.c
- libhdf5/hdf5open.c
- libhdf5/hdf5set_format_compatibility.c
This is @Dave-Allured 's PR #2176 but with the recently-added OSX checks in place, as a proof of concept.
> Dave allured format compat on reopen

- include/hdf5internal.h
- libhdf5/CMakeLists.txt
- libhdf5/Makefile.am
- libhdf5/hdf5create.c
- libhdf5/hdf5open.c
- libhdf5/hdf5set_format_compatibility.c
Closes #951.
Supplements the change in PR #1931.
This PR selects the best HDF5 format compatibility options when re-opening an existing netCDF-4 file for writing, such as appending, or adding new groups or variables.
The general objective is to make netCDF-4 files that can be read and written by all previous library  versions.  Optimal HDF5 v1.8 compatibility is selected whenever possible.  Otherwise this falls back to the adequate v1.6 compatibility.
Format compatibility is a transient property of the HDF5 library, rather than baked in at file creation time.  Therefore, compatibility options must be re-selected every time a netCDF-4 file is re-opened for writing.
This builds on the previous update for initial file creation, PR #1931, by @brtnfld, released in netcdf-c version 4.8.1.
In …
> HDF5 format compatibility when re-opening files

- .github/workflows/run_tests_ubuntu.yml
* Remove HDF5 `1.10.1` from the test matrix, replace `1.10.7` with `1.10.8`.
* For the one-off tests, replace `1.10.7` with `1.12.1`.
> Collapse and update the HDF5 versions being tested on Github Actions.

- RELEASE_NOTES.md
- include/ncs3sdk.h
- libdispatch/ds3util.c
- libdispatch/ncs3sdk.cpp
- liblib/nc_initialize.c
- ncdap_test/Makefile.am
- ncdap_test/findtestserver.c.in
- nczarr_test/run_interop.sh
* Fixes https://github.com/Unidata/netcdf-c/issues/2151
The use of a non-AWS appliance broke during the switch to testing
against Amazon S3.
So make necessary changes to get non-AWS appliances work correctly.
> Fix use of S3 with a non-AWS appliances

- liblib/Makefile.am
* Fixes #2196 
Thanks to @matzeri for reporting this apparent accidental removal of `${NOUNDEFINED}`  in `liblib/Makefile.am` in commit 26f8ebda466f64db8d85820413fb445ae97393d9.
> Correct the accidental removal of NOUNDEFINED in liblib/Makefile.am

- .github/workflows/run_tests_ubuntu.yml
* Update test matrix for latest HDF5, replace `1.8.21` with `1.8.22`.
1.8.22 was released 2021 February 5.
https://portal.hdfgroup.org/display/support/HDF5%201.8.22
This follows another recent matrix update in #2194.
This would depend on the latest `HDF5 1.8.22` being available in CI.
This is untested by me.  Let's just see what CI does with it.
> CI: Update HDF5 testing 1.8.21 --> 1.8.22

- CMakeLists.txt
- Makefile.am
- fuzz/CMakeLists.txt
- fuzz/Makefile.am
- libnczarr/Makefile.am
- nc_test4/Makefile.am
- ncdump/cdl/Makefile.am
- ncdump/expected/Makefile.am
- nczarr_test/Makefile.am
* Fixes #2166 
Clean up some of the issues with `make dist` generated tarballs when used with `cmake`.
> Address issue with `make dist` generated tarballs, subsequent cmake builds

- libhdf5/hdf5set_format_compatibility.c
* Comment change only.  Add one paragraph.  Explain the reason for the third argument to H5Pset_libver_bounds.  Simplifies experimental code using advanced features.
This updates the original function added in PR Unidata#2176.
> hdf5set_format_compatibility.c: Update new function documentation.

- CMakeLists.txt
The presence of cmake_policy(CMP0075 requires CMake >=3.12, and
errors with older CMake. Since older versions of CMake than 3.12
are already broken with NetCDF and uncommon nowadays, it may be
better to explicitly require 3.12 or newer.
This also enables hinting external libraries such as HDF5 via variable HDF5_ROOT, which is very handy
when using NetCDF from an ExternalProject in CMake.
This also suppresses several nuisance warnings about unexpected behavior when using a modern CMake version.
> CMake: CMP0075 requires CMake >= 3.12.

- RELEASE_NOTES.md
* Add current release note for #2176.
* Add missing note for #951 in release 4.8.0.
* Improve related old note for release 4.4.1.  Better consistency with recent updates.
* Minor link and spelling fixes (in separate commit).
> Release notes for #2176 format compatibility

- include/nc3dispatch.h
- libncpoco/cp_unix.c
- libnczarr/zinternal.h
- ncdump/dumplib.h
- ncdump/indent.h
- ncgen3/ncgen.l
- ncgen3/ncgen.y
- ncgen3/ncgenl.c
- ncgen3/ncgeny.c
- nctest/tst_rename.c
- oc2/ocinternal.h
- oc2/xxdr.h
Clang is considering making this warning an error by default: https://discourse.llvm.org/t/rfc-enabling-wstrict-prototypes-by-default-in-c/60521
> Fixed Clang -Wstrict-prototypes warnings

- libdap4/d4dump.c
- libdap4/d4util.h
- libdispatch/daux.c
- libsrc/ncx.m4
- oc2/xxdr.c
With the introduction of GCC v.11 numerous test cases in nc_test started to fail on x86_64. This was mostly due to improved optimizations applying aliasing rules more strictly. Recently, this issue has been mitigated by setting -fno-strict-aliasing  where available.
This set of patches attempts to fix all cases where strict aliasing violations were either flagged as warnings by GCC directly or where another warning (ie a warning about an uninitialized variable) was the result of a strict aliasing violation.
These fixes resolved all detected test failures.
> Fix Compiler Strict Aliasing Rule Violations

- ncdump/ncdump.c
If #2084 is merged , netcdf utilities will use Windows paths on mingw-w64. This leads to problems in the output from `ncdump`, such as the following error from `dap4_test/test_meta.sh`:
```
checking: test_anon_dim.2.syn
1c1
< netcdf test_anon_dim.2 {
---
> netcdf .\\results_test_meta\\test_anon_dim.2 {
```
The default name of the dataset is supposed to be the basename of the input file, minus any file extension. The existing function `name_path` which determines the default dataset name assumes that paths have Unix directory separators (`/`), but Windows paths use `\\`. This PR produces a compatible path format using function `NCpathcanonical` instead of `NCpathcvt`.
> Use canonical path to derive name of dataset on Windows

- libnczarr/zcvt.c
re: issue https://github.com/Unidata/netcdf-c/issues/2265
The zarr code is generating "Nan" instead of "NaN" on windows.
This causes failures.
Solution: fix typo.
> Fix typo "Nan" -> "NaN"

- include/ncdispatch.h
- libdispatch/CMakeLists.txt
- libdispatch/Makefile.am
MPI_Comm and MPI_Info should only be used when parallel I/O is enabled.
Compiling file libdispatch/dparallel.c is skipped when parallel I/O is disabled.
> avoid type redefine of MPI_Comm and MPI_Info

- .github/workflows/run_tests_ubuntu.yml
Fixes #2279 
Adds pnetcdf to the parallel I/O testing on GitHub.
> Adds pnetcdf to the parallel I/O testing on GitHub.

- configure.ac
fixes #2285 
@WardF this should be merged before the release or many users will start crying when their netcdf_meta.h file breaks their compiles.
> fixed missing NC_HAS_QUANTIZE

- examples/C/Makefile.am
- nctest/Makefile.am
- nczarr_test/Makefile.am
turning off tests that depend on ncpathcvt when --disable-utilities is used
Fixes #2281
> turning off tests that depend on ncpathcvt when --disable-utilities is used

- libdispatch/dinfermodel.c
ensuring that MPI_File_close() is only called on open MPI file handle
Fixes #2283
> ensuring that MPI_File_close() is only called on open MPI file handle

- .github/workflows/run_tests_osx.yml
- .github/workflows/run_tests_ubuntu.yml
> Remove on-push trigger for OSX-based workflows.

- include/ncdispatch.h
- libdispatch/CMakeLists.txt
- libdispatch/Makefile.am
Fixes #2299 
Return the parallel I/O functions to the build. 
If they are to be removed, it will require a lot of work on netcdf-fortran.
With this PR, netcdf-c goes back to the way it was and fortran works again. Attempts to change the presence of the parallel I/O functions need to also work on netcdf-fortran.
@WardF this should definitely be merged before the next release, or else netcdf-fortran will break.
> fixed parallel functions for netcdf-fortran build

- include/ncxml.h
When building netcdf as static libraries and executables on mingw-w64, the build fails while linking `ncgen.exe`, due to numerous undefined references to symbols in ncxml. These symbols are being defined for dll import, which is not appropriate when netcdf is built statically. A minor change to the preprocessor logic solves the problem on mingw-w64, and with this change, the (static) build completes and all tests pass.
> Fix dll exports for ncxml

- libdispatch/dutil.c
- libsrc/ncio.c
- nc_test/tst_diskless6.c
- nc_test4/tst_quantize.c
- unit_test/test_pathcvt.c
Fixes all warnings in the code.
Fixes #2306
> fixed all code warnings

- nc_test/Makefile.am
When using configure options --enable-pnetcdf --disable-hdf5,
I got error message below when running make check.
```
HYDU_create_process: execvp error on file ./tst_cdf5format (No such file or directory)
FAIL run_pnetcdf_tests.sh (exit status: 255)
```
I suggest to add in github actions a test option of --enable-pnetcdf --disable-hdf5
> allow to test tst_cdf5format when PnetCDF is enabled

- libdispatch/nchashmap.c
Fixes #2157 
Fix an intel compiler build problem.
> declared a variable outside for loop

- libnczarr/zcvt.c
This PR solves issue https://github.com/Unidata/netcdf-c/issues/2302.
> use isnan instead of _fpclass on non-MSVC compilers

- include/netcdf.h
- libdispatch/dvar.c
- nc_test4/tst_vars3.c
Fixes #1704.
@WardF since the next release is all about compression, it would be good if this fix could be merged before the release.
> fixed missing szip constants in netcdf.h

- ncgen/genc.c
Found by @Yonah125 with CodeQL
We first have allocation in the loop:
`Bytebuffer* tmp = bbNew();`
And we `continue` on to the next loop execution before having called `bbFree(tmp)`
What do you think of it @DennisHeimbigner ?
> fix memory leak in genc_netcdf

- libdispatch/drc.c
- ncdap_test/tst_utils.sh
* Fixes #2349 
* Fixes #2347 
Fixes issues that have cropped up with MacOS, also attempts to get around the unexpected issues with merging #2347.
> Removed precision fiddling on OSX

- libdispatch/dattget.c
Part of #2329 
This fixes the last of the doxygen warnings other than those in filters.md.
Once #2348 is merged I will fix the filters.md warnings, then we can turn on doxygen's WARN_AS_ERROR, and add a documentation build to the CI. Then new PRs will have to have no documentation warnings in order to pass CI. ;-)
> fixed more doxygen warnings

- docs/filters.md
- nc_test4/tst_specific_filters.sh
Part of #2329.
Fix the last few doxygen warnings.
I believe once all my outstanding PRs on doxygen are merged, we will get a warning-free doxygen build, and can then turn on automatic warning checking in CI to prevent any more doxygen warnings from occurring.
> fixed documentation warnings in filters.md

- CMakeLists.txt
The include_files argument was malformed due to a missing `${` at the beginning.  Was expanding to (e.g.) the literal `Zstd_INCLUDE_DIRS}` instead of to the contents of the `Zstd_INCLUDE_DIRS` variable.
> Fix syntax error

- docs/filters.md
I believe it is worth explicitly mentioning the error margins introduced by various methods.
Also references to relevant papers made as DOI.
> Add doc on errors introduced by lossy compression

- ncgen/bindata.c
In the second case, `arraycount` is uninitialized. In the first, just initializing at definition instead of a couple lines later...
> Initialize variable

- ncdump/ncpathcvt.c
If `cvtoptions.pathkind` is true, then `canon` will not be initialized and it is accessed at line 279.
> Initialize potentially uninitialized variable

- RELEASE_NOTES.md
- libhdf5/hdf5var.c
re: Github Issue https://github.com/Unidata/netcdf-c/issues/2401
The nc_def_var_fletcher32 code in hdf5 is always setting fletcher32 when invoked.
Fix is to properly test value of the fletcher32 argument.
> Fix nc_def_var_fletcher32 operation

- CMakeLists.txt
- RELEASE_NOTES.md
- libdispatch/ddispatch.c
- ncdap_test/t_auth.c
- test_common.in
re: https://github.com/Unidata/netcdf-c/issues/2380
re: https://github.com/Unidata/netcdf-c/issues/2337
This PARTIALLY fixes some HOME problems because under Windows,
the HOME environment variable may not be set. In that case, use the
USERPROFILE environment variable instead.
> Use env variable USERPROFILE instead of HOME for windows and mingw.

- libdispatch/ddispatch.c
re: https://github.com/Unidata/netcdf-c/pull/2408
re: https://github.com/Unidata/netcdf-c/pull/2405
Got use of $HOME and $USERPROFILE mixed up.
So fix it.
> Fix choice of HOME dir

- libdispatch/dutil.c
Otherwise running command below as part of nc_test/run_inmemory.sh can
be very slow
./tst_diskless4 500000000 opendiskless
> increase read block size from 1 KB to 4 MB

- RELEASE_NOTES.md
- configure.ac
Brings `configure` into parity with the `cmake`-based build, in terms of being able to disable `quantize` support at build time.  This won't be used much in practice, but it will make it easier to test downstream packages (like netcdf-fortran, etc) for things that might break if quantization isn't available, such as with an older libnetcdf install.
> Add `--disable-quantize` to configure

- RELEASE_NOTES.md
- libhdf5/hdf5file.c
- libhdf5/nc4hdf.c
- nc_test4/tst_quantize.c
Fixes #2441 
As @czender discovered, quantize mode does not work with classic model. 
Here's the fix. @WardF this should be merged as soon as possible so the main branch has the correct behavior.
> fix and test quantize mode for NC_CLASSIC_MODEL

- libdispatch/dreg.c
* Fixes #2446 
Credit to [DWesl](https://github.com/DWesl) and [matzeri](https://github.com/matzeri).
> Guard _declspec(dllexport) in support of #2446

- include/nc_tests.h
- nc_test4/tst_quantize.c
Fixes https://github.com/Unidata/netcdf-c/issues/2455
Fixes https://github.com/Unidata/netcdf-c/issues/2454
More quantize testing.
> more quantize testing and adding pre-processor constant NC_MAX_FILENAME to nc_tests.h

- ncgen/ncgen.l
- ncgen/ncgenl.c
- ncgen/ncgeny.c
- ncgen/ncgeny.h
* Fixes #2487 
The code being generated in `ncgenl.c` was jumping to a preceding label, which was triggering an error when compiling with `CFLAGS=-Werror=jump-misses-init`.  I've replaced the jump with an equivalent call to `return 0`; it's possible that the `goto done` was also not supposed to be there, but I don't want to change the behavior of the code while trying to diagnose a different issue (see #2486).  @DennisHeimbigner, I can't request you as a reviewer, but should the `goto done` have been there in the first palce?
> Address jump-misses-init issue.

- .github/workflows/run_tests_osx.yml
- .github/workflows/run_tests_ubuntu.yml
- .github/workflows/run_tests_win_mingw.yml
- RELEASE_NOTES.md
- docs/nczarr.md
- libdispatch/ncjson.c
- libnczarr/zcvt.c
- libnczarr/zinternal.h
- libnczarr/zsync.c
- libnczarr/zvar.c
- libnczarr/zwalk.c
- nczarr_test/CMakeLists.txt
- nczarr_test/Makefile.am
- nczarr_test/ref_scalar.cdl
- nczarr_test/ref_string.cdl
- nczarr_test/ref_string_nczarr.baseline
- nczarr_test/ref_string_zarr.baseline
- nczarr_test/run_quantize.sh
- nczarr_test/run_scalar.sh
- nczarr_test/run_strings.sh
re: PR https://github.com/Unidata/netcdf-c/pull/2492
re: Issue https://github.com/Unidata/netcdf-c/issues/2494
This PR fixes some problems with the pull request https://github.com/Unidata/netcdf-c/pull/2492 in response to Issue https://github.com/Unidata/netcdf-c/issues/2494.
* Found and fixed more scalar handling problems and add a test case for scalars.
* Cleanup nczarr_test/run_string.sh test
* Document *_nczarr_default_maxstrlen* and *_nczarr_maxstrlen*.
* Support both "Nan" and *Nan* as being floating point constants
for attributes. It is unclear from the Zarr V2 spec if
unquoted *Nan* is legal or not, but support for reading.
Write the quoted versions when writing an attribute.  Similar
for Infinity constants.
So NCZarr supports the following constants for use in Attributes
* *Nan*, …
> Fix some problems with PR 2492

- docs/attribute_conventions.md
> Changed attribute case in documentation

- configure.ac
Updated `configure.ac` to check for `zstd.h` in addition to `libzstd` runtime libraries.  This fixes a compile-time error otherwise encountered when the latter is present but the former is missing. 
Also added `stdint.h` to the list of files checked for in `configure.ac`, otherwise a baffling error would sometimes occur due to `uintptr_t` not being detected by some tests, detected in others.
> Check for zstd development headers in autotools

- nc-config.in
Darn these C programmer habits. This fixes a small typo in `nc-config.in`.
> Small fix in nc-config.in

- nc_test4/tst_virtual_datasets.c
I get an error about "for loop initial declarations are only allowed in C99 mode" with the current code.  Not sure why it hasn't shown up before.  I am configuring with `BUILD_SHARED_LIBS=NO ENABLE_PLUGINS=NO ENABLE_MULTIFILTERS=NO ENABLE_NCZARR_FILTERS=NO` when the error shows up using gcc-7.2.0.
> For loop initial declarations are only allowed in C99 mode

- ncdump/CMakeLists.txt
Discovered as part of working on https://github.com/conda-forge/libnetcdf-feedstock/pull/140
> Fix prereqs in ncdump/tst_nccopy4 in order to avoid race conditions.

- libdap4/d4chunk.c
* Fixes #2536 
re: Issue https://github.com/Unidata/netcdf-c/issues/2536
> Turn off extraneous debug output

- libdispatch/dutil.c
> replace 4194304 with READ_BLOCK_SIZE

- libnczarr/zutil.c
I was getting the following error while compiling:
```
netcdf-c/libnczarr/zutil.c:544:26: error: called object 'strlen' is not a function or function pointer
544 |     if(dnamep) *dnamep = strdup(dname);
|                          ^~~~~~
netcdf-c/libnczarr/zutil.c:533:68: note: declared here
533 | ncz_nctype2dtype(nc_type nctype, int endianness, int purezarr, int strlen, char** dnamep)
|                                                                ~~~~^~~~~~
```
My interpretation is that strdup() is implemented as a macro which calls strlen() the standard C function, and when that macro is being substituted here the call to strlen tries to "call" the integer variable named strlen.
Resolving this by renaming the integer variable to "len" instead of "strlen", avoiding a conflict with a …
> Rename variable to avoid function name conflict

- configure.ac
Small fix for an issue that snuck through.
> Make dap4 reference dap instead of hard-wired to be disabled.

- RELEASE_NOTES.md
- nc_test4/CMakeLists.txt
- nc_test4/Makefile.am
The test case nc_test4/tst_unknown.sh deletes and then restores a filter in the plugins directory. The test nczarr_test/run_unknown.sh also does this.  However if both are running at the same time in a parallel environment, they apparently can interfere and can cause a race condition failure.
The solution is to suppress one of them. Since nczarr code is more unstable, we need to run this test. So suppress the corresponding test in nc_test4.
> Suppress nczarr_test/tst_unknown filter test

- .github/workflows/run_tests_osx.yml
- .github/workflows/run_tests_ubuntu.yml
- .github/workflows/run_tests_win_cygwin.yml
- .github/workflows/run_tests_win_mingw.yml
- libdispatch/dfile.c
- libdispatch/dinfermodel.c
- libdispatch/ncbytes.c
- libdispatch/nclist.c
- libnczarr/zsync.c
- libnczarr/zvar.c
* Fixes #2573 
re: Issue https://github.com/Unidata/netcdf-c/issues/2573
The file type inferencer in libdispatch/dinference.c has a simple forward inference mechanism so that the occurrence of certain mode values in a URL fragment implies inclusion of additional mode values. This kind of inference is notorious for leading to cycles if not careful. Unfortunately, this occurred in the one in dinference.c.
This was fixed by providing a more complicated, but more reliable inference mechanism.
* Found and fixed a couple of memory leaks.
* There is a recent problem in building HDF4 support on github actions. Fixed by using the internal HDF4 xdr capability.
* Some filter-related code was not being properly ifdef'd with ENABLE_NCZARR_FILTERS.
> Fix infinite loop in file inferencing

- ncdump/Makefile.am
In the PR accepted earlier today, I neglected to ensure `make distcheck` wasn't impacted by my inclusion of `tst_calendars_nc4.sh` into the autoconf-based tests.  It was, predictably, so here is the fix.
> Fix an issue I introduced with make distcheck

- libdispatch/dfile.c
- libdispatch/dinfermodel.c
- nc_test4/tst_udf.c
Offered as an alternative to #2585 this PR frees NC_UDF0 of the NC_NETCDF4 requirement and 
addresses the issue in #2582.   Note that I did not change the NC_UDF1.
> make UDF0 not require NC_NETCDF4

- dap4_test/Makefile.am
- docs/CMakeLists.txt
- docs/Makefile.am
- libdispatch/dvar.c
- ncdump/utils.c
re: PR https://github.com/Unidata/netcdf-c/pull/2584
re: PR https://github.com/Unidata/netcdf-c/pull/2596
Repaired a memory leak in *netcdf-c/ncdump/utils.c*. I think introduced by PR 2584.
* Fixed references to *netcdf-c/docs/byterange.dox* ->  *netcdf-c/docs/byterange.md* (PR 2596).
> Fix Memory Leak

- .github/workflows/run_tests_ubuntu.yml
This is a reference to an issue (#2547) with how most distribution packagers run Autotools (source in one directory, compile in another, install to a third).  There was a PR (#2546) to catch errors in that kind of build by running `make distcheck` which was turned down due to [a preference for separate compile and test steps](https://github.com/Unidata/netcdf-c/pull/2546#discussion_r1018356480). This PR should test the out-of-tree builds, taking into account the preference for separate build and compile steps.
`make distcheck` would also catch files not being specified in `EXTRA_DIST` (#2548, #2544), though I could change the tests to do that as well (have one of the earlier CI runs make a source archive at the end and upload that, then download that in this step and use the source …
> CI: Change autotools CI build to out-of-tree build.

- .github/workflows/run_tests_osx.yml
- .github/workflows/run_tests_ubuntu.yml
- .github/workflows/run_tests_win_cygwin.yml
- .github/workflows/run_tests_win_mingw.yml
Update Github actions to work with Node.js 16 instead of Node.js 12.
> Update github action configuration scripts.

- RELEASE_NOTES.md
- configure.ac
Manage a subset of changes made as part of the release processes, that should go back into the `main` development branch.
> Merge v4.9.1 wellspring back into development branch

- RELEASE_NOTES.md
- libhdf5/H5FDhttp.c
- libhdf5/H5FDhttp.h
re: Issue https://github.com/Unidata/netcdf-c/issues/2614
Most of the changes are minor comment changes.
But the dispatch table for H5FD has changed, requiring changes to H5FDhttp.c, which is derived from the HDF5 source file H5FDstdio.c. The patch is to conditionally modify the dispatch table to conform to the HDF5-1.14.0 version.
I was able to build and successfully test 1.14 for a reasonable set of (non-parallel) ./configure options.
> Modify H5FDhttp.c to work with HDF5 1.14.0

- RELEASE_NOTES.md
- libhdf5/H5FDhttp.h
- nczarr_test/Makefile.am
- nczarr_test/run_interop.sh
- nczarr_test/s3util.c
The problem was that files were being copied
into the $ {srcdir} rather than $ {builddir} directory.
> Fix a distcheck failure with nczarr_test/run_interop.sh

- libsrc/var.c
- nc_test/util.c
* Fixes #1983 
A cast was resulting in undefined behavior, and had to be worked around in a style approximating C++'s 'reinterpret_cast'.  This was discovered using the `-fsanitize=undefined` compiler flag w/ `clang`, and there is a lot of other work to be done.  I am hoping that these fixes, when patched in to `libnetcdf-feedstock`, will also address the issue observed at https://github.com/conda-forge/libnetcdf-feedstock/issues/138.
> A small, but meaningful start, to addressing undefined behavior

- include/nc4internal.h
- libhdf5/hdf5internal.c
This fixes configuration with `--disable-parallel4 --enable-pnetcdf`. It looks like `NC_FILE_INFO` has the `comm` member (i.e. `grp->nc4_info->comm` is valid) only if `USE_PARALLEL4` is defined (see [here](https://github.com/Unidata/netcdf-c/blob/b1fd4b840df341dd8be3545c22e2ad15a985e97c/include/nc4internal.h#L291-L294)).
> Fix macro usage

- libdispatch/dhttp.c
There is either a missing `goto fail` on this line, or the empty if statement line should be removed.
> Missing `goto fail`

- CMakeLists.txt
I discovered an issue with the shelltest macro in CMake-based builds, which may have been fouling up some of the `DAP` tests, insofar as we were accidentally passing an argument which may have caused tests to be skipped.
> Fix a syntax issue in CMakeLists.txt

- CMakeLists.txt
- nczarr_test/CMakeLists.txt
Old older, common versions of `cmake` < `3.19`, the `CONFIGURE_FILE` command doesn't accept file permission bit arguments.  Introducing a workaround for this rather than enforce manual upgrades of cmake.
> Adding a workaround for older versions of cmake

- CMakeLists.txt
In CMake logically ON, YES, TRUE, 1 are equivalent. But  many CMake editors won't syntax highlight a lower-case "yes", and CMake-gui will change OPTION or CACHE BOOL values to ON, creating unnecessary changes to CMakeCache.txt. Also indent an MSVC if/then block.
> CMakeLists.txt use ON vs yes, indent

- configure.ac
Currently, the configuration fails on macOS with the `--disable-libxml2` option:
```console
configure: error: Error: OSX requires libxml2 => --disable-dap4.
```
The configuration fails even if we add an extra option `--disable-dap`.
Also, one of the two lines [here](https://github.com/Unidata/netcdf-c/blame/7cb42a673903e9fd80008f9cff0cb0ca8c6f08ed/configure.ac#L1251-L1252) is redundant: the configuration should either fail or override the user's choice and proceed. Although I personally prefer the former, the latter seems to be a common pattern in the configure script. Therefore, this MR switches from `AC_MSG_ERROR` to `AC_MSG_WARN` and modifies the misleading message (there is no option `--disable-dap4`). It also doesn't make sense to emit the message and set `enable_dap4` to `no` if the …
> Fix building on macOS

- .github/workflows/run_tests_osx.yml
- .github/workflows/run_tests_ubuntu.yml
- configure.ac
- libncxml/tinyxml2.cpp
- libncxml/tinyxml2.h
re: PR https://github.com/Unidata/netcdf-c/pull/2710
Apparently (see above PR) tinyxml2 now works under OS/X. So this PR is a follow on to the above PR. It modifies our OS/X github action to test tinyxml2 under OS/X.
> Update tinyxml and allow its use under OS/X.

- RELEASE_NOTES.md
- dap4_test/baseline/test_vlen4.nc.d4d
- dap4_test/baseline/test_vlen4.nc.d4m
- dap4_test/baseline/test_vlen4.nc.d4p
- dap4_test/baselinehyrax/amsre_20060131v5.dat.hyrax
- dap4_test/baselineraw/test_vlen4.nc.ncdump
- dap4_test/baselineremote/test_atomic_array.1.nc.ncdump
- dap4_test/baselineremote/test_atomic_array.2.nc.ncdump
- dap4_test/baselineremote/test_atomic_array.3.nc.ncdump
- dap4_test/baselineremote/test_enum_array.6.nc.ncdump
- dap4_test/baselineremote/test_one_vararray.4.nc.ncdump
- dap4_test/baselineremote/test_one_vararray.5.nc.ncdump
- dap4_test/baselineremote/test_opaque_array.7.nc.ncdump
- dap4_test/baselineremote/test_struct_array.8.nc.ncdump
- dap4_test/baselineremote/test_vlen4.nc.ncdump
- dap4_test/baselinethredds/2004050300_eta_211.nc.thredds
- include/hdf5internal.h
- include/netcdf_filter_hdf5_build.h
- libdap4/d4parser.c
- libhdf5/hdf5open.c
- nc_test4/tst_h_transient_types.c
- plugins/H5Zblosc.h
- plugins/H5Zzstd.h
re: PR https://github.com/Unidata/netcdf-c/pull/2655
This PR modifies the transient types PR so that all created transient types are given a created unique name (within a group). The form of the name is "_Anonymous\<Class\>NN". The class is the user-defined type class: Enum, Compound, Opaque, or Vlen. NN is an integer identifier to ensure uniqueness. Additionally, this was applied to DAP/4 anonymous dimensions. This also required some test baseline data changes.
The transient test case is modified to verify that the name exists.
> Modify PR 2655 to ensure transient types have names.

- RELEASE_NOTES.md
1.  Add missing [File Change] tag to old 4.4.1-RC1 release note which modified hdf5 file format control.  This improves consistency for format research.
2.  Minor spelling fix, coincidental.
> Release notes:  Minor.  Add historical tag, and spell fix.

- libsrc/posixio.c
- nc_test/test_byterange.sh
* Fixes https://github.com/Unidata/netcdf-c/issues/2731
A corrupted classic file is causing the library to crash. Fix so that it returns NC_ENOTNC instead.
> Fix a crash when accessing a corrupted classic file.

- libdispatch/dfilter.c
- libhdf5/nc4hdf.c
- libnczarr/zfilter.c
- nc_test/test_byterange.sh
- nc_test4/Makefile.am
- nc_test4/tst_filter_vlen.c
- nc_test4/tst_filter_vlen.sh
re: PR https://github.com/Unidata/netcdf-c/pull/2716).
* Fixes https://github.com/Unidata/netcdf-c/issues/2189
The basic change is to make use of the fact that HDF5 automatically suppresses optional filters when an attempt is made to apply them to variable-length typed arrays. This means that e.g. ncdump or nccopy will properly see meaningful data. Note that if a filter is defined as HDF5 mandatory, then the corresponding variable will be suppressed and will be invisible to ncdump and nccopy. This functionality is also propagated to NCZarr.
This PR makes some minor changes to PR https://github.com/Unidata/netcdf-c/pull/2716 as follows:
* Move the test for filter X variable-length from dfilter.c down into the dispatch table functions.
* Make all filters for HDF5 optional rather than …
> Explicitly suppress variable length type compression

- CMakeLists.txt
- RELEASE_NOTES.md
- config.h.cmake.in
- configure.ac
- libhdf5/nc4hdf.c
- libnczarr/zcache.h
- libnczarr/zinternal.h
- libnczarr/zvar.c
- libnczarr/zxcache.c
- libsrc4/nc4internal.c
- nc_test4/tst_chunks.c
- nczarr_test/tst_zchunks.c
re: Issue https://github.com/Unidata/netcdf-c/issues/2733
When addressing the above issue, I noticed that there was a disconnect in NCZarr between nc_set_chunk_cache and nc_set_var_chunk cache. Specifically, setting nc_set_chunk_cache had no impact on the per-variable cache parameters when nc_set_var_chunk_cache was not used.
So, modified the NCZarr code so that the per-variable cache parameters are set in this order (#1 is first choice):
1. The values set by nc_set_var_chunk_cache
2. The values set by nc_set_chunk_cache
3. The defaults set by configure.ac
> Cleanup the handling of cache parameters.

- CMakeLists.txt
H5public.h might require MPI headers which we haven't found at this point
Fixes #2742
> CMake: Change header in check for HDF5 zlib/szip support

- libdispatch/nclog.c
* Fixes #2773 
One of the changes in df3636b introduced the ability to filter log messages by level. This fixes a typo that flipped the intended filtering, so that `NCLOGOFF` _enabled_ all messages instead of _disabling_ them.
> Fix bug with displaying log messages

- .github/workflows/run_tests_ubuntu.yml
Instead of a clone of the repository, have the `nc-autotools` job work from a source distribution prepared by a previous autotools CI job.
This should catch most of the "files not included in `EXTRA_DIST`" or similar issues I remember, and probably most of the "netcdf-c does not pass `make distcheck`" errors.
I'm not sure whether this is in scope for a CI job, but the `nc-autotools` jobs should be a fairly complete copy of `make distcheck` now; the only things I can think of not included in that job would be `make install` and `make installcheck`.  I'm only aware of #2431 raising issues with installed files, so that may be less relevant.
> CI: Have nc-autotools use source distribution instead of repository

- .github/workflows/run_tests_cdash.yml
- .github/workflows/run_tests_osx.yml
- .github/workflows/run_tests_s3.yml
- .github/workflows/run_tests_ubuntu.yml
- .github/workflows/run_tests_win_cygwin.yml
- .github/workflows/run_tests_win_mingw.yml
Discovered yesterday that netCDF was clogging up some of the Github Action pipeline for the rest of the Unidata org.  This is because rapid pushes of changes do not cancel existing test runs, as had been my impression. Thanks @dopplershift for pointing this out, and for pointing me in the right direction to ameliorate this.
> Added stanza to workflow actions so that pushed changes cancel tests

- CMakeLists.txt
Fixes #2597
CMake 3.21 was released in 2021 and is available in the latest release of all the big distros (see https://pkgs.org/search/?q=cmake). If it's necessary to support older versions of CMake, a reasonable backport is something like:
```cmake
if (${CMAKE_PROJECT_NAME} STREQUAL ${PROJECT_NAME})
include(CMakeInstallation.cmake)
endif()
```
[`CMAKE_PROJECT_NAME`](https://cmake.org/cmake/help/latest/variable/CMAKE_PROJECT_NAME.html) is the top-level project name  
[`PROJECT_NAME`](https://cmake.org/cmake/help/latest/variable/PROJECT_NAME.html#variable:PROJECT_NAME) is the current project name (i.e. `netCDF`!)
It might also be friendlier to expose an option to allow changing this:
```cmake
if (${CMAKE_PROJECT_NAME} STREQUAL ${PROJECT_NAME})
set(_default_install_option ON)
else() …
```
> CMake: Don't add uninstall target and CPack config if not top-level

- libdispatch/dfile.c
- nc_test/tst_diskless.c
- nc_test/tst_diskless3.c
This fixes compiler errors on FreeBSD 14.
> Renamed mmap variable, which conflicts with mmap() function on FreeBSD

- configure.ac
* Fixes #2792 
Added fenceposts so that dependencies and options specific to nczarr are skipped if nczarr is not enabled.
> Make ncZarr-specific deps and options dependent on ncZarr being enabled.

- libdispatch/ncexhash.c
- libdispatch/nclistmgr.c
Just made sure to use unsigned, so that a bit does not get shifted into a sign bit.
> Fixed various UBSan warnings about invalid bit shifting

- libdispatch/utf8proc.c
Any pointer arithmetic with NULL pointers is technically UB, even if you don't end up dereferencing the pointer.
> Fixed various UBSan warnings about working with NULL pointers

- libsrc/ncx.m4
Use memcpy to copy correctly even for unaligned memory. This was already done for some functions here, but not all.
Also took the oppurtunity to remove a bunch of seemingly obsolete/commented code.
> Fixed misaligned memory access flagged by UBSan

- include/ncpathmgr.h
- include/ncs3sdk.h
- libdispatch/dcopy.c
- libdispatch/derror.c
- libdispatch/nch5s3comms.c
- libdispatch/nclist.c
- libncpoco/cp_unix.c
- libncpoco/cp_win32.c
- libncpoco/ncpoco.c
- libncpoco/ncpoco.h
- libsrc/v1hpg.c
- s3gc.in
The most critical bug is in nch5s3comms.c.
I for some reason assumed that signing keys
did not contain any zero bytes. But obviously
it can, so some conditional code was removed.
Other fixes:
1. Guarantee allocated memory is initialized to all zeros.
2. Cleanup errmsg handling in libncpoco.
3. Fix processing of aws list-objects-v2 because I misread the syntax.
> Fix some important bugs in various files

- nc_test4/tst_virtual_datasets.c
Initializing and declaring variable in for loop statement requires C99 mode.  NetCDF is compiled in C89 mode.
> Enable compilation with C89 compiler

- h5_test/tst_h_dimscales2.c
- h5_test/tst_h_enums.c
- h5_test/tst_h_files.c
- h5_test/tst_h_par.c
- h5_test/tst_h_par_compress.c
- h5_test/tst_h_strings2.c
- h5_test/tst_h_vars.c
- libhdf5/hdf5var.c
- libnczarr/zvar.c
- nc_perf/tst_files3.c
- nc_test4/tst_virtual_datasets.c
Argument 'count' in NetCDF is not exactly the same as the 'count' in
H5Sselect_hyperslabs(space_id, op, start, stride, count, block).
When the argument 'stride' is NULL, NetCDF's 'count' should be used in
argument 'block', for example,
```
H5Sselect_hyperslabs(space_id, op, start, NULL, ones, count);
```
where 'one' is an array of all 1s. Although using NULL 'block' below
```
H5Sselect_hyperslabs(space_id, op, start, NULL, count, NULL);
```
has the same effect, HDF5 internally stores the space of a subarray as a
list of single elements, instead of a "block", which can affect the
performance.
> count argument in H5Sselect_hyperslab

- docs/mainpage.dox
Fix link to Fortran documentation, thanks @edwardhartnett
> Changed link to netCDF-Fortran documentation.

- libsrc/posixio.c
It looks like on some platforms (e.g., MinGW) errno isn't set
when opening a file failed. That combination of a file id <0
and errno still 0 leads to a segmentation fault later on.
A possible solution to avoid that segfault is to set the status
to ENOENT if errno is unexpectedly 0.
That leads to the error ("No such file or directory") that was
reportedly emitted before version 4.9.0.
See also this report downstream: https://github.com/msys2/MINGW-packages/issues/11918
> Avoid segfault if opening file failed

- libhdf5/H5FDhttp.c
- libhdf5/H5FDhttp.h
- libhdf5/hdf5dispatch.c
> Add H5FD_http_finalize function and call on hdf5 finalize

- nc_perf/bm_file.c
> add new compression to bm_file benchmark

- .gitignore
- docs/Doxyfile.in
- docs/cloud.md
- docs/dispatch.md
- docs/filters.md
- docs/internal.md
- docs/nczarr.md
Some doxygen warnings for undefined references ended up in the dev branch, somehow which is fouling up CI.  This should fix that, so that we can continue getting the other PR's merged.
> Fix doxygen warnings

- CMakeLists.txt
The cmake build of nc-config relies on config file variable `USE_SZIP` which does not exist. In keeping consistent with the naming, this value is derived from `HAVE_SZ`
> Define USE_SZIP variable for nc-config.cmake.in

- cmake/check_hdf5.cmake
- cmake/dependencies.cmake
I was a bit hasty in #2757: some linux distros rename `H5pubconf.h` so we need to potentially check a few headers. I've wrapped this up to keep things clean in the main CMake file.
> CMake: Find HDF5 header we can safely include for other checks

- RELEASE_NOTES.md
- libdap2/CMakeLists.txt
- libdap4/CMakeLists.txt
- libdispatch/CMakeLists.txt
- libsrc/CMakeLists.txt
- nc_test/CMakeLists.txt
- ncdump/CMakeLists.txt
- ncgen/CMakeLists.txt
- nctest/CMakeLists.txt
Allows to speed-up compilation, or at least avoid erros in vtk where netcdf is used as a third-party
> CMake: Add support for UNITY_BUILD

- liblib/CMakeLists.txt
Neither #2595 nor #2758 fully addressed the underlying issue that final `netcdf` target linking was failing due to missing dependencies previously defined in other internal targets. While a valid solution to manually specify linking dependencies again, part of the effort is to make use of the target structure in cmake to further inform future linking.
The usage of the generator expression `$<TARGET_OBJECTS:...>` negates any target-specific linking that ought to be inherited to the `netcdf` target. To avoid this issue internal targets such as `dispatch` should be directly linked. Since target `netcdf` does not have `PUBLIC/PRIVATE` definitions for its  linking, a compromise for now is to use the `$<TARGET_NAME_IF_EXISTS:...>` generator expression which will fully fix linking even prior to …
> Link against internally defined libraries

- CITATION.cff
- Makefile.am
- docs/credits.md
* Fixes #2848 
Initial pass, will be fleshed out with feedback from appropriate folks @ Unidata.
> Add citation.cff file

- CMakeLists.txt
The #2842 PR changed most CMake keywords to lowercase, but missed (a portion) of the UNSET commands which were changed to `UNset`.  This follows on to that and pushes them all the way to `unset`
> Minor -- fix UNset to unset

- .github/workflows/run_tests_osx.yml
- .github/workflows/run_tests_ubuntu.yml
As discovered in #2847, we are not properly testing static builds, which has allowed an issue to creep in.
> Add static build to one-off GitHub Actions testing.

- cmake/check_hdf5.cmake
Without this PR, only the first file within the loop is checked for. Therefore, it fails if the first file is not found.
Without PR:
```
-- Checking for HDF5 config header
-- Looking for H5public.h
-- Looking for H5public.h - not found
CMake Error at cmake/check_hdf5.cmake:30 (message):
Could not include any HDF5 config headers
Call Stack (most recent call first):
```
With PR:
```
-- Looking for H5public.h
-- Looking for H5public.h - not found
-- Looking for H5pubconf.h
-- Looking for H5pubconf.h - found
-- Using H5pubconf.h to check for feature macros
```
> Fixes finding HDF5 header

- .github/workflows/run_tests_ubuntu.yml
I think this change got lost in a merge
> CI: Fix version of HDF5 used in one-off test

- h5_test/tst_h_files4.c
The netCDF library supports many versions of HDF5, which handles API compatibility via a set of API-call-specific macros. netCDF uses H5Literate(), which was versioned in the 1.12.x maintenance line in order to better support the virtual object layer (VOL).
h5_test/tst_h_files4.c failed to compile with certain compilers when the HDF5 library was built using pre-VOL versions of the library- e.g., 1.10, which can be configured with --with-default-api-version=110. This was due to the API compatibility macros being used to select the 1.10 version of H5Literate(), but not its callback function, which was set using a `H5_VERSION_GE()` macro that does not take the compatibility macros into consideration.
Fixing the problem involved removing the `H5_VERSION_GE()` macro and letting the …
> Fix for H5Literate() callback versioning

- ncdump/dumplib.c
- ncdump/dumplib.h
The easy win here was changing the return type of `sbuf_len` which is used in a lot of places in this file. Two alternatives that I think would be cleaner but require touching more places:
1. Change the `typ_tostring_func` function pointer typedef to return `size_t`. This is more correct as it matches the current return type of `sbuf_len`, which is returned from the implementations of this prototype.
2. Change the `typ_tostring_func` return type to `void` -- as far as I can tell, the return value of these functions isn't used anywhere that they're called, I think it's an entirely internal module. Doing this would also mean that the call to `sbuf_len` in these functions could also be removed entirely
This PR fixes about 55 warnings
> Fix most warnings in `dumplib.c`

- include/nc4internal.h
- libhdf5/hdf5attr.c
- libhdf5/hdf5create.c
- libhdf5/hdf5dim.c
- libhdf5/hdf5file.c
- libhdf5/hdf5internal.c
- libhdf5/hdf5open.c
- libhdf5/hdf5type.c
- libhdf5/hdf5var.c
- libhdf5/nc4hdf.c
- libhdf5/nc4memcb.c
The remaining warnings basically fall into two categories: 
- those from `NC_ATT_INFO.len` being `int` -- changing this to `size_t` would silence a lot of warnings in one go
- those from HDF5 filters -- the filter type in HDF5 itself is `H5Zfilter_t == int`, whereas netcdf mostly uses `unsigned int`; and then the flags/parameters are exactly the other way round.
The filter types can't be completely fixed because they're in the netcdf public API, but we could fix the internals and just convert on the boundary. This is would change a bunch of internal API though, so I haven't done that here.
> Silence most warnings in libhdf5

- include/onstack.h
- libsrc/dim.c
- libsrc/httpio.c
- libsrc/memio.c
- libsrc/mmapio.c
- libsrc/nc3internal.c
- libsrc/posixio.c
- libsrc/putget.m4
- libsrc/v1hpg.c
- libsrc/var.c
The few remaining warnings are either not obvious what the correct type should be, or would require changing multiple function prototypes to fix, so I've left them in.
> Silence most warnings in `libsrc`

- libdap2/cache.c
- libdap2/constraints.c
- libdap2/dapodom.c
- libdap2/daputil.c
- libdap2/ncd2dispatch.c
- libdispatch/dinfermodel.c
- libdispatch/drc.c
- libhdf5/hdf5filter.c
- libnczarr/zchunking.c
- libnczarr/zfilter.c
- ncdump/ocprint.c
- oc2/ocutil.c
Changes backward-loops over lists\* from this pattern:
```c
int i;
size_t length_of_list = /* ... */;
for(i=length_of_list-1;i>=0;i--) {
...
```
to this:
```c
size_t length_of_list = /* ... */;
for(size_t i = length_of_list; i-->0;) {
...
```
This form enables using an unsigned type for the loop index, which usually fixes a couple of sign conversion warnings.
---
\* or at least those that currently trigger sign-conversion warnings in the `for` statement or in the loop body
> Fix warnings from backwards-loops

- cmake/dependencies.cmake
- libdap2/CMakeLists.txt
- libdap4/CMakeLists.txt
- liblib/CMakeLists.txt
- libsrc/CMakeLists.txt
- oc2/CMakeLists.txt
Bumping to the most recent version of `libcurl` under Windows+Visual Studio unearthed some issues, so I've taken a stab at modernizing the cmake-based infrastructure. The pressure for this release has hit critical mass, so we will be releasing pretty soon, after this and other recent PRs have been reviewed, some documentation gets updated, etc.  We will also be coordinating a Fortran release to happen at/near the same time, followed by a refresh of the C++ interface library.
> Modernize CURL in netCDF cmake

- include/ncconfigure.h
- libdispatch/dmissing.c
This allows to statically link libnetcdf into binaries that already contain this symbol from another location.
Fixes #927
> Rename the vendored strlcat symbol

- ncgen3/CMakeLists.txt
- ncgen3/genlib.c
- ncgen3/ncgen.l
- ncgen3/ncgen.y
- ncgen3/ncgenl.c
- ncgen3/ncgeny.c
- ncgen3/ncgeny.h
This is a large change due to regenerating the generated files in `ncgen3` using a more recent version of flex/bison
> Fix warnings in `ncgen3`

- netCDFConfig.cmake.in
Changes in `5ee66e87ac52b5c626afefdcd96833c2b055008b` broke netCDF Fortran cmake-based builds.  The fault likes in netCDF-Fortran, undoubtedly, but until we can refresh netCDF Fortran's cmake configuration, we'll need to accommodate that.  This does not appear to introduce any conflicts with `netCDFTargets.cmake`.
> Re-introduce targets into netCDFConfig.cmake.in

- docs/FAQ.md
- docs/attribute_conventions.md
- docs/known_problems.md
- docs/static-pages/software.html
- hdf4_test/run_get_hdf4_files.sh
- nc_perf/run_knmi_bm.sh
- `/ftp/pub/netcdf/contrib/*` has been archived offline.  We can resurrect it at any time if needed.
- `/ftp/pub/netcdf/sample_data/*` has been moved to:  https://resources.unidata.ucar.edu/sample_data/*
> changes associated with the removal of the Unidata ftp site.

- CMakeLists.txt
- libncpoco/CMakeLists.txt
- plugins/CMakeLists.txt
> CMake: Enable plugins on MinGW

- CMakeLists.txt
- libsrc/CMakeLists.txt
- ncdump/CMakeLists.txt
- ncgen/CMakeLists.txt
- ncgen3/CMakeLists.txt
* Fixes #2920 
Modify `CMakeLists.txt` files to honor [`CMAKE_INSTALL_MANDIR`](https://cmake.org/cmake/help/latest/command/install.html).
> Honor CMAKE_INSTALL_MANDIR

- include/ncs3sdk.h
- libdispatch/ds3util.c
- libdispatch/ncs3sdk_aws.cpp
- libdispatch/ncs3sdk_h5.c
- libnczarr/zmap_s3sdk.c
- nczarr_test/run_corrupt.sh
re: Issue https://github.com/Unidata/netcdf-c/issues/2927
The NC_s3sdkinitialize and NC_s3sdkfinalize functions were misplaced. They should have been moved from ds3util.c to ncs3sdk_h5.c.  When using ncs3sdl_aws.cpp, this resulted in a duplicate definition.
* Factored out the common code of the ncs3sdk_xxx files.
* Fixed a memory leak in the NCZarr S3 code.
* Suppress a google storage test when using aws-sdk-cpp because google storage is not supported.
> Fix duplicate definition when using aws-sdk-cpp.

- CMakeLists.txt
- RELEASE_NOTES.md
- config.h.cmake.in
- configure.ac
- include/nc_logging.h
- libsrc4/nc4internal.c
The NETCDF_ENABLE_SET_LOG_LEVEL_FUNC option is apparently not used directly. But it is effectively used to set NETCDF_ENABLE_SET_LOG_LEVEL. This is not clear from the build files CMakeLists.txt and configure.ac. So this PR cleanups the code to make it more clear what is going on.
> Cleanup handling of NETCDF_ENABLE_SET_LOG_LEVEL and NETCDF_ENABLE_SET_LOG_LEVEL_FUNC

- docs/filters.md
There were several HDF5_PLUGIN_PATH that did not have the underscore escaped.  A few other symbols with similar issues.
Fixed some code blocks that appeared broken on my markdown viewer... Not sure if that is the case in general.
There was a HDF5_PLUGIN_DIR referenced near the bottom.  I think it was supposed to be _PATH, but could be wrong since there are multiple _DIR and _PATH througout the code and scripts...
> Clean up some inconsistencies in filter documentation

- cmake/dependencies.cmake
Not sure if this is the best solution.  Figured I would propose and let people throw arrows at it...
This method works for me when I have a local HDF5 build; the previous method seems to have issues comparing version numbers...  I don't know if the other method is supposed to search multiple HDF5 installs and pick only one that satisfies the version requirement where this version will stop after finding the first installation in its search path and then check the version...
Another benefit is that it prints the version of the HDF5 library that was found which may be useful.
Addresses problem detailed in #2932
> Different method for checking HDF5 version requirement

- CMakeLists.txt
The configuration of the `nc-config` file uses some symbols that were not defined until later in the file.  This caused the quantize and zstd support lines to be incorrect.
This PR moves the configuration of nc-config after all of the `is_enabled` variable setting calls.  It is now close to the other generated files (libnetcdf.settings and netcdf_meta.h) which also use those symbols
> Fix ordering in CMakeLists.txt

- CMakeLists.txt
Current code defines the CMAKE_MODULE_PATH as a cache variable[1]. As a result, if one passes the `-DCMAKE_MODULE_PATH=<something>` to the cmake invocation, its contents override the paths to netcdf-bundled cmake modules. Based on code and attempt to use Shell-PATH-like expansion, it looks as unintended behavior. Moreover, it's quite common in CI/CD systems to pass extra cmake module paths (e.g., we have to do so for AWS SDKs, on which netcdf depends optionally). This tiny fix replaces that with `list(APPEND)` which adds paths to netcdf-provided modules to the user-passed -DCMAKE_MODULE_PATH. At the same time, if user doesn't passes this variable - the previous behavior is preserved, as netcdf paths will be added to that CMAKE_MODULE_PATH currently holds (if netcdf is built as standalone …
> Fix: CMAKE_MODULE_PATH contents is being overriden with -D contents, not merged with

- nczarr_test/Makefile.am
re: Issue https://github.com/Unidata/netcdf-c/issues/2966
The nczarr_test/Makefile.am had the alternate, verbose test-driver-verbose enabled. This PR disables it.
> Some debugging output was left enabled by accident.

- libdispatch/ncuri.c
fix ncuriparse error,Correctly remove leading and trailing whitespace.
When I use netcdf-c to connect to the nc file at the following path (D:/文档/test.nc), netcdf-c prompts me with a parameter error. After my investigation, I found that the error is caused by the ncuriparse function incorrectly interpreting the file path as a URI.
> fix ncuriparse error,Correctly remove leading and trailing whitespace

- config.h.cmake.in
- libhdf5/hdf5open.c
> Expand logic around H5Literate2 data structure use.

- configure.ac
Fixes https://github.com/Unidata/netcdf-c/issues/2967
The CMake and autotools builds were doing different things with the plugin dir default. The CMake behavior is more useful for users.
In this PR I change the configure.ac to match the CMake behavior. I also add some documentation.
> fixed --with-plugin-dir option to match cmake behavior

- README.md
Part of #2963
Updating README with links to new install documentation (probably should wait until after 4.9.3 country.)
> updated README with install documentation

- libhdf5/nc4hdf.c
This PR addresses issue #2962.
All tests pass locally:
```
...
227/231 Test #227: nczarr_test_run_fillonlyz .................   Passed    0.08 sec
Start 228: nczarr_test_run_nczfilter
228/231 Test #228: nczarr_test_run_nczfilter .................   Passed    0.07 sec
Start 229: nczarr_test_run_filter
229/231 Test #229: nczarr_test_run_filter ....................   Passed    0.39 sec
Start 230: nczarr_test_run_specific_filters
230/231 Test #230: nczarr_test_run_specific_filters ..........   Passed    0.43 sec
Start 231: nczarr_test_run_filter_vlen
231/231 Test #231: nczarr_test_run_filter_vlen ...............   Passed    0.13 sec
100% tests passed, 0 tests failed out of 231
Total Test time (real) = 219.58 sec
```
> Take into account that attach_dimscales can fail when dimensions and variables are named inconsistently

- CMakeLists.txt
Some symbols in the comments about deprecated symbols were using `-` instead of `_`
> Clean up some `-` vs `_` in some comments

- include/nclog.h
- include/ncrc.h
Both files use a `FILE*` somewhere, but miss a include to `stdio.h`. This was found while cross compiling the library using the rust bindings. Adding these includes fixes the compilation error.
> Add two missing includes

- .github/workflows/run_tests_osx.yml
> now install m4 on macos in CI

- configure.ac
> fixed some autoreconf warnings

- libhdf5/H5FDhttp.c
* Fixes #2990 
[Based on the feedback on from @jhendersonHDF](https://github.com/Unidata/netcdf-c/issues/2990#issuecomment-2310882647), I was able to eliminate in the error stack messages related to H5FDunregister, in my own environment (Ubuntu 22.04). I am testing this in other environments/compiler combinations, and I will integrate the PR @edwardhartnett put up to integrate a test for this issue, #3012, before final merge.
> Address ordering issue with HTTP VFD, H5FDunregister

- h5_test/tst_h_par_compress.c
Part of https://github.com/Unidata/netcdf-c/issues/2938
Adding parallel I/O testing with zstd with h5_tests.
This is part of trying to track down problems with parallel zstd in netCDF.
> HDF5 testing for parallel I/O including zstd (when present)

- configure.ac
* Fixes #3016 
Thanks to @edwardhartnett for pointing out that #2907 only addressed `cmake-based` builds.
> Check for libcurl should only happen if DAP and/or ncZarr are enabled.

- RELEASE_NOTES.md
* Fixes #3105
Update release notes to address an issue that took a while to draw some boundaries around.
> Added information re: mpich version 4.2.0 and related 'error' messages.

- include/netcdf.h
> Fix in support of https://github.com/Unidata/netcdf-c/issues/3007

- configure.ac
- nc-config.cmake.in
- nc-config.in
* Fixes #3032 
`--static` now implies `--libs` if `--libs` is omitted.
> Modify nc-config --libs and --static arguments

- acinclude.m4
- configure.ac
Part of #3006 
I thought I had taken care of these, but there is one last autoconf warning.
> autoconf cleanup

- include/netcdf_aux.h
- libdispatch/daux.c
- unit_test/Makefile.am
- unit_test/ref_xget.txt
- unit_test/ref_xset.txt
- unit_test/run_pluginpaths.sh
- unit_test/tst_pluginpaths.c
The new plugin path API uses char** to represent a variable lenght vector of variable length strings. FORTRAN is not capable of accessing such structures. So, this PR extends the API to provide a counted string-based API to the plugin path functionality.
The new functions are inserted in the netcdf_aux.h/daux.c files. The new functions are just wrappers around other plugin path API function; they are just (I hope) more convenient for FORTRAN users. The new functions are as follows:
* Return the length (as in strlen) of the current plugin path directories encoded as a string. Return -1 if the request fails.
* Get the current sequence of directories in the internal global plugin path list encoded as a string path using ';' as a path separator. As an example, it might return …
> Simplify FORTRAN access to the new plugin path mechanism

- plugins/CMakeLists.txt
This PR reverts the removal of the installation of necessary "base" plugins https://github.com/Unidata/netcdf-c/pull/3034/files#diff-1abf564a84becf73b24c833a7300a9fcaf5ff9df6427cb54fd53b297806669a0L141.
One could simple build and install a747f5ea761d494ec5135ca4c57ba495c921a7ef and with that the base plugins would be installed one last time, and if they stay in the system, this problem might go unnoticed for the following builds.
> CMAKE: Address #3055 - install plugins filters

- .github/workflows/run_tests_ubuntu.yml
- .github/workflows/run_tests_win_mingw.yml
> Update upload-artifact/download-artifact for github actions

- include/Makefile.am
- nc_test4/run_par_warn_test.sh.in
Without this, `build/include/netcdf_json.h` and `build/include_netcdf_proplist.h` simply contain the initial `#ifdev` line.
> Fix out-of-tree builds generating netcdf_json.h and netcdf_proplist.h

- .github/workflows/run_tests_win_cygwin.yml
- CMakeLists.txt
- libdap4/d4meta.c
Correct an issue reported by static analysis re: garbage/undefined dereference.
Clean out some cruft from CMakeLists.txt
> Clean up a couple small things while I'm looking at them.

- .github/workflows/run_tests_win_cygwin.yml
- CMakeLists.txt
- configure.ac
> Update default_chunk_cache_size 

- RELEASE_NOTES.md
- include/netcdf_aux.h
- libdispatch/daux.c
- ncdap_test/Makefile.am
- unit_test/Makefile.am
- unit_test/ref_provparse.txt
- unit_test/run_auxmisc.sh
- unit_test/test_auxmisc.c
re: Discussion https://github.com/Unidata/netcdf-c/discussions/3085
This discussion raised the issue of the best way to distinguish a netcdfd-c created file and an HDF5 created file. The recommended way is to use the _NCProperties attribute.  In order for users to process this attribute, I have added a parser for the attribute to the netcdf_aux.h file.
> Provide an auxilliary function that allows users to parse the _NCProperties attribute.

- CMakeLists.txt
This fixes a bug on 4.9.2 where an installed non-netcdf `config.h` (I think this was pulled in from a system library - unfortunately I don't have access to that machine myself) was included instead of netcdf's `config.h` due to the order of `-I` statements.
Another nice effect of this is it makes the order of `-I`s for cmake more similar to those generated by `./configure`.
> Give `config.h` a higher precedence.

- libdispatch/dinstance.c
- libdispatch/dinstance_intern.c
- unit_test/Makefile.am
- unit_test/reclaim_tests.baseline
- unit_test/reclaim_tests.cdl
- unit_test/run_reclaim_tests.sh
- unit_test/tst_reclaim.c
re: Issue https://github.com/Unidata/netcdf-c/issues/3110
There was a two-line typo in the code in netcdf-c/libdispatch/distance_intern.c. This PR fixes it and adds a test case in netcdf-c/unit_test/tst_reclaim.c.
> Fix bug in copying compound types with variable length fields.

- RELEASE_NOTES.md
- include/Makefile.am
- include/ncconfigure.h
- include/ncjson.h
- include/ncproplist.h
- libdispatch/ncjson.c
- libdispatch/ncproplist.c
- libnczarr/zsync.c
- libnczarr/zutil.c
- nc_test4/test_filterx_hdf5.c
- nczarr_test/ut_json.c
- nczarr_test/zisjson.c
- plugins/H5Znoop.c
- plugins/NCZmisc.c
- plugins/NCZtest.c
re: PR https://github.com/Unidata/netcdf-c/pull/3068
1. Update the ncjson and ncproplist code to latest.
2. Fix some references to older API functions.
3. Update the netcdf_json and netcdf_proplist builds.
> Step 1 in splitting PR 3068

- RELEASE_NOTES.md
- dap4_test/CMakeLists.txt
- dap4_test/Makefile.am
- dap4_test/test_hyrax.sh
- libncxml/ncxml_tinyxml2.cpp
- unit_test/run_reclaim_tests.sh
re: PR https://github.com/Unidata/netcdf-c/pull/3068
1. Fix a namespace problem in tinyxml2.cpp. Note that this is a visual studio problem hence use of _MSC_VER.
2. Turn off libdap4/test_hyrax.sh until such time as the DAP4 spec. problems are reconciled.
> Step 2 in splitting PR 3068

- include/ncs3sdk.h
- libdispatch/dhttp.c
- libdispatch/dinfermodel.c
- libdispatch/ds3util.c
- libdispatch/ncs3sdk_h5.c
- libnczarr/zmap_s3sdk.c
I stumble upon this when trying to read a netcdf file from a  **non-AWS** S3 bucket that requires authorization.
```
$ ncdump -L 11  -v time  "https://play.min.io/unidata/u_4km.nc#mode=bytes,s3&aws.profile=play"
log_level changed to 11
HDF5 error messages have been turned off.
ncdump/ncdump: https://play.min.io/unidata/u_4km.nc#mode=bytes,s3&aws.profile=play: NetCDF: Unknown file format
NC4_clear_provenance
NCZ_clear_provenance
```
I used [minio public testing S3 server](https://min.io/docs/minio/linux/administration/minio-console.html#id6) (~/.aws/credentials)
```
[play]
aws_access_key_id = Q3AM3UQ867SPQQA43P2F
aws_secret_access_key = zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
```
It seems that this is working for publicly available netcdf files in AWS S3 like the ones on the used on the …
> Broken S3 implementation for netcdf files on non-AWS + Authenticated buckets

- include/hdf5internal.h
- libhdf5/nc4hdf.c
- libsrc4/nc4internal.c
re: https://github.com/Unidata/netcdf-c/discussions/3085
This PR adds a check for _NCProperties provenance as part of _IsNetcdf4 test. This simplifies what the user needs to check to determine if a file is Netcdf-4. It also reduces the number of false negatives.
The primary change is to libhdf5/nc4hdf4.c. This change changes NC4_strict_att_exists to NC4_root_att_exists. This is used to check for root attributes whose existence indicate that a file is a Netcdf-4 file.
> Modify provenance check "_IsNetcdf4" to check for existence of "_NCProperties"

- include/ncpathmgr.h
- libdap4/ncd4.h
- libdispatch/dpathmgr.c
- libncxml/ncxml_xml2.c
- libnczarr/zmap_file.c
- libnczarr/zplugins.c
* Fixes #3139 
Something changed in the MSYS2/MinGW64-based runners, resulting in failures due to a pointer type mismatch (`stat` vs. `_stat64`).  This PR corrects this, although a little more testing is needed to make sure it's comprehensive.
> Fix pointer type on 64-bit Windows

- CMakeLists.txt
Moves the block copying nczarr tests data to be under `NETCDF_ENABLE_TESTS`
> Only conditionally copy test files

- libhdf5/hdf5open.c
Change null dataspace detection from abort to HDF error.
Null dataspace is legal in an HDF5 file, but not in the netcdf data model.
As a side effect, the underlying error return H5S_NO_CLASS is also changed from assertion failure and abort, to a normal error return to the caller.
Closes #3128.
> hdf5open.c: Handle null dataspace gracefully

- cmake/dependencies.cmake
- incorrect reference to `NETCDF_ENABLE_BYTERANGE_SUPPORT`
- should be `NETCDF_ENABLE_BYTERANGE`
> CMake: correct the byterange flag

- libhdf5/nc4hdf.c
- nc_test4/CMakeLists.txt
- nc_test4/Makefile.am
- nc_test4/run_zero_len_att_test.sh
- nc_test4/tst_zero_len_att.c
Fixes corner case overwriting a 1-character attribute value, with a zero-length string.
Closes issue https://github.com/Unidata/netcdf-c/issues/3154.
See discussion in that issue.
> nc4hdf.c: Fix overwrite with zero-length attribute

- docs/building-with-cmake.md
The CMake build evidently depends on m4 when not on a release branch. Document that requirement.
As a Windows developer, I do wish there was a way to sidestep this requirement, as it's not always straightfoward/viable to have m4 available on a Windows system.
If folks have ideas on how to accomplish that, I am more than happy to put in the work myself.
> CMake Builder Docs: document m4 dependency
