Unidata/netcdf-c

- oc2/daplex.c
Their is an ambiguity in the DAP2 spec.  Section A.2 of the
dap2 spec says:
"...The backslash character (.\.) MAY be used as
a single-character quoting mechanism only within
quoted-string and comment constructs.
quoted-pair = "\" CHAR
..."
The underlying problem was to allow for " chars inside
strings by using \". However, this definition is overbroad.
It is not stated:
1. if the backslash is to be left in the string or not.
2. There is also an unstated, but related issue of what
to do about e.g. '\n';convert to newline or not.
This change is to conform to libdap and it does the following:
1. The backslash is left in the string
2. Things like \n are left as is and it is assumed that
higher level code will decide what to do with e.g. \n.
> Github issue 134:

- libsrc4/nc4var.c
- nc_test4/tst_chunks.c
1. Added check to libsrc4/nc4var.nc_def_var_extra to
check that the no specified chunks size is greater than
the dimension size.
2. Added test to nc_test4/tst_chunks.c
> Fix github issues #140

- include/onstack.h
- oc2/ocinternal.c
Resolves #172, and a second issue with pid_t being redefined.
> Fix preprocessor for mingw

- nc_test4/tst_compounds3.c
Missed this file earlier somehow.  Same situation as fixed in fbc210f
> Replace NC_MAX_DIMS with NC_TESTS_MAX_DIMS

- nc_test4/bm_radar.c
> Replace NC_MAX_DIMS with NC_MAX_VAR_DIMS

- CONTRIBUTING.md
Added a TOC to contributing guidelines, also issuing this pull request in part to see how the guidelines are then presented.
> Added a table-of-contents to the contributing guideline file.

- cf
- libsrc4/nc4var.c
- nc_test4/Make0
- nc_test4/Makefile.am
- nc_test4/run_par_test.sh
- nc_test4/tst_mode.c
Return an error when specifying deflation (compression) or fletcher32 on
a file created for parallel IO in netcdf-4.
> Fix github issue: https://github.com/Unidata/netcdf-c/issues/208

- h5_test/tst_h_files.c
fixed compile warning in tst_h_files.c
Fixes #518.
> fixed compile warning in tst_h_files.c

- nc_test/tst_elatefill.c
- nc_test/tst_utf8_phrases.c
Fixes #535.
Fixes #534.
More warning fixes.
> fixed more warnings in nc_test

- libsrc/posixio.c
Fixes #537.
Simple warning fix.
> fixed warning in libsrc/posixio.c

- include/netcdf.h
- libdispatch/derror.c
Fixes #565.
Added a missing error message. Also cleaned up the doxygen comments for some of the error messages.
Also did an untabify operation on netcdf.h to clean up all the whitespace issues.
> added error code message for NC_EMPI

- libdap4/d4chunk.c
- libdap4/d4data.c
- libdap4/d4file.c
- libdap4/d4rc.c
- libdap4/d4swap.c
Fixes #582, as discussed with Dennis.
Also fixed some other easy warnings. Couldn't fix all of them, some are kind of weird and I don't want to mess with them. But I fixed the easy ones and reduced the number of warnings.
> fixed some warnings and incorrect assert

- nc_test/Makefile.am
- nc_test/tst_cdf5format.c
This is a nice test, originally contributed by @wkliao. It tests that files created with pnetcdf can be opened and modified with classic - similarly for CDF5.
Fixes #588.
> refurbished tst_cdf5format.c

- configure.ac
- h5_test/tst_h_atts3.c
- h5_test/tst_h_atts4.c
- h5_test/tst_h_dimscales.c
- libsrc4/nc4file.c
- nc_test4/tst_camrun.c
- nc_test4/tst_files4.c
- nc_test4/tst_interops.c
- nc_test4/tst_xplatform2.c
- nctest/Makefile.am
Fixes #608.
This is needed before I can submit my PR that will address #606.
> took out most uses of EXTRA_TESTS, returned it to disabled by default

- docs/mainpage.dox
> Corrected links to cdash dashboard.

- nc_test/tst_meta.c
Modify test to also verify that NC_HAS_META_H is defined
> Ensure NC_HAS_META_H is defined

- libsrc4/nc4grp.c
- nc_test4/tst_grps.c
- nc_test4/tst_types.c
- nc_test4/tst_vars2.c
- ncgen/genbin.c
Merging multiple pull requests from @gsjaardema into one to avoid the constant rechecking from Travis CI if they were merged one at a time.
> Gsjaardema batch merge

- libsrc4/nc4attr.c
- libsrc4/nc4internal.c
- nc_test4/tst_atts.c
- nc_test4/tst_atts2.c
Here are the bad parameter fixes for attributes. I refactored away some unneeded functions, and cleaned up the is_long junk.
Fixes #801.
Fixes #799.
Fixes #798.
Fixes #797.
Fixes #796.
> Fixes for attributes bad parameters, more testing

- libsrc/var.c
> Address a Windows NC3 Memory issue.

- examples/C/hdf5plugins/Makefile.am
- hdf4_test/run_get_hdf4_files.sh
- ncdap_test/tst_remote3.sh
Solution used here is to repeat the request
and to use the wget -c flag so we do not
start over on every retry.
> Attempt to fix the problem of ftp failing when getting the hdf4 from our ftp site.

- libdispatch/dv2i.c
- nc_test4/tst_converts2.c
* Fixes #928 
In support of https://github.com/Unidata/netcdf-c/issues/928
> Replace quotes when including system includes

- appveyor.yml
- docs/install.md
Testing exclusion syntax for appveyor.
> Testing Appveyor branch exclusion syntax.

- include/netcdf.h
nc_finalize() -> nc_finalize(void)
> Fix esupport # HYV-329576

- cf
- libdap2/daputil.c
- libdap2/dceparse.c
- libdispatch/nchashmap.c
- libhdf5/hdf5file.c
- libhdf5/hdf5open.c
- nc_test4/tst_filter.sh
- ncdump/nccopy.c
- ncdump/ocprint.c
- oc2/dapparse.c
Clear up coverity complaints with respect to this coverity report.
https://u2389337.ct.sendgrid.net/wf/click?upn=08onrYu34A-2BWcWUl-2F-2BfV0V05UPxvVjWch-2Bd2MGckcRZApv53Ry-2FReUME-2Fmei1et81WqdBwm5AxSAYBM9iFSmbw-3D-3D_YxTn3nq1kZ9CfXcyYFaB2DtJSVHTn8U-2BK0LV-2FDyLYKcFvnwYJ7pm2zFB5UovsEUh5miIfeCfQzYxpN9HYcdqs9sKVjtklOkfPIjEpg0Tj8G9wiptznJeX-2FO4PrqJA1ViQYtQfpjugq01XGMQ3-2Bll42dUMxrmbdYSqi8T7bCcANC5evyZs4MKvmAWXt1bnPaHcOYJDN-2FUt-2FJTlhwu91HyR7h-2FnkvMY9paYUNB1gxiyUA-3D
> Clear up coverity complaints

- liblib/nc_initialize.c
resolve issue: https://github.com/Unidata/netcdf-c/issues/1138
> Remove the set_fmode

- RELEASE_NOTES.md
@WardF not sure where to put these, but probably we want them in the release notes for the next release.
> added release notes

- docs/install.md
Minor documentation fix.
Fixes #291.
> minor doc change

- include/hdf5internal.h
- include/nc4internal.h
- libhdf5/hdf5attr.c
- libhdf5/hdf5create.c
- libhdf5/hdf5dim.c
- libhdf5/hdf5file.c
- libhdf5/hdf5grp.c
- libhdf5/hdf5internal.c
- libhdf5/hdf5open.c
- libhdf5/hdf5var.c
- libhdf5/nc4hdf.c
- libhdf5/nc4info.c
- libsrc4/nc4internal.c
Part of #856.
Moving the HDF5 group data into libhdf5.
This PR is in the queue behind #1186 and includes the changes from that PR.
> Next step in HDF5/libsrc4 separation - Moving HDF5 group info to libhdf5.

- configure.ac
Fixes #1195.
Fixes #1197.
Some fixes to configure.ac.
> Some fixes for configure.ac

- RELEASE_NOTES.md
- include/Makefile.am
- include/nc4internal.h
- include/nc_provenance.h
- ncdump/nccopy.c
- ncdump/ncdump.c
> Fixes #803

- CMakeLists.txt
- examples/C/parallel_vara.c
- include/hdf5internal.h
- libhdf5/hdf5attr.c
- libhdf5/hdf5dim.c
- libhdf5/hdf5file.c
- libhdf5/hdf5internal.c
- libhdf5/hdf5open.c
- libhdf5/hdf5type.c
- libhdf5/hdf5var.c
- libhdf5/nc4hdf.c
- libsrc4/nc4dim.c
- libsrc4/nc4internal.c
- nc_test/Makefile.am
- nc_test/tst_formatx_pnetcdf.c
- nc_test4/Makefile.am
- nc_test4/run_bm_elena.sh
- nc_test4/tst_files2.c
- ncdump/ncdump.c
- ncdump/tst_fileinfo.sh
Latest Merge
Contains the following collection of PR's (thus far).
* https://github.com/Unidata/netcdf-c/pull/1285
* https://github.com/Unidata/netcdf-c/pull/1271
* https://github.com/Unidata/netcdf-c/pull/1276
* https://github.com/Unidata/netcdf-c/pull/1277
* https://github.com/Unidata/netcdf-c/pull/1289
> Y.A.A. (Yet Another Another Aggregation)

- ncdump/ncdump.c
> Added newline after ncdump -k output

- examples/C/parallel_vara.c
- include/hdf5internal.h
- libhdf5/hdf5attr.c
- libhdf5/hdf5dim.c
- libhdf5/hdf5file.c
- libhdf5/hdf5internal.c
- libhdf5/hdf5open.c
- libhdf5/hdf5var.c
- libhdf5/nc4hdf.c
- libsrc4/nc4dim.c
- libsrc4/nc4internal.c
- nc_test/Makefile.am
- nc_test/tst_formatx_pnetcdf.c
- nc_test4/Makefile.am
- nc_test4/run_bm_elena.sh
- nc_test4/tst_files2.c
- ncdump/tst_fileinfo.sh
Fixes #1288.
Fixes #1287.
Fixes #1286.
Fixes #1282.
This PR is a grabbag of fixes. ;-)
This includes my currently outstanding PR on parallel warnings (#1271).
> Fix issues: excess variables, broken LOG statements, parallel build issue, benchmark build issue

- nc_test/tst_cdf5format.c
Fixed issue with C99 declarations of i,j counters in for loop.
> Added int i and j declarations

- dap4_test/CMakeLists.txt
- dap4_test/Makefile.am
- include/nctestserver.h
- libdap2/test_vara.c
- libdap4/d4meta.c
- ncdap_test/CMakeLists.txt
- ncdap_test/Makefile.am
Follow on to PR: https://github.com/Unidata/netcdf-c/pull/1302
> Fix additional big-endian machine error in dap4.

- nc_test4/tst_filterparser.c
> Fix typo in tst_filterparser.c

- libdap2/dapcvt.c
- libdispatch/dwinpath.c
- libsrc/memio.c
Some Win32 includes are also needed on MinGW
> Fix MinGW build

- .travis.yml
- CMakeLists.txt
- appveyor.yml
- configure.ac
- debug/cf
- docs/inmemory.md
- libsrc/mmapio.c
- nc_test/CMakeLists.txt
- nc_test/Makefile.am
- nc_test/ref_tst_diskless3_create.cdl
- nc_test/ref_tst_diskless3_open.cdl
- nc_test/run_diskless.sh
- nc_test/run_mmap.sh
- nc_test/tst_diskless.c
- nc_test/tst_diskless2.c
- nc_test/tst_diskless3.c
- nc_test4/Makefile.am
- ncgen/ncgen.h
- ncgen/semantics.c
supercede PR: https://github.com/Unidata/netcdf-c/pull/1384
Since we have an mmap user, undeprecate it and make sure
it works. Other changes:
* fix test cases to work with make -j
* fix exposed ncgen error.
> Fix cmake wrt mmap

- examples/C/CMakeLists.txt
- examples/C/Makefile.am
- examples/C/format.c
- examples/C/quick_large_files.c
- nc_test4/tst_vars4.c
> uncommented test

- configure.ac
- include/ncdimscale.h
- libdispatch/dfilter.c
- libhdf5/hdf5var.c
- liblib/nc_initialize.c
- libsrc4/nc4var.c
- nc_perf/Makefile.am
- nc_test/Makefile.am
- nc_test4/tst_large2.c
- nc_test4/tst_rename2.c
- nc_test4/tst_rename3.c
- nc_test4/tst_udf.c
Fixes #1401.
Fixes #1403.
Part of #1402.
Fixes #1399.
Some fixes for problems found by my CI system.
> fix compile warnings in tst_large2, tst_rename2, and tst_rename3, and some build issues, including partial fix for building with HDF4 but without HDF5

- docs/windows-binaries.md
Small change to documentation.
> Corrected mistake regarding VS version.

- libdispatch/dfile.c
- nc_test/Makefile.am
- nc_test/tst_formats.c
Fixes #1419 
Also add test to make sure we don't do this again. ;-)
Also, also test nc_create and nc_delete for the same problem. ;-)
> fix handling of NULL name in nc_open

- ncdump/ncvalidator.c
Fixes #1421 
Changed C++ comments to C comments.
> changed c++ style comments into c comments

- examples/C/Makefile.am
- examples/C/quick_large_files.c
- examples/C/quick_small_files.c
- examples/C/sfc_pres_temp_more.c
- examples/C/simple.c
Fixes #1333 
Fixes #1423 
Fix a warning, and add some examples that somehow stopped getting built somewhere along the line.
> fixed up extra examples

- libhdf4/hdf4dispatch.c
- libhdf4/hdf4file.c
- libhdf4/hdf4var.c
I am using the dispatch code with PIO right now and referring to my work in the HDF4 code for a good example.
As I do so, I found some incorrect comments and a line of useless code. They are all corrected in this PR.
> Fixing and expanding some documentation in the HDF4 code

- examples/C/sfc_pres_temp_more.c
Fixes #1429 
Fixes a memory issue in sft_pres_temp_more.c.
> Fix memory problem in example sfc_pres_temp_more.c

- configure.ac
Respect configure option--enable-erange-fill when used at configure command line.
> bug fix: respect configure option--enable-erange-fill

- nc_test4/tst_parallel.c
- nc_test4/tst_parallel5.c
Part of #1462
In this PR I add a test. Seems that the reported NC_BYTE bug does not exist in the current master, because this test passes.
> Testing for parallel I/O NC_BYTE bug

- Makefile.am
- configure.ac
- libdispatch/nc.c
- libdispatch/nclistmgr.c
- unit_test/Makefile.am
- unit_test/tst_nclist.c
Part of #1458 
Added more tests and code comments. This replaces my previous PR so I will take that down once this one passes Travis.
> more unit tests for nclistmgr.c

- RELEASE_NOTES.md
- include/nc.h
- include/nc4internal.h
- libdispatch/nclistmgr.c
- libsrc4/nc4internal.c
- unit_test/tst_nc4internal.c
- unit_test/tst_nclist.c
#1487 + a release notes entry.
> #1487 + Release Note entry

- libdispatch/ddispatch.c
> Fix NC_coord_zero indexing in NCDISPATCH_initialize()

- include/netcdf_dispatch.h
> fixed lack of boilerplate for C++ compilers in header file netcdf_dispatch.h

- CMakeLists.txt
- configure.ac
- include/netcdf_meta.h.in
- libdispatch/dvarget.c
- libdispatch/dvarput.c
- libhdf5/hdf5var.c
- libnetcdf.settings.in
- libsrc/putget.m4
- nc_test/Makefile.am
- nc_test/test_get.m4
- nc_test/test_put.m4
- nc_test/test_read.m4
- nc_test/test_write.m4
> Make RELAX_COORD_BOUNDS mandatory for all builds

- nc_perf/bm_file.c
> update of benchmark program bm_file to prevent integer overflows on very big files

- .gitignore
File is produced but not ignored, leaving a dirty tree when building
> add file to .gitignore

- dap4_test/Makefile.am
> fixed distclean target in dap4_test

- RELEASE_NOTES.md
This PR simply adds release notes for the PRs I've submitted which have been merged since the last release.
> updated RELEASE_NOTES to include results of recent PR merges

- nc_test4/tst_unlim_vars.c
After a recent bug I was worried that there might be more problems lurking when multiple vars shared multiple unlimited dimensions, and one of the vars had data written, extending an unlimited dimension.
But if there are more bugs I have not found them today. My new tests work fine. ;-)
Fixes #1567
> more tests for variables that share multiple unlimited dimensions

- RELEASE_NOTES.md
- h5_test/tst_h_files.c
- libdispatch/dparallel.c
- libdispatch/dvar.c
- nc_test4/tst_parallel5.c
- unit_test/tst_nclist.c
Fixes #1656 
Fixes #1653 
Fixes #1652
Fix some issue, also update documentation for nc_var_par_access() and nc_def_var_chunking() to cover recent changes.
> Fix largefile issue, szip parallel test, and some documentation updates

- libdispatch/dvarinq.c
- nc_test4/tst_vars2.c
> now pass 0 for deflate_level if deflate not in use

- libhdf5/hdf5var.c
- libsrc4/nc4var.c
> fixed documentation of cache int functions

- README.md
Fixed a dead link in README.md
> Correcting dead link to installation

- docs/footer.html
Ensure that the nav-tree extends to the full height of the content area. The footer must be enclosed in a div element with the id="nav-path" for this to work.
> Ensure nav-tree is the correct height

- docs/FAQ.md
This updates the broken links from Issue #1696 .
> Updating Links in FAQ.md

- ncdump/ncdump.c
- ncgen/ncgen.1
Fix wrong keywords in ncdump and ncgen man page.
> Fix incorrect keywords.

- configure.ac
> Fix parallel NetCDF checks in configure.ac for spectrum MPI

- plugins/Makefile.am
> fixed the setting of AM_LDFLAGS

- libhdf5/hdf5filter.c
> fixed warning in hdf5filter.c

- RELEASE_NOTES.md
- libhdf5/hdf5file.c
- nc_test4/tst_files.c
This is PR #1781 plus a modest conflict resolution in RELEASE_NOTES.md.
> Noaa gsd ejh fix redef

- CMakeLists.txt
- configure.ac
> fixed dispatch version number in CMakeLists.txt

- include/isnan.h
I'm not certain why this wasn't in `master` already, the change was already in a local repository on my laptop, but a fresh checkout lacked the update.
> Minor update for OSX

- libnczarr/zdebug.c
- libnczarr/zdebug.h
- libnczarr/zwalk.c
- nczarr_test/ut_chunking.c
- nczarr_test/ut_includes.h
- nczarr_test/ut_projections.c
* Fixes #1839 
Fix issue https://github.com/Unidata/netcdf-c/issues/1839 -- missing symbols under OSX
> Fix issue 1839 -- missing symbols under OSX

- libnczarr/zfilter.c
- libsrc4/nc4var.c
Fix Issue https://github.com/Unidata/netcdf-c/issues/1858
> Fix missing casts of var->filters

- RELEASE_NOTES.md
- libdap4/d4util.c
- libdap4/ncd4.h
This is #1871 plus updated Release Notes.
> d4align fix + release notes

- configure.ac
- plugins/Makefile.am
> Compilation failure in plugins/ when sanitizing memory

- .travis.yml
As per a request by @DennisHeimbigner, Restoring .travis.yml file for convienence until Github Actions are i…ntegrated, but not restoring the requirement that they pass (due to throttled Travis runs) for PR's to be merged.
> Restore .travis.yml file, but not dependency.

- CMakeLists.txt
- libsrc/CMakeLists.txt
- ncgen/ncgenl.c
- ncgen/ncgeny.c
- ncgen/ncgeny.h
It's #1740 plus conflicts resolved and Github Actions.
> Fixing up PR 1740

- .github/workflows/run_tests.yml
Added an "apt update" to the github action script to try to fix a broken mirror issue.
> Added an apt update stanza to the github action script.

- CMakeLists.txt
> Fix detection and use of SZIP library

- .github/workflows/run_tests.yml
- nczarr_test/CMakeLists.txt
- nczarr_test/Makefile.am
Changes:
1. add "use_nczarr: [ nczarr_off, nczarr_on ]" to matrix
2. add libzip-dev to the apt installs (might need caching).
3. convert deprecated "--enable-netcdf-4" to "--enable-hdf5" (also for cmake)
4. Disable run_chunkcases
> Enable nczarr testing in github actions.

- ncdump/nccopy.c
> Fix memory leak in nccopy.c

- RELEASE_NOTES.md
- plugins/Makefile.am
- plugins/blocksort.c
- plugins/bzlib.c
- plugins/bzlib.h
- plugins/bzlib_private.h
- plugins/compress.c
- plugins/crctable.c
- plugins/decompress.c
- plugins/huffman.c
- plugins/randtable.c
This is #1970 plus updated release notes.
> PR1970 + Release Notes

- h5_test/tst_h_atts3.c
> Fix tst_h_atts3 for hdf5 1.12

- nc_perf/tst_gfs_data_1.c
Fixes #1997 
Improved the decompositions and data for tst_gfs_data_1.c, a parallel I/O benchmarking program.
> improved program nc_perf/tst_gfs_data_1.c

- nc_test4/tst_fill_attr_vanish.c
> Fix in support of https://github.com/Unidata/netcdf-c/issues/2027

- .github/workflows/run_tests.yml
added 1.12.1 to hdf5 versions built by GitHub actions
Let's see how it works! ;-)
> added 1.12.1 to hdf5 versions built by GitHub actions

- libhdf5/nc4hdf.c
- nc_test4/tst_vars2.c
> The coord dimids should be written for all variables

- ncdump/cdl/ref_tst_econst.cdl
- ncdump/cdl/ref_tst_econst2.cdl
- ncdump/expected/ref_tst_econst2.dmp
- ncdump/tst_ncgen4_cycle.sh
- ncdump/tst_ncgen_shared.sh
- ncgen/semantics.c
re: Issue https://github.com/Unidata/netcdf-c/issues/2108
Fix ncgen to properly locate a matching enum type when it encounters
a reference to an enum constant. Add test cases.
> Fix handling of enum constants nested in compound types.

- libdispatch/dinfermodel.c
* Fixes https://github.com/Unidata/netcdf-c/issues/2136
Patch for: https://github.com/Unidata/netcdf-c/pull/2134/
Inadvertent error changing ->info to ->s3.
> Typo in previous PR

- libhdf5/hdf5var.c
- nc_perf/Makefile.am
- nc_perf/run_gfs_test.sh.in
- nc_perf/tst_compress.c
- nc_test4/tst_quantize.c
- nc_test4/tst_vars.c
Fixes #2155 
Now setting deflate_level of 0 is interpreted to mean no deflate.
Also added a benchmarking programming that helped me figure this problem out...
> Now setting deflate_level of 0 is interpreted to mean no deflate.

- nc_test4/tst_quantize.c
Adding another test for quantize to tst_quantize.c.
This test acts as an example of using quantize in our AGU paper...
Part of #1548
> adding quantize test

- nc_perf/run_gfs_test.sh.in
Fixes #2149 
Fixed running tst_compress_par.
> fixed benchmark program run

- libdispatch/dpathmgr.c
* Fixes #2203 
Thank you @abhibaruah for reporting a memory leak, this PR corrects it.
> Correct a memory leak as reported in #2203

- README.md
* Fixes #1350 
Add a new badge, remove stale ones.
> Remove stale badges, add badge for Repology 

- CMakeLists.txt
* Fixes #2103 
Rebase of #2103 against current `main`.
> Rebase of #2103

- ncdump/ncdump.c
Rebase of #2104 to take advantage of the new GitHub Action-based CI.
> Rebase of #2104

- docs/CMakeLists.txt
> Change order in which auth.html is generated and copied.

- docs/static-pages/credits.html
- docs/static-pages/software.html
Incorporate static pages into version control.  This reorganization will continue, some pages will end up in the NUG repository, but this is the first step.
> Static page/documentation reorganization.

- .github/workflows/run_tests_ubuntu.yml
- libsrc4/nc4var.c
This is #2261 plus the addition of parallel github action-based tests.
> Fix parallel build issue, add Parallel Tests Github Actions

- .github/workflows/run_tests_ubuntu.yml
- examples/C/Makefile.am
turning on parallel I/O tests in CI
Part of #1655
> turning on parallel I/O tests in CI

- docs/windows-binaries.md
> Update URL for windows downloads.

- nc_test4/tst_parallel_zlib.c
Future-proofing when this is but a faded memory and I would spend 10 minutes either jumping into the line specified by `ERR` for an error directly observed or submitted by an end user.  Unlikely, perhaps, but those are the best types of issues to get in front of.
> #2323 plus mpi_count error message

- docs/static-pages/software.html
> Correct links for gliderscope and netcdfninja in software.html

- nc-config.in
Fixes #2320 
Add has_zstd and has_benchmarks to nc-config.
> added some entries to nc-config

- docs/dispatch.md
- docs/internal.md
- docs/nczarr.md
- docs/notes.md
Part of #2329 
Fixed some doxygen warnings.
> fixed some doxygen warnings

- libhdf5/hdf5dim.c
- libhdf5/hdf5var.c
- nc_test4/tst_dims3.c
Fixes #2357 
See discussion in issue...
> fixing issues with dimlens of unlitmited dims in complex situations

- .github/workflows/run_tests_osx.yml
- .github/workflows/run_tests_win_mingw.yml
Added manual `workflow_dispatch` to trigger for OSX, MinGW/MSYS tests.
> Add manual GitHub actions triggers for the tests.

- .github/workflows/run_tests_osx.yml
- .github/workflows/run_tests_ubuntu.yml
Bumping hdf5 from 1.12.1 to 1.12.2.
> Update hdf5 version in github actions.

- plugins/Makefile.am
> Update plugins/Makefile.am 

- docs/static-pages/orgs.html
- docs/static-pages/standards.html
A couple of old static files were misplaced during a migration. Re-adding so they can be modernized and folded back in to the documentation.
> Add an old static file.

- libdispatch/dv2i.c
> Fix symbol export on Windows

- libsrc/posixio.c
See https://github.com/Unidata/netcdf-c/pull/2437#issuecomment-1419381660
> Incorporate fix for errno check when fd < 0

- CMakeLists.txt
In #2463 there was a typo which set dest incorrectly
> Fix dest for non-m4 path

- configure.ac
- dap4_test/Makefile.am
- libdap4/d4parser.c
> Cleaning up a few stray issues

- docs/logging.md
- nc_test4/tst_parallel3.c
Fixes #2676 
@georgevandenburgh this will be of interest to you.
> Add documentation for logging

- nc-config.in
> Fix --has-quantize in autotools-generated nc-config.

- docs/static-pages/software.html
Add package to `software.html` list.
> Updated static software.html page with reference to met.3d

- ncdump/chunkspec.c
- ncdump/chunkspec.h
- ncdump/dumplib.c
- ncdump/list.c
- ncdump/nc4printer.c
- ncdump/nccopy.c
- ncdump/ncdump.c
- ncdump/nchdf5version.c
- ncdump/nciter.c
- ncdump/nctime0.c
- ncdump/ncvalidator.c
- ncdump/ocprint.c
- ncdump/tst_comp.c
- ncdump/tst_comp2.c
- ncdump/tst_opaque_data.c
- ncdump/tst_vlen_data.c
- ncdump/utils.c
- ncdump/utils.h
- ncdump/vardata.c
- ncgen/dump.c
Fix ~120 warnings from the `ncdump` directory
> Silence ncdump warnings

- CMakeLists.txt
> Add compiler flag to fix infinities issue with intel compilers.

- libdispatch/dvar.c
- libdispatch/dvarget.c
- libdispatch/dvarput.c
- libhdf5/hdf5var.c
> added documentation for start/count/stride mandating same size arrays as data variable

- nc_test4/tst_parallel_compress.c
Some test code was commented out, due to old debugging.
This PR uncomments some extra test code.
> turned on some commented out test code

- nc_test4/tst_specific_filters.sh
Oops, fix bug in previous pull request.
> Replace PR https://github.com/Unidata/netcdf-c/pull/3046

- RELEASE_NOTES.md
- nc-config.cmake.in
- nc-config.in
Makes some changes to `nc-config.cmake.in` and `nc-config.in` to report `plugin-search-path`.
> Update nc-config in support of changes made in #3034

- docs/all-error-codes.md
- include/netcdf.h
> Update error code list.

- libsrc4/nc4var.c
Addresses #3091
Issue #3091 points out that the quantization routine Granular BitRound raises a SIGFPE when it receives negative zero (-0.0) input. Since -0.0 is a legal IEEE value, this is a bug. (I have never seen -0.0 occur "in the wild" but it is a legal value and so this should be fixed). Testing reveals that BitGroom also suffered from the same issue. BitRound itself is/was well-behaved. 
During discussion of #3091 @Dave-Allured asked whether the quantization routines were safe for NaNs. Offline testing in NCO showed that NaNs were always successfully handled (meaning they were not quantized) even though there were no explicity fenceposts around handling NaNs. This patch implements NaN-specific fenceposts around the quantization routines, and now fenceposts -0.0 values as well as …
> Fix SIGFPE with -0.0 values and quantization

- libdispatch/dpathmgr.c
> Fix reported memory leak

- docs/static-pages/software.html
Do not merge before 2025-08-04.
> Update Software list with contribution.
